using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Xunit;
using Xunit.Abstractions;

namespace PgProj.Core.Tests;

/// <summary>
/// Code-generates one [Fact] per corpus case under Corpus/*.g.cs (one partial class per category).
/// Cases the parser does not yet handle are emitted with [Fact(Skip=...)] based on the committed
/// tests/corpus/_pending.txt list, so `dotnet test` stays GREEN while the suite drives TDD: to work
/// a feature, remove its ids from _pending.txt, regenerate, and the now-active tests must pass.
///
/// Run:   PGPROJ_GEN_CORPUS_TESTS=1 dotnet test --filter FullyQualifiedName~Generate_per_case_corpus_tests
/// Reseed pending from current parser behaviour (first time / deliberate reset):
///        PGPROJ_GEN_CORPUS_TESTS=1 PGPROJ_GEN_RECOMPUTE_PENDING=1 dotnet test --filter ...Generate_per_case...
/// </summary>
public class CorpusTestGenerator
{
    private readonly ITestOutputHelper _out;
    public CorpusTestGenerator(ITestOutputHelper output) => _out = output;

    [Fact]
    public void Generate_per_case_corpus_tests()
    {
        if (Environment.GetEnvironmentVariable("PGPROJ_GEN_CORPUS_TESTS") != "1")
            return; // no-op unless explicitly invoked

        var cases = CorpusData.LoadAll();
        Assert.True(cases.Count > 0, "no corpus cases found");

        var pendingPath = Path.Combine(CorpusData.CorpusDir, "_pending.txt");
        HashSet<string> pending;
        if (File.Exists(pendingPath) && Environment.GetEnvironmentVariable("PGPROJ_GEN_RECOMPUTE_PENDING") != "1")
        {
            pending = new HashSet<string>(
                File.ReadAllLines(pendingPath)
                    .Select(l => l.Trim())
                    .Where(l => l.Length > 0 && !l.StartsWith('#')),
                StringComparer.Ordinal);
            _out.WriteLine($"loaded {pending.Count} pending ids from _pending.txt");
        }
        else
        {
            pending = new HashSet<string>(
                cases.Where(c => !CorpusData.Passes(c)).Select(c => c.Id), StringComparer.Ordinal);
            var header = new[]
            {
                "# Corpus cases the parser does not YET handle (emitted as [Fact(Skip=...)]).",
                "# Burn down: delete ids here, regenerate, then implement until the activated tests pass.",
                "# Regenerate: PGPROJ_GEN_CORPUS_TESTS=1 dotnet test --filter ...Generate_per_case...",
            };
            File.WriteAllLines(pendingPath, header.Concat(pending.OrderBy(x => x, StringComparer.Ordinal)));
            _out.WriteLine($"computed and wrote {pending.Count} pending ids (current parser failures)");
        }

        var outDir = Path.Combine(CorpusData.RepoRoot, "tests", "PgProj.Core.Tests", "Corpus");
        Directory.CreateDirectory(outDir);
        foreach (var old in Directory.EnumerateFiles(outDir, "*.g.cs")) File.Delete(old);

        int emitted = 0, skipped = 0, files = 0;
        foreach (var group in cases.GroupBy(c => c.Category).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var className = "Corpus_" + Pascal(group.Key);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> Generated from tests/corpus/*.jsonl by CorpusTestGenerator. Do not edit by hand. </auto-generated>");
            sb.AppendLine("using Xunit;");
            sb.AppendLine();
            sb.AppendLine("namespace PgProj.Core.Tests.Corpus;");
            sb.AppendLine();
            sb.AppendLine($"public class {className}");
            sb.AppendLine("{");

            var usedNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var c in group.OrderBy(c => c.Id, StringComparer.Ordinal))
            {
                var name = MethodName(c.Id, usedNames);
                var sql = "@\"" + c.Sql.Replace("\"", "\"\"") + "\"";
                if (pending.Contains(c.Id))
                {
                    sb.AppendLine($"    [Fact(Skip = \"pending: parser not yet complete\")]");
                    skipped++;
                }
                else
                {
                    sb.AppendLine($"    [Fact]");
                    emitted++;
                }
                sb.AppendLine($"    public void {name}() => CorpusAssert.Parses({sql}, \"{c.Expect}\");");
            }

            sb.AppendLine("}");
            File.WriteAllText(Path.Combine(outDir, className + ".g.cs"), sb.ToString());
            files++;
        }

        _out.WriteLine($"generated {files} files, {emitted + skipped} [Fact] methods ({emitted} active, {skipped} skipped)");
        Assert.Equal(cases.Count, emitted + skipped);
    }

    private static string Pascal(string kebab) =>
        string.Concat(kebab.Split('-', '_', ' ')
            .Where(p => p.Length > 0)
            .Select(p => char.ToUpperInvariant(p[0]) + p[1..]));

    private static string MethodName(string id, HashSet<string> used)
    {
        var chars = id.Select(ch => char.IsLetterOrDigit(ch) ? ch : '_').ToArray();
        var name = new string(chars);
        if (name.Length == 0 || char.IsDigit(name[0])) name = "_" + name;
        var baseName = name;
        int i = 1;
        while (!used.Add(name)) name = baseName + "_" + i++;
        return name;
    }
}
