using System.Linq;
using PgProj.Core.Syntax;
using Xunit;

namespace PgProj.Core.Tests;

/// <summary>
/// Focused unit tests for the hand-written <see cref="PgParser"/> CREATE TABLE grammar. Each test
/// targets one production and inspects the typed AST, so a failure points at a single rule.
/// </summary>
public class CreateTableSyntaxTests
{
    private static CreateTableStatement Table(string sql)
    {
        var res = new PgParser().Parse(sql);
        Assert.True(res.FullyRecognized);
        Assert.Empty(res.Diagnostics);
        return res.Statements.OfType<CreateTableStatement>().Single();
    }

    private static ParseResult Parse(string sql) => new PgParser().Parse(sql);

    [Fact]
    public void Columns_and_types_with_defaults_and_notnull()
    {
        var t = Table("CREATE TABLE s.t (id bigint, name varchar(50) NOT NULL DEFAULT 'x', flag boolean DEFAULT NULL)");
        Assert.Equal(3, t.Columns.Count);
        Assert.Equal("bigint", t.Columns[0].Type.Text);
        Assert.Contains(t.Columns[1].Constraints, c => c is NotNullConstraint);
        var def = t.Columns[2].Constraints.OfType<DefaultConstraint>().Single();
        Assert.Equal("NULL", def.Expression);
    }

    [Fact]
    public void Primary_key_with_include()
    {
        var pk = Table("CREATE TABLE s.t (a int, b text, PRIMARY KEY (a) INCLUDE (b))")
            .Constraints.OfType<PrimaryKeyConstraint>().Single();
        Assert.Equal(new[] { "a" }, pk.Columns);
        Assert.Equal(new[] { "b" }, pk.Include);
    }

    [Fact]
    public void Unique_nulls_not_distinct()
    {
        var u = Table("CREATE TABLE s.t (a text, UNIQUE NULLS NOT DISTINCT (a))")
            .Constraints.OfType<UniqueConstraint>().Single();
        Assert.True(u.NullsNotDistinct);
        Assert.Equal(new[] { "a" }, u.Columns);
    }

    [Fact]
    public void Foreign_key_match_actions_and_deferrable()
    {
        var fk = Table("CREATE TABLE s.t (x bigint, FOREIGN KEY (x) REFERENCES s.u (id) MATCH FULL ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY DEFERRED)")
            .Constraints.OfType<ForeignKeyConstraint>().Single();
        Assert.Equal("FULL", fk.Match);
        Assert.Equal("CASCADE", fk.OnDelete!.Action);
        Assert.Equal("RESTRICT", fk.OnUpdate!.Action);
        Assert.True(fk.Deferrability.Deferrable);
        Assert.True(fk.Deferrability.InitiallyDeferred);
    }

    [Fact]
    public void Foreign_key_on_delete_set_null_columns()
    {
        var fk = Table("CREATE TABLE s.t (a bigint, b text, FOREIGN KEY (a, b) REFERENCES s.u (a, b) ON DELETE SET NULL (a, b))")
            .Constraints.OfType<ForeignKeyConstraint>().Single();
        Assert.Equal("SET NULL", fk.OnDelete!.Action);
        Assert.Equal(new[] { "a", "b" }, fk.OnDelete.Columns);
    }

    [Fact]
    public void Check_no_inherit_and_not_valid()
    {
        var chk = Table("CREATE TABLE s.t (v int, CONSTRAINT c CHECK (v > 0) NO INHERIT NOT VALID)")
            .Constraints.OfType<CheckConstraint>().Single();
        Assert.Equal("c", chk.Name);
        Assert.True(chk.NoInherit);
        Assert.True(chk.NotValid);
    }

    [Fact]
    public void Table_level_not_null_pg18()
    {
        var nn = Table("CREATE TABLE s.t (id int, name text, NOT NULL name)")
            .Constraints.OfType<NotNullTableConstraint>().Single();
        Assert.Equal("name", nn.Column);
    }

    [Fact]
    public void Generated_stored_and_virtual_and_identity()
    {
        var t = Table("CREATE TABLE s.t (a int, b int GENERATED ALWAYS AS (a + 1) STORED, c int GENERATED ALWAYS AS (a * 2) VIRTUAL, d int GENERATED BY DEFAULT AS IDENTITY)");
        Assert.Single(t.Columns[1].Constraints.OfType<GeneratedStored>());
        Assert.Single(t.Columns[2].Constraints.OfType<GeneratedStored>());
        Assert.Equal("BY DEFAULT", t.Columns[3].Constraints.OfType<GeneratedIdentity>().Single().Kind);
    }

    [Fact]
    public void Create_table_as_with_column_alias_list()
    {
        var res = Parse("CREATE TABLE t (a, b) AS SELECT id, name FROM s.t");
        Assert.True(res.FullyRecognized);
        Assert.Empty(res.Diagnostics);
        var ctas = res.Statements.OfType<CreateTableAsStatement>().Single();
        Assert.Equal(new[] { "a", "b" }, ctas.ColumnAliases);
    }

    [Theory]
    [InlineData("CREATE TABLE s.t (a int,)")]                                          // trailing comma
    [InlineData("CREATE TABLE s.t (a)")]                                               // column without a type
    [InlineData("CREATE TABLE s.t (v int, CHECK (v > 0) DEFERRABLE)")]                 // CHECK can't be deferrable
    [InlineData("CREATE TABLE s.t (a int, UNIQUE (a) NOT DEFERRABLE INITIALLY DEFERRED)")] // contradictory
    [InlineData("CREATE TABLE s.t (a bigint, FOREIGN KEY (a) REFERENCES s.u (id) ON UPDATE SET NULL (a))")] // cols only on ON DELETE
    [InlineData("CREATE TABLE t (a, a) AS SELECT 1, 2")]                               // duplicate alias
    public void Rejects_invalid(string sql)
    {
        var res = Parse(sql);
        Assert.True(res.FullyRecognized);
        Assert.NotEmpty(res.Diagnostics);
    }

    [Fact]
    public void Diagnostics_carry_line_and_column()
    {
        var res = Parse("CREATE TABLE s.t (a int,)");
        var d = res.Diagnostics.Single();
        Assert.Equal(1, d.Line);
        Assert.True(d.Column > 1);
    }
}
