using System.Linq;
using PgProj.Core.Parsing;
using Xunit;

namespace PgProj.Core.Tests;

public class ParserTests
{
    [Fact]
    public void Parses_table_with_columns_constraints_and_defaults()
    {
        const string sql = """
            CREATE SCHEMA app;
            CREATE TABLE app.customers (
                id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email      varchar(255) NOT NULL,
                status     varchar(20)  NOT NULL DEFAULT 'active',
                created_at timestamptz  NOT NULL DEFAULT now()
            );
            """;

        var model = new SqlParser().Parse(sql);

        Assert.True(model.HasSchema("app"));
        var t = model.FindTable("app", "customers");
        Assert.NotNull(t);
        Assert.Equal(4, t!.Columns.Count);

        var id = t.FindColumn("id")!;
        Assert.Equal("bigint", id.DataType);
        Assert.True(id.IsIdentity);
        Assert.False(id.IsNullable); // primary key implies NOT NULL

        Assert.Equal("character varying(255)", t.FindColumn("email")!.DataType);

        var status = t.FindColumn("status")!;
        Assert.Equal("'active'", status.Default);
        Assert.False(status.IsNullable);

        var createdAt = t.FindColumn("created_at")!;
        Assert.Equal("timestamp with time zone", createdAt.DataType);
        Assert.Equal("now()", createdAt.Default);

        Assert.NotNull(t.PrimaryKey);
        Assert.Equal(new[] { "id" }, t.PrimaryKey!.Columns);
    }

    [Fact]
    public void Parses_inline_foreign_key_with_actions()
    {
        const string sql = """
            CREATE TABLE app.orders (
                id          bigint PRIMARY KEY,
                customer_id bigint NOT NULL REFERENCES app.customers (id) ON DELETE CASCADE
            );
            """;

        var t = new SqlParser().Parse(sql).FindTable("app", "orders")!;
        var fk = Assert.Single(t.ForeignKeys);
        Assert.Equal(new[] { "customer_id" }, fk.Columns);
        Assert.Equal("app", fk.ReferencedSchema);
        Assert.Equal("customers", fk.ReferencedTable);
        Assert.Equal(new[] { "id" }, fk.ReferencedColumns);
        Assert.Equal("CASCADE", fk.OnDelete);
    }

    [Fact]
    public void Parses_table_level_composite_primary_key()
    {
        const string sql = """
            CREATE TABLE app.membership (
                team_id bigint NOT NULL,
                user_id bigint NOT NULL,
                CONSTRAINT membership_pkey PRIMARY KEY (team_id, user_id)
            );
            """;

        var t = new SqlParser().Parse(sql).FindTable("app", "membership")!;
        Assert.Equal("membership_pkey", t.PrimaryKey!.Name);
        Assert.Equal(new[] { "team_id", "user_id" }, t.PrimaryKey!.Columns);
    }

    [Fact]
    public void Parses_unique_index()
    {
        const string sql = "CREATE UNIQUE INDEX customers_email_idx ON app.customers (email);";
        var ix = Assert.Single(new SqlParser().Parse(sql).Indexes);
        Assert.True(ix.IsUnique);
        Assert.Equal("customers_email_idx", ix.Name);
        Assert.Equal("app", ix.Schema);
        Assert.Equal("customers", ix.Table);
        Assert.Equal(new[] { "email" }, ix.Columns);
    }

    [Fact]
    public void Parses_view_and_function_with_dollar_body()
    {
        const string sql = """
            CREATE OR REPLACE VIEW app.v AS SELECT 1 AS one;
            CREATE OR REPLACE FUNCTION app.f() RETURNS integer LANGUAGE sql AS $$
                SELECT 1; -- a semicolon inside the body must not split the statement
            $$;
            """;

        var model = new SqlParser().Parse(sql);
        var v = Assert.Single(model.Views);
        Assert.Equal("app", v.Schema);
        Assert.Contains("select", v.Body, System.StringComparison.OrdinalIgnoreCase);

        var f = Assert.Single(model.Functions);
        Assert.Equal("app.f()", f.Signature);
        Assert.Contains("$$", f.Body);
    }

    [Fact]
    public void Default_schema_is_applied_when_unqualified()
    {
        var t = new SqlParser("app").Parse("CREATE TABLE widgets (id int);").FindTable("app", "widgets");
        Assert.NotNull(t);
    }

    [Fact]
    public void Comments_are_ignored()
    {
        const string sql = """
            -- a line comment
            CREATE TABLE app.t ( /* inline */ id int );
            """;
        Assert.NotNull(new SqlParser().Parse(sql).FindTable("app", "t"));
    }
}
