using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PgProj.Core.Model;

namespace PgProj.Core.Testing;

/// <summary>Which test categories the suite generator emits. All default on; the CLI maps a CSV onto these.</summary>
public sealed record SuiteOptions
{
    public bool Constraints { get; init; } = true;   // NOT NULL / UNIQUE / PK negatives (+ CHECK stubs)
    public bool ForeignKeys { get; init; } = true;    // orphan-insert negatives
    public bool Crud { get; init; } = true;           // baseline insert round-trip
    public bool Views { get; init; } = true;          // view / matview queryability
    public bool UnitStubs { get; init; } = true;      // function / procedure / trigger stubs
    public bool Existence { get; init; } = true;       // catalog existence smoke tests for other kinds

    public static SuiteOptions All => new();

    /// <summary>Map a CSV like "constraints,fk,crud,view,unit,exists" onto the flags (unknown tokens throw).</summary>
    public static SuiteOptions Parse(string? csv)
    {
        if (string.IsNullOrWhiteSpace(csv)) return All;
        bool c = false, fk = false, crud = false, v = false, u = false, e = false;
        foreach (var raw in csv.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            switch (raw.ToLowerInvariant())
            {
                case "constraints": case "constraint": c = true; break;
                case "fk": case "foreignkeys": case "foreign-keys": fk = true; break;
                case "crud": crud = true; break;
                case "view": case "views": v = true; break;
                case "unit": case "stubs": u = true; break;
                case "exists": case "existence": e = true; break;
                default: throw new ArgumentException($"Unknown test category '{raw}' (use: constraints,fk,crud,view,unit,exists).");
            }
        return new SuiteOptions { Constraints = c, ForeignKeys = fk, Crud = crud, Views = v, UnitStubs = u, Existence = e };
    }
}

/// <summary>
/// Generates a COMPLETE, auto-asserted test suite (#153) from a built <see cref="DatabaseModel"/> — one
/// <c>.test.sql</c> per (object, category), run as-is by <see cref="PgUnitRunner"/>. Unlike the single-object
/// <see cref="TestScaffolder"/> (which it reuses for function/procedure/trigger stubs), this walks the whole
/// model and emits runnable assertions wherever the model gives enough information: constraint-enforcement and
/// FK negatives (via the <c>-- @expect-sqlstate:</c> directive), CRUD round-trips, view queryability, and
/// catalog existence smoke tests. Where a true value cannot be synthesised (enum/domain/UDT columns, non-trivial
/// CHECKs, an FK to a table outside the model) it DOWNGRADES to an inconclusive stub rather than emit a false
/// assertion. Output is deterministic (no randomness; <c>gen_random_uuid()</c>/<c>now()</c> evaluate at run time)
/// and every file carries the <see cref="Sentinel"/> header so regeneration can replace only its own files.
/// </summary>
public static class SuiteScaffolder
{
    /// <summary>Marker placed in every generated file's header; regeneration deletes only files carrying it.</summary>
    public const string Sentinel = "@pgproj-generated";
    private const string SentinelLine = "-- " + Sentinel + ": do not edit — regenerated by 'pgproj test generate'";

    /// <summary>Walk the model and emit the full suite, sorted by file name for deterministic output.</summary>
    public static IReadOnlyList<ScaffoldResult> GenerateSuite(DatabaseModel model, SuiteOptions options)
    {
        var results = new List<ScaffoldResult>();

        foreach (var table in model.Tables)
        {
            if (options.Constraints) AddConstraintTests(model, table, results);
            if (options.ForeignKeys) AddForeignKeyTests(model, table, results);
            if (options.Crud) AddCrudTest(model, table, results);
        }

        if (options.Views)
            foreach (var view in model.Views)
                results.Add(ViewTest(view));

        if (options.UnitStubs)
            AddUnitStubs(model, results);

        if (options.Existence)
            AddExistenceTests(model, results);

        // Safety net: two objects must never silently overwrite each other on disk. If any file name
        // repeats (e.g. a future object kind with a clashing identity), disambiguate with a counter rather
        // than lose a test. With Comments skipped this should not fire — but it guarantees it can't.
        DisambiguateFileNames(results);

        results.Sort((a, b) => string.CompareOrdinal(a.FileName, b.FileName));
        return results;
    }

    // ---- constraint enforcement (NOT NULL / UNIQUE / PK negatives; CHECK → inconclusive stub) -------------

    private static void AddConstraintTests(DatabaseModel model, TableDefinition table, List<ScaffoldResult> outp)
    {
        // NOT NULL: insert a baseline row with the target column forced to NULL → 23502.
        foreach (var col in table.Columns)
        {
            if (col.IsNullable || col.Default is not null || col.IsIdentity || col.IsSerial || col.GeneratedExpression is not null)
                continue;
            var overrides = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) { [col.Name] = "NULL" };
            outp.Add(BuildInsertTest(model, table, $"notnull.{col.Name}", "23502",
                $"NOT NULL: {table.QualifiedName}.{col.Name}", overrides, forceEmit: null, repeat: 1));
        }

        // PRIMARY KEY: insert the same key twice → 23505.
        if (table.PrimaryKey is { Columns.Count: > 0 } pk)
            outp.Add(BuildInsertTest(model, table, "pk", "23505",
                $"PRIMARY KEY: {table.QualifiedName} ({string.Join(", ", pk.Columns)})",
                overrides: null, forceEmit: pk.Columns, repeat: 2));

        // UNIQUE: one per declared unique constraint, insert the same key twice → 23505.
        foreach (var uq in table.Unique)
        {
            if (uq.Columns.Count == 0) continue;
            var detail = "unique." + string.Join("_", uq.Columns);
            outp.Add(BuildInsertTest(model, table, detail, "23505",
                $"UNIQUE: {table.QualifiedName} ({string.Join(", ", uq.Columns)})",
                overrides: null, forceEmit: uq.Columns, repeat: 2));
        }

        // CHECK: inverting an arbitrary predicate is undecidable — emit an authorable inconclusive stub.
        foreach (var ck in table.Checks)
        {
            var detail = "check." + Sanitize(ck.Name ?? ck.Expression);
            outp.Add(Inconclusive(table.Schema, table.Name, detail,
                $"CHECK {table.QualifiedName}: {ck.Expression}",
                $"author: insert a row violating CHECK ({ck.Expression}); expect 23514"));
        }
    }

    // ---- foreign-key referential integrity (orphan child insert → 23503) ---------------------------------

    private static void AddForeignKeyTests(DatabaseModel model, TableDefinition table, List<ScaffoldResult> outp)
    {
        foreach (var fk in table.ForeignKeys)
        {
            if (fk.Columns.Count == 0) continue;
            var detail = "fk." + Sanitize(fk.Name ?? string.Join("_", fk.Columns));

            if (model.FindTable(fk.ReferencedSchema, fk.ReferencedTable) is null)
            {
                outp.Add(Inconclusive(table.Schema, table.Name, detail,
                    $"FK {table.QualifiedName} ({string.Join(", ", fk.Columns)}) -> {fk.ReferencedSchema}.{fk.ReferencedTable}",
                    "referenced table is outside the project model — cannot assert 23503 deterministically"));
                continue;
            }

            // Force a deterministic orphan value into every FK column; baseline-fill the rest. A row that
            // satisfies the table's other NOT NULL / FK constraints but points at a missing parent → 23503.
            var overrides = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            bool ok = true;
            foreach (var cn in fk.Columns)
            {
                var col = table.FindColumn(cn);
                if (col is null || !BaselineRowSynthesizer.TryOrphanValue(col.DataType, out var ov)) { ok = false; break; }
                overrides[cn] = ov;
            }
            if (!ok)
            {
                outp.Add(Inconclusive(table.Schema, table.Name, detail,
                    $"FK orphan: {table.QualifiedName} ({string.Join(", ", fk.Columns)})",
                    "could not synthesise an orphan value for the FK column type"));
                continue;
            }

            outp.Add(BuildInsertTest(model, table, detail, "23503",
                $"FK orphan: {table.QualifiedName} ({string.Join(", ", fk.Columns)}) -> {fk.ReferencedSchema}.{fk.ReferencedTable}",
                overrides, forceEmit: fk.Columns, repeat: 1));
        }
    }

    // ---- CRUD round-trip (insert a baseline row, assert it landed) ---------------------------------------

    private static void AddCrudTest(DatabaseModel model, TableDefinition table, List<ScaffoldResult> outp)
    {
        if (!BaselineRowSynthesizer.TryBuildInsert(model, table, null, null, depth: 0,
                out var prelude, out var insert, out var reason))
        {
            outp.Add(Inconclusive(table.Schema, table.Name, "crud",
                $"CRUD round-trip: {table.QualifiedName}", reason));
            return;
        }

        var sb = new StringBuilder();
        sb.Append(PositiveHeader($"CRUD round-trip: {table.QualifiedName}"));
        foreach (var p in prelude) sb.Append(p).Append('\n');
        sb.Append(insert).Append('\n');
        sb.Append($"SELECT pgproj_assert_not_empty($$ SELECT 1 FROM {table.QualifiedName} LIMIT 1 $$);\n");
        outp.Add(new ScaffoldResult(FileName(table.Schema, table.Name, "crud"), sb.ToString(), "crud"));
    }

    // ---- view / materialized-view queryability ----------------------------------------------------------

    private static ScaffoldResult ViewTest(ViewDefinition view)
    {
        var kind = view.IsMaterialized ? "materialized view" : "view";
        var sb = new StringBuilder();
        sb.Append(PositiveHeader($"{kind} queryability: {view.Schema}.{view.Name}"));
        // LIMIT 0 forces full bind/type-resolution of the view body with zero rows; a broken view raises here.
        sb.Append($"SELECT pgproj_assert_rowcount($$ SELECT * FROM {view.Schema}.{view.Name} LIMIT 0 $$, 0);\n");
        return new ScaffoldResult(FileName(view.Schema, view.Name, "view"), sb.ToString(), kind);
    }

    // ---- function / procedure / trigger unit stubs (delegated to TestScaffolder) -------------------------

    private static void AddUnitStubs(DatabaseModel model, List<ScaffoldResult> outp)
    {
        foreach (var fn in model.Functions)
            TryStub(model, fn.Schema, fn.Name, outp);
        foreach (var trg in model.Objects.Where(o => o.Kind == ObjectKind.Trigger))
            TryStub(model, string.IsNullOrEmpty(trg.Schema) ? "public" : trg.Schema, trg.Name, outp);
    }

    private static void TryStub(DatabaseModel model, string schema, string name, List<ScaffoldResult> outp)
    {
        try
        {
            var stub = TestScaffolder.Scaffold(model, $"{schema}.{name}");
            // The generator cannot know an object's expected BEHAVIOUR, so an unedited unit stub must be
            // INCONCLUSIVE — never a failing assertion. We raise pgproj_inconclusive FIRST (so the suite is
            // clean by default and a trigger-returning function is never called directly), then keep the
            // TestScaffolder template below as authoring guidance (dead code after the raise — it parses but
            // never runs). The author writes the assertion and moves the file out of Generated/.
            var content = SentinelLine + "\n" +
                $"-- Generated {stub.Kind} unit-test stub — INCONCLUSIVE until you author the assertion below.\n" +
                $"SELECT pgproj_inconclusive({Lit($"author the {stub.Kind} test for {schema}.{name}: arrange, act, then assert")});\n\n" +
                stub.Content;
            outp.Add(new ScaffoldResult(FileName(schema, name, "unit"), content, stub.Kind));
        }
        catch (ScaffoldException)
        {
            // Name didn't resolve to a function/procedure/trigger (e.g. overload edge) — skip it silently.
        }
    }

    // ---- existence smoke tests for the remaining object kinds --------------------------------------------

    private static void AddExistenceTests(DatabaseModel model, List<ScaffoldResult> outp)
    {
        foreach (var seq in model.Sequences)
            outp.Add(ExistenceAssert(seq.Schema, seq.Name, "sequence",
                $"SELECT 1 FROM pg_sequences WHERE schemaname = {Lit(seq.Schema)} AND sequencename = {Lit(seq.Name)}"));

        foreach (var o in model.Objects)
        {
            // A Comment is metadata ON another object, not a standalone testable object — and the extractor
            // gives it no schema/name, so every comment would collide on one file name. Skip it (and any
            // other nameless object) outright.
            if (o.Kind == ObjectKind.Comment || string.IsNullOrEmpty(o.Name)) continue;

            var qn = string.IsNullOrEmpty(o.Schema) ? o.Name : $"{o.Schema}.{o.Name}";
            switch (o.Kind)
            {
                case ObjectKind.Type:
                case ObjectKind.Domain:
                    outp.Add(ExistenceAssertExpr(o.Schema, o.Name, o.Kind.ToString().ToLowerInvariant(),
                        $"to_regtype({Lit(qn)}) IS NOT NULL", $"type {qn} is missing"));
                    break;
                case ObjectKind.Table:
                    outp.Add(ExistenceAssertExpr(o.Schema, o.Name, "table",
                        $"to_regclass({Lit(qn)}) IS NOT NULL", $"relation {qn} is missing"));
                    break;
                case ObjectKind.Extension:
                    outp.Add(ExistenceAssert(o.Schema, o.Name, "extension",
                        $"SELECT 1 FROM pg_extension WHERE extname = {Lit(o.Name)}"));
                    break;
                case ObjectKind.Policy:
                    var tbl = string.IsNullOrEmpty(o.OnObject) ? "%" : BareTable(o.OnObject!);
                    outp.Add(ExistenceAssert(o.Schema, o.Name, "policy",
                        $"SELECT 1 FROM pg_policies WHERE policyname = {Lit(o.Name)} AND tablename LIKE {Lit(tbl)}"));
                    break;
                case ObjectKind.Rule:
                    outp.Add(ExistenceAssert(o.Schema, o.Name, "rule",
                        $"SELECT 1 FROM pg_rules WHERE rulename = {Lit(o.Name)}"));
                    break;
                case ObjectKind.Collation:
                    outp.Add(ExistenceAssert(o.Schema, o.Name, "collation",
                        $"SELECT 1 FROM pg_collation WHERE collname = {Lit(o.Name)}"));
                    break;
                case ObjectKind.EventTrigger:
                    outp.Add(ExistenceAssert(o.Schema, o.Name, "event_trigger",
                        $"SELECT 1 FROM pg_event_trigger WHERE evtname = {Lit(o.Name)}"));
                    break;
                case ObjectKind.Statistics:
                    outp.Add(ExistenceAssert(o.Schema, o.Name, "statistics",
                        $"SELECT 1 FROM pg_statistic_ext WHERE stxname = {Lit(o.Name)}"));
                    break;
                case ObjectKind.Publication:
                    outp.Add(ExistenceAssert(o.Schema, o.Name, "publication",
                        $"SELECT 1 FROM pg_publication WHERE pubname = {Lit(o.Name)}"));
                    break;
                case ObjectKind.Trigger:
                    break; // covered by the unit stub
                default:
                    outp.Add(Inconclusive(o.Schema, o.Name, "exists",
                        $"existence: {o.Kind} {qn}",
                        $"existence smoke test not auto-generated for {o.Kind} (no safe catalog predicate)"));
                    break;
            }
        }
    }

    // ---- shared builders --------------------------------------------------------------------------------

    /// <summary>Build a negative insert test: header + optional FK preludes + the insert repeated <paramref name="repeat"/> times.</summary>
    private static ScaffoldResult BuildInsertTest(
        DatabaseModel model, TableDefinition table, string detail, string expectedSqlState,
        string description, IReadOnlyDictionary<string, string>? overrides, IReadOnlyList<string>? forceEmit, int repeat)
    {
        var force = forceEmit is null ? null : new HashSet<string>(forceEmit, StringComparer.OrdinalIgnoreCase);
        if (!BaselineRowSynthesizer.TryBuildInsert(model, table, overrides, force, depth: 0,
                out var prelude, out var insert, out var reason))
            return Inconclusive(table.Schema, table.Name, detail, description, reason);

        var sb = new StringBuilder();
        sb.Append(NegativeHeader(expectedSqlState, description));
        foreach (var p in prelude) sb.Append(p).Append('\n');
        for (int i = 0; i < repeat; i++) sb.Append(insert).Append('\n');
        return new ScaffoldResult(FileName(table.Schema, table.Name, detail), sb.ToString(), "constraint");
    }

    private static ScaffoldResult ExistenceAssert(string schema, string name, string detail, string query) =>
        new(FileName(schema, name, "exists"),
            PositiveHeader($"existence: {detail} {(string.IsNullOrEmpty(schema) ? name : schema + "." + name)}") +
            $"SELECT pgproj_assert_not_empty($$ {query} $$);\n", "exists");

    private static ScaffoldResult ExistenceAssertExpr(string schema, string name, string detail, string boolExpr, string msg) =>
        new(FileName(schema, name, "exists"),
            PositiveHeader($"existence: {detail} {(string.IsNullOrEmpty(schema) ? name : schema + "." + name)}") +
            $"SELECT pgproj_assert({boolExpr}, {Lit(msg)});\n", "exists");

    private static ScaffoldResult Inconclusive(string schema, string name, string detail, string description, string reason) =>
        new(FileName(schema, name, detail),
            PositiveHeader(description) + $"SELECT pgproj_inconclusive({Lit(reason)});\n", "inconclusive");

    private static string NegativeHeader(string expectedSqlState, string description) =>
        // @expect-sqlstate MUST be first: PgUnitRunner.ParseExpectedSqlState stops at the first non-comment line.
        $"-- @expect-sqlstate: {expectedSqlState}\n{SentinelLine}\n-- {description}\n";

    private static string PositiveHeader(string description) =>
        $"{SentinelLine}\n-- {description}\n";

    /// <summary>The generated file name: <c>_gen.&lt;schema&gt;.&lt;object&gt;.&lt;detail&gt;.test.sql</c> (build-skipped, test-discovered).</summary>
    private static string FileName(string schema, string name, string detail) =>
        $"_gen.{Sanitize(schema)}.{Sanitize(name)}.{detail}.test.sql";

    /// <summary>Reduce a name fragment to a safe file-name token (identifiers can contain spaces/quotes).</summary>
    private static string Sanitize(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var ch in s)
            sb.Append(char.IsLetterOrDigit(ch) || ch is '_' or '-' ? ch : '_');
        return sb.Length == 0 ? "_" : sb.ToString();
    }

    /// <summary>Rename any duplicate file names in place (append <c>.2</c>, <c>.3</c>, …) so no test is lost on write.</summary>
    private static void DisambiguateFileNames(List<ScaffoldResult> results)
    {
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        for (var i = 0; i < results.Count; i++)
        {
            var name = results[i].FileName;
            if (seen.Add(name)) continue;
            var stem = name.EndsWith(".test.sql", StringComparison.Ordinal) ? name[..^".test.sql".Length] : name;
            for (var n = 2; ; n++)
            {
                var candidate = $"{stem}.{n}.test.sql";
                if (seen.Add(candidate)) { results[i] = results[i] with { FileName = candidate }; break; }
            }
        }
    }

    /// <summary>The bare table name from a possibly schema-qualified <c>schema.table</c>.</summary>
    private static string BareTable(string qualified)
    {
        var dot = qualified.LastIndexOf('.');
        return dot >= 0 ? qualified[(dot + 1)..] : qualified;
    }

    /// <summary>SQL single-quoted string literal.</summary>
    private static string Lit(string s) => "'" + s.Replace("'", "''") + "'";
}
