using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using PgProj.Core.Model;

namespace PgProj.Core.Testing;

/// <summary>The outcome of scaffolding a test stub: the file name to write, its content, and the object kind.</summary>
public sealed record ScaffoldResult(string FileName, string Content, string Kind);

/// <summary>
/// Generates a pre/test/post unit-test STUB (#139 — the SSDT "create unit test for this object" analogue) for
/// a chosen function/procedure/trigger from the parsed semantic model. The stub is named with a leading
/// underscore (<c>_schema.name.test.sql</c>) so the build globber skips it (<see
/// cref="Project.DatabaseProject.ResolveSqlFiles"/> drops leading-underscore files) while the
/// <c>*.test.sql</c> suffix keeps it discoverable by <c>pgproj test</c>. The body is a starting point — an
/// arrange section, an act+assert section wired to the <see cref="PgUnitRunner"/> prelude helpers, and a note
/// on the negative-test directive — that the author fills in.
/// </summary>
public static class TestScaffolder
{
    /// <summary>The conventional stub file name for an object: <c>_schema.name.test.sql</c> (build-skipped, test-discovered).</summary>
    public static string FileNameFor(string schema, string name) => $"_{schema}.{name}.test.sql";

    /// <summary>
    /// Build a test stub for the object named <paramref name="qualified"/> (<c>schema.name</c>) in
    /// <paramref name="model"/>. Resolves a function/procedure first, then a trigger. Throws
    /// <see cref="ScaffoldException"/> when the name is malformed or no such object exists.
    /// </summary>
    public static ScaffoldResult Scaffold(DatabaseModel model, string qualified)
    {
        var (schema, name) = Split(qualified);

        var fn = model.Functions.FirstOrDefault(f =>
            DatabaseModel.NameEquals(f.Schema, schema) && DatabaseModel.NameEquals(f.Name, name));
        if (fn is not null)
        {
            var isProc = IsProcedure(fn);
            return new ScaffoldResult(FileNameFor(schema, name),
                isProc ? ProcedureStub(fn) : FunctionStub(fn), isProc ? "procedure" : "function");
        }

        var trg = model.Objects.FirstOrDefault(o =>
            o.Kind == ObjectKind.Trigger && DatabaseModel.NameEquals(o.Name, name) &&
            (string.IsNullOrEmpty(o.Schema) || DatabaseModel.NameEquals(o.Schema, schema)));
        if (trg is not null)
            return new ScaffoldResult(FileNameFor(schema, name), TriggerStub(trg), "trigger");

        throw new ScaffoldException(
            $"No function/procedure or trigger named '{qualified}' was found in the built project model.");
    }

    private static readonly string Header = string.Join('\n',
        "-- Each test runs inside its own BEGIN ... ROLLBACK (single-transaction scope): the database is",
        "-- left untouched, so the rows you arrange here are disposable.",
        "--",
        "-- Prelude assertion helpers available in every test:",
        "--   pgproj_assert(cond, msg)                 pgproj_assert_rowcount(query, n)",
        "--   pgproj_assert_scalar(query, expected)    pgproj_assert_empty(query)",
        "--   pgproj_assert_not_empty(query)           pgproj_assert_column_type(rel, col, type)",
        "--   pgproj_assert_checksum(query, expected)  pgproj_inconclusive(msg)",
        "--",
        "-- For a negative / expected-exception test, add a leading directive on the first line:",
        "--   -- @expect-sqlstate: 23505");

    private static string FunctionStub(FunctionDefinition fn)
    {
        var sb = new StringBuilder();
        sb.Append("-- Unit test stub for function ").Append(fn.Schema).Append('.').Append(fn.Name)
          .Append('(').Append(fn.ArgTypes).Append(")\n");
        sb.Append("-- Generated by `pgproj test scaffold`. Edit the sections below, then run `pgproj test`.\n");
        sb.Append(Header).Append("\n\n");
        sb.Append("-- 1. ARRANGE — set up the rows/fixtures the function needs.\n");
        sb.Append("-- INSERT INTO ").Append(fn.Schema).Append(".some_table (...) VALUES (...);\n\n");
        sb.Append("-- 2. ACT + ASSERT — invoke the function and assert its result.\n");
        sb.Append("SELECT pgproj_assert_scalar(\n");
        sb.Append("    $$ SELECT ").Append(fn.Schema).Append('.').Append(fn.Name)
          .Append('(').Append(ArgPlaceholders(fn.ArgTypes)).Append(") $$,\n");
        sb.Append("    '<expected-value>');\n\n");
        sb.Append("-- 3. (post) cleanup is automatic — the surrounding transaction rolls back.\n");
        return sb.ToString();
    }

    private static string ProcedureStub(FunctionDefinition fn)
    {
        var sb = new StringBuilder();
        sb.Append("-- Unit test stub for procedure ").Append(fn.Schema).Append('.').Append(fn.Name)
          .Append('(').Append(fn.ArgTypes).Append(")\n");
        sb.Append("-- Generated by `pgproj test scaffold`. Edit the sections below, then run `pgproj test`.\n");
        sb.Append(Header).Append("\n\n");
        sb.Append("-- 1. ARRANGE — set up the rows/fixtures the procedure needs.\n");
        sb.Append("-- INSERT INTO ").Append(fn.Schema).Append(".some_table (...) VALUES (...);\n\n");
        sb.Append("-- 2. ACT — invoke the procedure.\n");
        sb.Append("CALL ").Append(fn.Schema).Append('.').Append(fn.Name)
          .Append('(').Append(ArgPlaceholders(fn.ArgTypes)).Append(");\n\n");
        sb.Append("-- 3. ASSERT — check the side effects the procedure produced.\n");
        sb.Append("SELECT pgproj_assert_rowcount($$ SELECT 1 WHERE false $$, 0);  -- replace with a real check\n");
        return sb.ToString();
    }

    private static string TriggerStub(RawObjectDefinition trg)
    {
        var on = string.IsNullOrEmpty(trg.OnObject) ? "the_table" : trg.OnObject!;
        var sb = new StringBuilder();
        sb.Append("-- Unit test stub for trigger ").Append(trg.Name).Append(" on ").Append(on).Append('\n');
        sb.Append("-- Generated by `pgproj test scaffold`. Edit the sections below, then run `pgproj test`.\n");
        sb.Append(Header).Append("\n\n");
        sb.Append("-- 1. ARRANGE + ACT — perform the DML on ").Append(on).Append(" that fires the trigger:\n");
        sb.Append("-- INSERT INTO ").Append(on).Append(" (...) VALUES (...);\n\n");
        sb.Append("-- 2. ASSERT — verify the trigger's effect (audit row, computed column, rejection, ...).\n");
        sb.Append("SELECT pgproj_inconclusive('fill in the trigger test: perform the DML, then assert its effect');\n");
        return sb.ToString();
    }

    /// <summary>Render <c>NULL::type</c> placeholders for each argument type (empty when the function takes none).</summary>
    private static string ArgPlaceholders(string argTypes)
    {
        if (string.IsNullOrWhiteSpace(argTypes)) return "";
        return string.Join(", ", argTypes.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(t => $"NULL::{t}"));
    }

    private static bool IsProcedure(FunctionDefinition fn) =>
        Regex.IsMatch(fn.Body, @"\bCREATE\s+(OR\s+REPLACE\s+)?PROCEDURE\b", RegexOptions.IgnoreCase);

    private static (string Schema, string Name) Split(string qualified)
    {
        var dot = qualified?.IndexOf('.') ?? -1;
        if (qualified is null || dot <= 0 || dot == qualified.Length - 1)
            throw new ScaffoldException($"Expected a schema-qualified name 'schema.name' (got '{qualified}').");
        return (qualified[..dot], qualified[(dot + 1)..]);
    }
}

/// <summary>Thrown when a scaffold request's name is malformed or its target object is not found.</summary>
public sealed class ScaffoldException : Exception
{
    public ScaffoldException(string message) : base(message) { }
}
