// <auto-generated> Generated from tests/corpus/*.jsonl by CorpusTestGenerator. Do not edit by hand. </auto-generated>
using Xunit;

namespace PgProj.Core.Tests.Corpus;

public class Corpus_CreateTextsearch
{
    [Fact]
    public void tsa0001() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.myconfig (PARSER = pg_catalog.default)", "ok");
    [Fact]
    public void tsa0002() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconfig2 (PARSER = pg_catalog.default)", "ok");
    [Fact]
    public void tsa0003() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.copyconfig (COPY = pg_catalog.english)", "ok");
    [Fact]
    public void tsa0004() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION copysimple (COPY = pg_catalog.simple)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0005() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfgdup (PARSER = pg_catalog.default);
CREATE TEXT SEARCH CONFIGURATION s.cfgdup (PARSER = pg_catalog.default)", "error");
    [Fact]
    public void tsa0006() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION (PARSER = pg_catalog.default)", "error");
    [Fact]
    public void tsa0007() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.badcfg (PARSER = pg_catalog.default, COPY = pg_catalog.simple)", "error");
    [Fact]
    public void tsa0008() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.emptycfg ()", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0009() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.badparser (PARSER = nonexistent_parser)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0010() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.badcopy (COPY = nonexistent_config)", "error");
    [Fact]
    public void tsa0011() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg1 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg1 ADD MAPPING FOR asciiword WITH pg_catalog.english_stem", "ok");
    [Fact]
    public void tsa0012() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg2 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg2 ADD MAPPING FOR asciiword, word WITH pg_catalog.english_stem", "ok");
    [Fact]
    public void tsa0013() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg3 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg3 ADD MAPPING FOR asciiword WITH pg_catalog.english_stem, pg_catalog.simple", "ok");
    [Fact]
    public void tsa0014() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg4 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg4 ADD MAPPING FOR asciiword WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.cfg4 ALTER MAPPING FOR asciiword WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0015() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg5 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg5 ADD MAPPING FOR asciiword, word, numword WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.cfg5 ALTER MAPPING FOR asciiword, word WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0016() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg6 (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION s.cfg6 ALTER MAPPING REPLACE pg_catalog.english_stem WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0017() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg7 (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION s.cfg7 ALTER MAPPING FOR asciiword REPLACE pg_catalog.english_stem WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0018() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg8 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg8 ADD MAPPING FOR asciiword WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.cfg8 DROP MAPPING FOR asciiword", "ok");
    [Fact]
    public void tsa0019() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg9 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg9 DROP MAPPING IF EXISTS FOR asciiword", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0020() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg10 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg10 ADD MAPPING FOR asciiword WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.cfg10 DROP MAPPING FOR asciiword, word", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0021() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg11 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg11 DROP MAPPING FOR asciiword", "error");
    [Fact]
    public void tsa0022() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.rencfg (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.rencfg RENAME TO s.rencfg2", "error");
    [Fact]
    public void tsa0023() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.rencfg3 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.rencfg3 RENAME TO rencfg4", "ok");
    [Fact]
    public void tsa0024() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.schemacfg (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.schemacfg SET SCHEMA public", "ok");
    [Fact]
    public void tsa0025() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.ownercfg (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.ownercfg OWNER TO CURRENT_USER", "ok");
    [Fact]
    public void tsa0026() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.ownercfg2 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.ownercfg2 OWNER TO CURRENT_ROLE", "ok");
    [Fact]
    public void tsa0027() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.ownercfg3 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.ownercfg3 OWNER TO SESSION_USER", "ok");
    [Fact]
    public void tsa0028() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.dropcfg (PARSER = pg_catalog.default);
DROP TEXT SEARCH CONFIGURATION s.dropcfg", "ok");
    [Fact]
    public void tsa0029() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.dropcfg2 (PARSER = pg_catalog.default);
DROP TEXT SEARCH CONFIGURATION s.dropcfg2 RESTRICT", "ok");
    [Fact]
    public void tsa0030() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.dropcfg3 (PARSER = pg_catalog.default);
DROP TEXT SEARCH CONFIGURATION s.dropcfg3 CASCADE", "ok");
    [Fact]
    public void tsa0031() => CorpusAssert.Parses(@"DROP TEXT SEARCH CONFIGURATION IF EXISTS s.nonexistent_cfg", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0032() => CorpusAssert.Parses(@"DROP TEXT SEARCH CONFIGURATION s.nonexistent_cfg2", "error");
    [Fact]
    public void tsa0033() => CorpusAssert.Parses(@"DROP TEXT SEARCH CONFIGURATION IF EXISTS s.nonexistent_cfg3 CASCADE", "ok");
    [Fact]
    public void tsa0034() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.mydict (TEMPLATE = pg_catalog.simple)", "ok");
    [Fact]
    public void tsa0035() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict2 (TEMPLATE = pg_catalog.simple)", "ok");
    [Fact]
    public void tsa0036() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.stopdict (TEMPLATE = pg_catalog.simple, STOPWORDS = english)", "ok");
    [Fact]
    public void tsa0037() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.snowdict (TEMPLATE = pg_catalog.snowball, LANGUAGE = english)", "ok");
    [Fact]
    public void tsa0038() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.snowdict2 (TEMPLATE = pg_catalog.snowball, LANGUAGE = english, STOPWORDS = english)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0039() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.syndict (TEMPLATE = pg_catalog.synonym, SYNONYMS = pg_catalog.pg_dict)", "error");
    [Fact]
    public void tsa0040() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.notempl ()", "error");
    [Fact]
    public void tsa0041() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY (TEMPLATE = pg_catalog.simple)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0042() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.badtempl (TEMPLATE = nonexistent_template)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0043() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dictdup (TEMPLATE = pg_catalog.simple);
CREATE TEXT SEARCH DICTIONARY s.dictdup (TEMPLATE = pg_catalog.simple)", "error");
    [Fact]
    public void tsa0044() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dictren (TEMPLATE = pg_catalog.simple);
ALTER TEXT SEARCH DICTIONARY s.dictren RENAME TO dictren2", "ok");
    [Fact]
    public void tsa0045() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dictowner (TEMPLATE = pg_catalog.simple);
ALTER TEXT SEARCH DICTIONARY s.dictowner OWNER TO CURRENT_USER", "ok");
    [Fact]
    public void tsa0046() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dictschema (TEMPLATE = pg_catalog.simple);
ALTER TEXT SEARCH DICTIONARY s.dictschema SET SCHEMA public", "ok");
    [Fact]
    public void tsa0047() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dictparams (TEMPLATE = pg_catalog.simple);
ALTER TEXT SEARCH DICTIONARY s.dictparams (STOPWORDS = english)", "ok");
    [Fact]
    public void tsa0048() => CorpusAssert.Parses(@"DROP TEXT SEARCH DICTIONARY s.dropdict (TEMPLATE = pg_catalog.simple)", "error");
    [Fact]
    public void tsa0049() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dropd1 (TEMPLATE = pg_catalog.simple);
DROP TEXT SEARCH DICTIONARY s.dropd1", "ok");
    [Fact]
    public void tsa0050() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dropd2 (TEMPLATE = pg_catalog.simple);
DROP TEXT SEARCH DICTIONARY s.dropd2 CASCADE", "ok");
    [Fact]
    public void tsa0051() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dropd3 (TEMPLATE = pg_catalog.simple);
DROP TEXT SEARCH DICTIONARY s.dropd3 RESTRICT", "ok");
    [Fact]
    public void tsa0052() => CorpusAssert.Parses(@"DROP TEXT SEARCH DICTIONARY IF EXISTS s.nosuchdict", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0053() => CorpusAssert.Parses(@"DROP TEXT SEARCH DICTIONARY s.nosuchdict2", "error");
    [Fact]
    public void tsa0054() => CorpusAssert.Parses(@"DROP TEXT SEARCH DICTIONARY IF EXISTS s.nosuchdict3 CASCADE", "ok");
    [Fact]
    public void tsa0055() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.myparser (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype, HEADLINE = prsd_headline)", "ok");
    [Fact]
    public void tsa0056() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.myparser2 (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "ok");
    [Fact]
    public void tsa0057() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.myparser3 (GETTOKEN = prsd_nexttoken, START = prsd_start, LEXTYPES = prsd_lextype, END = prsd_end)", "ok");
    [Fact]
    public void tsa0058() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.myparser4 (HEADLINE = prsd_headline, END = prsd_end, LEXTYPES = prsd_lextype, GETTOKEN = prsd_nexttoken, START = prsd_start)", "ok");
    [Fact]
    public void tsa0059() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.badparser1 (GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "error");
    [Fact]
    public void tsa0060() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.badparser2 (START = prsd_start, END = prsd_end, LEXTYPES = prsd_lextype)", "error");
    [Fact]
    public void tsa0061() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.badparser3 (START = prsd_start, GETTOKEN = prsd_nexttoken, LEXTYPES = prsd_lextype)", "error");
    [Fact]
    public void tsa0062() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.badparser4 (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end)", "error");
    [Fact]
    public void tsa0063() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0064() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.parserdup (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype);
CREATE TEXT SEARCH PARSER s.parserdup (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0065() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.badparser5 (START = nonexistent_fn, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "error");
    [Fact]
    public void tsa0066() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.renparser (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype);
ALTER TEXT SEARCH PARSER s.renparser RENAME TO renparser2", "ok");
    [Fact]
    public void tsa0067() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.schparser (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype);
ALTER TEXT SEARCH PARSER s.schparser SET SCHEMA public", "ok");
    [Fact]
    public void tsa0068() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.dropparser1 (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype);
DROP TEXT SEARCH PARSER s.dropparser1", "ok");
    [Fact]
    public void tsa0069() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.dropparser2 (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype);
DROP TEXT SEARCH PARSER s.dropparser2 CASCADE", "ok");
    [Fact]
    public void tsa0070() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.dropparser3 (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype);
DROP TEXT SEARCH PARSER s.dropparser3 RESTRICT", "ok");
    [Fact]
    public void tsa0071() => CorpusAssert.Parses(@"DROP TEXT SEARCH PARSER IF EXISTS s.nosuchparser", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0072() => CorpusAssert.Parses(@"DROP TEXT SEARCH PARSER s.nosuchparser2", "error");
    [Fact]
    public void tsa0073() => CorpusAssert.Parses(@"DROP TEXT SEARCH PARSER IF EXISTS s.nosuchparser3 CASCADE", "ok");
    [Fact]
    public void tsa0074() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.mytempl (LEXIZE = dsimple_lexize)", "ok");
    [Fact]
    public void tsa0075() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.mytempl2 (INIT = dsimple_init, LEXIZE = dsimple_lexize)", "ok");
    [Fact]
    public void tsa0076() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.mytempl3 (LEXIZE = dsimple_lexize, INIT = dsimple_init)", "ok");
    [Fact]
    public void tsa0077() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE mytempl4 (LEXIZE = dsimple_lexize)", "ok");
    [Fact]
    public void tsa0078() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.badtempl1 (INIT = dsimple_init)", "error");
    [Fact]
    public void tsa0079() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.badtempl2 ()", "error");
    [Fact]
    public void tsa0080() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE (LEXIZE = dsimple_lexize)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0081() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.templdup (LEXIZE = dsimple_lexize);
CREATE TEXT SEARCH TEMPLATE s.templdup (LEXIZE = dsimple_lexize)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0082() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.badtempl3 (LEXIZE = nonexistent_lexize_fn)", "error");
    [Fact]
    public void tsa0083() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.rentempl (LEXIZE = dsimple_lexize);
ALTER TEXT SEARCH TEMPLATE s.rentempl RENAME TO rentempl2", "ok");
    [Fact]
    public void tsa0084() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.schematempl (LEXIZE = dsimple_lexize);
ALTER TEXT SEARCH TEMPLATE s.schematempl SET SCHEMA public", "ok");
    [Fact]
    public void tsa0085() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.droptempl1 (LEXIZE = dsimple_lexize);
DROP TEXT SEARCH TEMPLATE s.droptempl1", "ok");
    [Fact]
    public void tsa0086() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.droptempl2 (LEXIZE = dsimple_lexize);
DROP TEXT SEARCH TEMPLATE s.droptempl2 CASCADE", "ok");
    [Fact]
    public void tsa0087() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.droptempl3 (LEXIZE = dsimple_lexize);
DROP TEXT SEARCH TEMPLATE s.droptempl3 RESTRICT", "ok");
    [Fact]
    public void tsa0088() => CorpusAssert.Parses(@"DROP TEXT SEARCH TEMPLATE IF EXISTS s.nosuchtempl", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0089() => CorpusAssert.Parses(@"DROP TEXT SEARCH TEMPLATE s.nosuchtempl2", "error");
    [Fact]
    public void tsa0090() => CorpusAssert.Parses(@"DROP TEXT SEARCH TEMPLATE IF EXISTS s.nosuchtempl3 CASCADE", "ok");
    [Fact]
    public void tsa0091() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.fullcfg (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.fullcfg ADD MAPPING FOR asciiword WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.fullcfg ADD MAPPING FOR word WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.fullcfg ADD MAPPING FOR numword WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0092() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_email (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_email ADD MAPPING FOR email WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0093() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_url (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_url ADD MAPPING FOR url WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0094() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_host (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_host ADD MAPPING FOR host WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0095() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_int (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_int ADD MAPPING FOR int WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0096() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_float (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_float ADD MAPPING FOR float WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0097() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_sfloat (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_sfloat ADD MAPPING FOR sfloat WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0098() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_uint (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_uint ADD MAPPING FOR uint WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0099() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_ver (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_ver ADD MAPPING FOR version WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0100() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_tag (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_tag ADD MAPPING FOR tag WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0101() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_entity (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_entity ADD MAPPING FOR entity WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0102() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_file (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_file ADD MAPPING FOR file WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0103() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_proto (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_proto ADD MAPPING FOR protocol WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0104() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_urlpath (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_urlpath ADD MAPPING FOR url_path WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0105() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_hword (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_hword ADD MAPPING FOR hword WITH pg_catalog.english_stem", "ok");
    [Fact]
    public void tsa0106() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_ahword (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_ahword ADD MAPPING FOR asciihword WITH pg_catalog.english_stem", "ok");
    [Fact]
    public void tsa0107() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_nhword (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_nhword ADD MAPPING FOR numhword WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0108() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_hwpart (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_hwpart ADD MAPPING FOR hword_part WITH pg_catalog.english_stem", "ok");
    [Fact]
    public void tsa0109() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_ahwpart (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_ahwpart ADD MAPPING FOR hword_asciipart WITH pg_catalog.english_stem", "ok");
    [Fact]
    public void tsa0110() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_nhwpart (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_nhwpart ADD MAPPING FOR hword_numpart WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0111() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_blank (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_blank ADD MAPPING FOR blank WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0112() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.altcfg1 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.altcfg1 ADD MAPPING FOR asciiword, word, numword, email WITH pg_catalog.simple", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0113() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.altcfg2 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.altcfg2 ADD MAPPING FOR asciiword WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.altcfg2 ADD MAPPING FOR asciiword WITH pg_catalog.simple", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0114() => CorpusAssert.Parses(@"ALTER TEXT SEARCH CONFIGURATION pg_catalog.english ADD MAPPING FOR asciiword WITH pg_catalog.simple", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0115() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_nomap (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_nomap ADD MAPPING FOR badtokentype WITH pg_catalog.simple", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0116() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_baddict (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_baddict ADD MAPPING FOR asciiword WITH nonexistent_dict", "error");
    [Fact]
    public void tsa0117() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_syntax1 (PARSER pg_catalog.default)", "error");
    [Fact]
    public void tsa0118() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_syntax2 PARSER = pg_catalog.default", "error");
    [Fact]
    public void tsa0119() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_syntax3 (COPY pg_catalog.simple)", "error");
    [Fact]
    public void tsa0120() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dict_syntax1 (TEMPLATE pg_catalog.simple)", "error");
    [Fact]
    public void tsa0121() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dict_syntax2 TEMPLATE = pg_catalog.simple", "error");
    [Fact]
    public void tsa0122() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.parser_syntax1 (START = prsd_start GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "error");
    [Fact]
    public void tsa0123() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.templ_syntax1 (LEXIZE dsimple_lexize)", "error");
    [Fact]
    public void tsa0124() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.templ_syntax2 LEXIZE = dsimple_lexize", "error");
    [Fact]
    public void tsa0125() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION ""My Config"" (PARSER = pg_catalog.default)", "ok");
    [Fact]
    public void tsa0126() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.""MyConfig2"" (COPY = pg_catalog.simple)", "ok");
    [Fact]
    public void tsa0127() => CorpusAssert.Parses(@"CREATE text search configuration s.kwcfg (parser = pg_catalog.default)", "ok");
    [Fact]
    public void tsa0128() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION S.CfgUpper (PARSER = pg_catalog.default)", "ok");
    [Fact]
    public void tsa0129() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.""MyDict"" (TEMPLATE = pg_catalog.simple)", "ok");
    [Fact]
    public void tsa0130() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dictcomment (TEMPLATE = pg_catalog.simple);
COMMENT ON TEXT SEARCH DICTIONARY s.dictcomment IS 'test dictionary'", "ok");
    [Fact]
    public void tsa0131() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfgcomment (PARSER = pg_catalog.default);
COMMENT ON TEXT SEARCH CONFIGURATION s.cfgcomment IS 'test config'", "ok");
    [Fact]
    public void tsa0132() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_dropmapping (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_dropmapping ADD MAPPING FOR asciiword, word WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.cfg_dropmapping DROP MAPPING FOR asciiword, word", "ok");
    [Fact]
    public void tsa0133() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_altmap (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_altmap ADD MAPPING FOR asciiword WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.cfg_altmap ALTER MAPPING FOR asciiword WITH pg_catalog.simple, pg_catalog.english_stem", "ok");
    [Fact]
    public void tsa0134() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_replace (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION s.cfg_replace ALTER MAPPING REPLACE pg_catalog.english_stem WITH pg_catalog.simple;
ALTER TEXT SEARCH CONFIGURATION s.cfg_replace ALTER MAPPING REPLACE pg_catalog.simple WITH pg_catalog.english_stem", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0135() => CorpusAssert.Parses(@"ALTER TEXT SEARCH CONFIGURATION nonexistent_cfg ADD MAPPING FOR asciiword WITH pg_catalog.simple", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0136() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_miss_with (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_miss_with ADD MAPPING FOR asciiword pg_catalog.simple", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0137() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_miss_for (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_miss_for ADD MAPPING asciiword WITH pg_catalog.simple", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0138() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_miss_for2 (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_miss_for2 DROP MAPPING asciiword", "error");
    [Fact]
    public void tsa0139() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.snowdict3 (TEMPLATE = pg_catalog.snowball, LANGUAGE = danish)", "ok");
    [Fact]
    public void tsa0140() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.snowdict4 (TEMPLATE = pg_catalog.snowball, LANGUAGE = french)", "ok");
    [Fact]
    public void tsa0141() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.snowdict5 (TEMPLATE = pg_catalog.snowball, LANGUAGE = spanish)", "ok");
    [Fact]
    public void tsa0142() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.snowdict6 (TEMPLATE = pg_catalog.snowball, LANGUAGE = german)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0143() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.unaccdict (TEMPLATE = pg_catalog.simple, UNACCENT = false)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0144() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_copy_english (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION s.cfg_copy_english ADD MAPPING FOR asciiword WITH pg_catalog.english_stem", "error");
    [Fact]
    public void tsa0145() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_two_parsers (PARSER = pg_catalog.default, PARSER = pg_catalog.default)", "ok");
    [Fact]
    public void tsa0146() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_two_copies (COPY = pg_catalog.simple, COPY = pg_catalog.english)", "ok");
    [Fact]
    public void tsa0147() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.parsersch (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype);
CREATE TEXT SEARCH CONFIGURATION s.cfg_custparser (PARSER = s.parsersch)", "ok");
    [Fact]
    public void tsa0148() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.mytempl5 (LEXIZE = dsimple_lexize);
CREATE TEXT SEARCH DICTIONARY s.dictfromtempl (TEMPLATE = s.mytempl5)", "ok");
    [Fact]
    public void tsa0149() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.mytempl6 (LEXIZE = dsimple_lexize);
CREATE TEXT SEARCH DICTIONARY s.dictfromtempl2 (TEMPLATE = s.mytempl6);
CREATE TEXT SEARCH CONFIGURATION s.cfg_from_templ (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_from_templ ADD MAPPING FOR asciiword WITH s.dictfromtempl2", "ok");
    [Fact]
    public void tsa0150() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dictaltparams (TEMPLATE = pg_catalog.simple);
ALTER TEXT SEARCH DICTIONARY s.dictaltparams (STOPWORDS = english, ACCEPT = false)", "ok");
    [Fact]
    public void tsa0151() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dictaltparams2 (TEMPLATE = pg_catalog.snowball, LANGUAGE = english);
ALTER TEXT SEARCH DICTIONARY s.dictaltparams2 (LANGUAGE = french)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0152() => CorpusAssert.Parses(@"ALTER TEXT SEARCH DICTIONARY nonexistent_dict (STOPWORDS = english)", "error");
    [Fact]
    public void tsa0153() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_ifnotex (PARSER = pg_catalog.default);
CREATE TEXT SEARCH CONFIGURATION IF NOT EXISTS s.cfg_ifnotex (PARSER = pg_catalog.default)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0154() => CorpusAssert.Parses(@"CREATE OR REPLACE TEXT SEARCH CONFIGURATION s.cfg_orrepl (PARSER = pg_catalog.default)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0155() => CorpusAssert.Parses(@"CREATE OR REPLACE TEXT SEARCH DICTIONARY s.dict_orrepl (TEMPLATE = pg_catalog.simple)", "error");
    [Fact]
    public void tsa0156() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY IF NOT EXISTS s.dict_ifnotex (TEMPLATE = pg_catalog.simple)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0157() => CorpusAssert.Parses(@"CREATE OR REPLACE TEXT SEARCH PARSER s.parser_orrepl (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsa0158() => CorpusAssert.Parses(@"CREATE OR REPLACE TEXT SEARCH TEMPLATE s.templ_orrepl (LEXIZE = dsimple_lexize)", "error");
    [Fact]
    public void tsa0159() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_qparser (PARSER = ""pg_catalog"".""default"")", "ok");
    [Fact]
    public void tsa0160() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_qcopy (COPY = ""pg_catalog"".""simple"")", "ok");
    [Fact]
    public void tsa0161() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dict_qtempl (TEMPLATE = ""pg_catalog"".""simple"")", "ok");
    [Fact]
    public void tsa0162() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_multi_dicts (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_multi_dicts ADD MAPPING FOR asciiword WITH pg_catalog.english_stem, pg_catalog.simple, pg_catalog.english_stem", "ok");
    [Fact]
    public void tsa0163() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_dropthenreadd (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_dropthenreadd ADD MAPPING FOR asciiword WITH pg_catalog.english_stem;
ALTER TEXT SEARCH CONFIGURATION s.cfg_dropthenreadd DROP MAPPING FOR asciiword;
ALTER TEXT SEARCH CONFIGURATION s.cfg_dropthenreadd ADD MAPPING FOR asciiword WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0164() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_replacenodict (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION s.cfg_replacenodict ALTER MAPPING REPLACE pg_catalog.simple WITH pg_catalog.english_stem", "ok");
    [Fact]
    public void tsa0165() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.p_headline (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype, HEADLINE = prsd_headline);
CREATE TEXT SEARCH CONFIGURATION s.cfg_p_headline (PARSER = s.p_headline)", "ok");
    [Fact]
    public void tsa0166() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_owner_session (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_owner_session OWNER TO SESSION_USER", "ok");
    [Fact]
    public void tsa0167() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.dict_owner_crole (TEMPLATE = pg_catalog.simple);
ALTER TEXT SEARCH DICTIONARY s.dict_owner_crole OWNER TO CURRENT_ROLE", "ok");
    [Fact]
    public void tsa0168() => CorpusAssert.Parses(@"DROP TEXT SEARCH CONFIGURATION IF EXISTS s.nosuchcfg CASCADE", "ok");
    [Fact]
    public void tsa0169() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.cfg_delim (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION s.cfg_delim ADD MAPPING FOR asciiword, word, numword, email, url, host, int, float WITH pg_catalog.simple", "ok");
    [Fact]
    public void tsa0170() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.mytempl7 (LEXIZE = dsimple_lexize);
CREATE TEXT SEARCH DICTIONARY s.dchain1 (TEMPLATE = s.mytempl7);
CREATE TEXT SEARCH DICTIONARY s.dchain2 (TEMPLATE = pg_catalog.simple);
CREATE TEXT SEARCH PARSER s.pchain (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype);
CREATE TEXT SEARCH CONFIGURATION s.cfg_chain (PARSER = s.pchain);
ALTER TEXT SEARCH CONFIGURATION s.cfg_chain ADD MAPPING FOR asciiword WITH s.dchain1, s.dchain2", "ok");
    [Fact]
    public void tsb0001() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default)", "ok");
    [Fact]
    public void tsb0002() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (COPY = pg_catalog.english)", "ok");
    [Fact]
    public void tsb0003() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION s.myconf (PARSER = pg_catalog.default)", "ok");
    [Fact]
    public void tsb0004() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (COPY = pg_catalog.simple)", "ok");
    [Fact]
    public void tsb0005() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default, COPY = pg_catalog.english)", "error");
    [Fact]
    public void tsb0006() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf ()", "error");
    [Fact]
    public void tsb0007() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION (PARSER = pg_catalog.default)", "error");
    [Fact]
    public void tsb0008() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf PARSER = pg_catalog.default", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsb0009() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (COPY = nonexistent_config_xyz)", "error");
    [Fact]
    public void tsb0010() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
DROP TEXT SEARCH CONFIGURATION myconf", "ok");
    [Fact]
    public void tsb0011() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
DROP TEXT SEARCH CONFIGURATION IF EXISTS myconf", "ok");
    [Fact]
    public void tsb0012() => CorpusAssert.Parses(@"DROP TEXT SEARCH CONFIGURATION IF EXISTS no_such_config_xyz", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsb0013() => CorpusAssert.Parses(@"DROP TEXT SEARCH CONFIGURATION no_such_config_xyz", "error");
    [Fact]
    public void tsb0014() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
DROP TEXT SEARCH CONFIGURATION myconf CASCADE", "ok");
    [Fact]
    public void tsb0015() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
DROP TEXT SEARCH CONFIGURATION myconf RESTRICT", "ok");
    [Fact]
    public void tsb0016() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION myconf ADD MAPPING FOR word WITH simple", "ok");
    [Fact]
    public void tsb0017() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION myconf ADD MAPPING FOR word, numword WITH simple", "ok");
    [Fact]
    public void tsb0018() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION myconf ALTER MAPPING FOR word WITH simple", "ok");
    [Fact]
    public void tsb0019() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION myconf ALTER MAPPING REPLACE english_stem WITH simple", "ok");
    [Fact]
    public void tsb0020() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION myconf DROP MAPPING FOR word", "ok");
    [Fact]
    public void tsb0021() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION myconf DROP MAPPING IF EXISTS FOR word", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsb0022() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (COPY = pg_catalog.english);
ALTER TEXT SEARCH CONFIGURATION myconf DROP MAPPING IF EXISTS FOR no_such_token_type_xyz", "error");
    [Fact]
    public void tsb0023() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION myconf ADD MAPPING FOR word WITH simple, english_stem", "ok");
    [Fact]
    public void tsb0024() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION myconf RENAME TO myconf2", "ok");
    [Fact]
    public void tsb0025() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION myconf OWNER TO CURRENT_USER", "ok");
    [Fact]
    public void tsb0026() => CorpusAssert.Parses(@"CREATE TEXT SEARCH CONFIGURATION myconf (PARSER = pg_catalog.default);
ALTER TEXT SEARCH CONFIGURATION myconf SET SCHEMA s", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsb0027() => CorpusAssert.Parses(@"ALTER TEXT SEARCH CONFIGURATION pg_catalog.english ADD MAPPING FOR word WITH simple", "error");
    [Fact]
    public void tsb0028() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict (TEMPLATE = pg_catalog.simple)", "ok");
    [Fact]
    public void tsb0029() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict (TEMPLATE = pg_catalog.simple, STOPWORDS = english)", "ok");
    [Fact]
    public void tsb0030() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY s.mydict (TEMPLATE = pg_catalog.simple)", "ok");
    [Fact]
    public void tsb0031() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict (TEMPLATE = pg_catalog.snowball, LANGUAGE = english)", "ok");
    [Fact]
    public void tsb0032() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict (TEMPLATE = pg_catalog.snowball, LANGUAGE = english, STOPWORDS = english)", "ok");
    [Fact]
    public void tsb0033() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict ()", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsb0034() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict (TEMPLATE = nonexistent_template_xyz)", "error");
    [Fact]
    public void tsb0035() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY (TEMPLATE = pg_catalog.simple)", "error");
    [Fact]
    public void tsb0036() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict TEMPLATE = pg_catalog.simple", "error");
    [Fact]
    public void tsb0037() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict (TEMPLATE = pg_catalog.simple);
DROP TEXT SEARCH DICTIONARY mydict", "ok");
    [Fact]
    public void tsb0038() => CorpusAssert.Parses(@"DROP TEXT SEARCH DICTIONARY IF EXISTS no_such_dict_xyz", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsb0039() => CorpusAssert.Parses(@"DROP TEXT SEARCH DICTIONARY no_such_dict_xyz", "error");
    [Fact]
    public void tsb0040() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict (TEMPLATE = pg_catalog.simple);
DROP TEXT SEARCH DICTIONARY mydict CASCADE", "ok");
    [Fact]
    public void tsb0041() => CorpusAssert.Parses(@"CREATE TEXT SEARCH DICTIONARY mydict (TEMPLATE = pg_catalog.simple);
DROP TEXT SEARCH DICTIONARY mydict RESTRICT", "ok");
    [Fact]
    public void tsb0042() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER myparser (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype, HEADLINE = prsd_headline)", "ok");
    [Fact]
    public void tsb0043() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER myparser (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "ok");
    [Fact]
    public void tsb0044() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER s.myparser (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "ok");
    [Fact]
    public void tsb0045() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER myparser (GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype)", "error");
    [Fact]
    public void tsb0046() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER myparser (START = prsd_start, END = prsd_end, LEXTYPES = prsd_lextype)", "error");
    [Fact]
    public void tsb0047() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER myparser (START = prsd_start, GETTOKEN = prsd_nexttoken, LEXTYPES = prsd_lextype)", "error");
    [Fact]
    public void tsb0048() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER myparser (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end)", "error");
    [Fact]
    public void tsb0049() => CorpusAssert.Parses(@"CREATE TEXT SEARCH PARSER myparser (START = prsd_start, GETTOKEN = prsd_nexttoken, END = prsd_end, LEXTYPES = prsd_lextype);
DROP TEXT SEARCH PARSER myparser", "ok");
    [Fact]
    public void tsb0050() => CorpusAssert.Parses(@"DROP TEXT SEARCH PARSER IF EXISTS no_such_parser_xyz", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsb0051() => CorpusAssert.Parses(@"DROP TEXT SEARCH PARSER no_such_parser_xyz", "error");
    [Fact]
    public void tsb0052() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE mytempl (INIT = dsimple_init, LEXIZE = dsimple_lexize)", "ok");
    [Fact]
    public void tsb0053() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE mytempl (LEXIZE = dsimple_lexize)", "ok");
    [Fact]
    public void tsb0054() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE s.mytempl (LEXIZE = dsimple_lexize)", "ok");
    [Fact]
    public void tsb0055() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE mytempl (INIT = dsimple_init)", "error");
    [Fact]
    public void tsb0056() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE mytempl ()", "error");
    [Fact]
    public void tsb0057() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE mytempl (LEXIZE = dsimple_lexize);
DROP TEXT SEARCH TEMPLATE mytempl", "ok");
    [Fact]
    public void tsb0058() => CorpusAssert.Parses(@"DROP TEXT SEARCH TEMPLATE IF EXISTS no_such_template_xyz", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void tsb0059() => CorpusAssert.Parses(@"DROP TEXT SEARCH TEMPLATE no_such_template_xyz", "error");
    [Fact]
    public void tsb0060() => CorpusAssert.Parses(@"CREATE TEXT SEARCH TEMPLATE mytempl (LEXIZE = dsimple_lexize);
DROP TEXT SEARCH TEMPLATE mytempl CASCADE", "ok");
}
