// <auto-generated> Generated from tests/corpus/*.jsonl by CorpusTestGenerator. Do not edit by hand. </auto-generated>
using Xunit;

namespace PgProj.Core.Tests.Corpus;

public class Corpus_CreateFunction
{
    [Fact]
    public void fna0001() => CorpusAssert.Parses(@"CREATE FUNCTION s.add1(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x + 1 $$", "ok");
    [Fact]
    public void fna0002() => CorpusAssert.Parses(@"CREATE FUNCTION s.add2(integer, integer) RETURNS integer LANGUAGE sql AS $$ SELECT $1 + $2 $$", "ok");
    [Fact]
    public void fna0003() => CorpusAssert.Parses(@"CREATE OR REPLACE FUNCTION s.f(x integer) RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT x + 1 $$", "ok");
    [Fact]
    public void fna0004() => CorpusAssert.Parses(@"CREATE FUNCTION s.noop() RETURNS void LANGUAGE sql AS $$ SELECT 1 $$", "ok");
    [Fact]
    public void fna0005() => CorpusAssert.Parses(@"CREATE FUNCTION s.always_null(x integer) RETURNS integer LANGUAGE sql STRICT AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0006() => CorpusAssert.Parses(@"CREATE FUNCTION s.strict2(x integer) RETURNS integer LANGUAGE sql RETURNS NULL ON NULL INPUT AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0007() => CorpusAssert.Parses(@"CREATE FUNCTION s.called_null(x integer) RETURNS integer LANGUAGE sql CALLED ON NULL INPUT AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0008() => CorpusAssert.Parses(@"CREATE FUNCTION s.imm(x integer) RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0009() => CorpusAssert.Parses(@"CREATE FUNCTION s.stab(x integer) RETURNS integer LANGUAGE sql STABLE AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0010() => CorpusAssert.Parses(@"CREATE FUNCTION s.vol(x integer) RETURNS integer LANGUAGE sql VOLATILE AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0011() => CorpusAssert.Parses(@"CREATE FUNCTION s.sec_def(x integer) RETURNS integer LANGUAGE sql SECURITY DEFINER AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0012() => CorpusAssert.Parses(@"CREATE FUNCTION s.sec_inv(x integer) RETURNS integer LANGUAGE sql SECURITY INVOKER AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0013() => CorpusAssert.Parses(@"CREATE FUNCTION s.ext_sec_def(x integer) RETURNS integer LANGUAGE sql EXTERNAL SECURITY DEFINER AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0014() => CorpusAssert.Parses(@"CREATE FUNCTION s.ext_sec_inv(x integer) RETURNS integer LANGUAGE sql EXTERNAL SECURITY INVOKER AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0015() => CorpusAssert.Parses(@"CREATE FUNCTION s.par_safe(x integer) RETURNS integer LANGUAGE sql PARALLEL SAFE AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0016() => CorpusAssert.Parses(@"CREATE FUNCTION s.par_rest(x integer) RETURNS integer LANGUAGE sql PARALLEL RESTRICTED AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0017() => CorpusAssert.Parses(@"CREATE FUNCTION s.par_uns(x integer) RETURNS integer LANGUAGE sql PARALLEL UNSAFE AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0018() => CorpusAssert.Parses(@"CREATE FUNCTION s.withcost(x integer) RETURNS integer LANGUAGE sql COST 50 AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0019() => CorpusAssert.Parses(@"CREATE FUNCTION s.withcost2(x integer) RETURNS integer LANGUAGE sql COST 1.5 AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0020() => CorpusAssert.Parses(@"CREATE FUNCTION s.setof1() RETURNS SETOF integer LANGUAGE sql AS $$ SELECT 1 UNION SELECT 2 $$", "ok");
    [Fact]
    public void fna0021() => CorpusAssert.Parses(@"CREATE FUNCTION s.setof_t() RETURNS SETOF s.t LANGUAGE sql AS $$ SELECT * FROM s.t $$", "ok");
    [Fact]
    public void fna0022() => CorpusAssert.Parses(@"CREATE FUNCTION s.ret_tbl(lim int) RETURNS TABLE(a int, b text) LANGUAGE sql AS $$ SELECT 1, 'x' $$", "ok");
    [Fact]
    public void fna0023() => CorpusAssert.Parses(@"CREATE FUNCTION s.ret_tbl2() RETURNS TABLE(id bigint, nm text, v numeric) LANGUAGE sql AS $$ SELECT id, name, val FROM s.t $$", "ok");
    [Fact]
    public void fna0024() => CorpusAssert.Parses(@"CREATE FUNCTION s.ret_record() RETURNS record LANGUAGE sql AS $$ SELECT 1, 'x' $$", "ok");
    [Fact]
    public void fna0025() => CorpusAssert.Parses(@"CREATE FUNCTION s.rows_hint() RETURNS SETOF integer LANGUAGE sql ROWS 500 AS $$ SELECT 1 $$", "ok");
    [Fact]
    public void fna0026() => CorpusAssert.Parses(@"CREATE FUNCTION s.in_mode(IN x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0027() => CorpusAssert.Parses(@"CREATE FUNCTION s.out_mode(OUT x integer) LANGUAGE sql AS $$ SELECT 1 $$", "ok");
    [Fact]
    public void fna0028() => CorpusAssert.Parses(@"CREATE FUNCTION s.inout_mode(INOUT x integer) LANGUAGE sql AS $$ SELECT x + 1 $$", "ok");
    [Fact]
    public void fna0029() => CorpusAssert.Parses(@"CREATE FUNCTION s.in_out_both(IN a integer, OUT b integer) LANGUAGE sql AS $$ SELECT a * 2 $$", "ok");
    [Fact]
    public void fna0030() => CorpusAssert.Parses(@"CREATE FUNCTION s.variadic_fn(VARIADIC arr integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT arr[1] $$", "ok");
    [Fact]
    public void fna0031() => CorpusAssert.Parses(@"CREATE FUNCTION s.variadic_with_in(a text, VARIADIC nums integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT nums[1] $$", "ok");
    [Fact]
    public void fna0032() => CorpusAssert.Parses(@"CREATE FUNCTION s.with_default(x integer, y integer DEFAULT 10) RETURNS integer LANGUAGE sql AS $$ SELECT x + y $$", "ok");
    [Fact]
    public void fna0033() => CorpusAssert.Parses(@"CREATE FUNCTION s.with_eq_default(x integer, y integer = 10) RETURNS integer LANGUAGE sql AS $$ SELECT x + y $$", "ok");
    [Fact]
    public void fna0034() => CorpusAssert.Parses(@"CREATE FUNCTION s.multi_default(a integer = 1, b integer = 2, c integer = 3) RETURNS integer LANGUAGE sql AS $$ SELECT a + b + c $$", "ok");
    [Fact]
    public void fna0035() => CorpusAssert.Parses(@"CREATE FUNCTION s.plpgsql_fn(x integer) RETURNS integer LANGUAGE plpgsql AS $$ BEGIN RETURN x + 1; END $$", "ok");
    [Fact]
    public void fna0036() => CorpusAssert.Parses(@"CREATE FUNCTION s.plpgsql_declare(x integer) RETURNS integer LANGUAGE plpgsql AS $$ DECLARE v integer; BEGIN v := x + 1; RETURN v; END $$", "ok");
    [Fact]
    public void fna0037() => CorpusAssert.Parses(@"CREATE FUNCTION s.dollar_tag() RETURNS integer LANGUAGE sql AS $myTag$ SELECT 42 $myTag$", "ok");
    [Fact]
    public void fna0038() => CorpusAssert.Parses(@"CREATE FUNCTION s.single_quote_body() RETURNS integer LANGUAGE sql AS 'SELECT 42'", "ok");
    [Fact]
    public void fna0039() => CorpusAssert.Parses(@"CREATE FUNCTION s.set_config_fn(x integer) RETURNS integer LANGUAGE sql SET search_path TO s AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0040() => CorpusAssert.Parses(@"CREATE FUNCTION s.set_config_eq(x integer) RETURNS integer LANGUAGE sql SET work_mem = '4MB' AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0041() => CorpusAssert.Parses(@"CREATE FUNCTION s.set_from_current(x integer) RETURNS integer LANGUAGE sql SET search_path FROM CURRENT AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0042() => CorpusAssert.Parses(@"CREATE FUNCTION s.multi_set(x integer) RETURNS integer LANGUAGE sql SET search_path TO s SET work_mem = '4MB' AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0043() => CorpusAssert.Parses(@"CREATE FUNCTION s.begin_atomic() RETURNS integer LANGUAGE sql BEGIN ATOMIC SELECT 42; END", "ok");
    [Fact]
    public void fna0044() => CorpusAssert.Parses(@"CREATE FUNCTION s.begin_atomic_return(x integer) RETURNS integer LANGUAGE sql BEGIN ATOMIC RETURN x + 1; END", "ok");
    [Fact]
    public void fna0045() => CorpusAssert.Parses(@"CREATE FUNCTION s.begin_atomic_multi(a integer, b integer) RETURNS integer LANGUAGE sql BEGIN ATOMIC RETURN a + b; END", "ok");
    [Fact]
    public void fna0046() => CorpusAssert.Parses(@"CREATE FUNCTION s.imm_strict(x integer) RETURNS integer LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0047() => CorpusAssert.Parses(@"CREATE FUNCTION s.stable_safe(x integer) RETURNS integer LANGUAGE sql STABLE PARALLEL SAFE AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0048() => CorpusAssert.Parses(@"CREATE FUNCTION s.all_opts(x integer) RETURNS integer LANGUAGE sql IMMUTABLE STRICT SECURITY DEFINER PARALLEL SAFE COST 100 AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0049() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_mood(x integer) RETURNS s.mood LANGUAGE sql AS $$ SELECT 'ok'::s.mood $$", "ok");
    [Fact]
    public void fna0050() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_addr() RETURNS s.addr LANGUAGE sql AS $$ SELECT ROW('123 Main', 'Springfield', '12345')::s.addr $$", "ok");
    [Fact]
    public void fna0051() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_domain(x integer) RETURNS s.pos_int LANGUAGE sql AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0052() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_text_arr() RETURNS text[] LANGUAGE sql AS $$ SELECT ARRAY['a','b'] $$", "ok");
    [Fact]
    public void fna0053() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_setof_mood() RETURNS SETOF s.mood LANGUAGE sql AS $$ SELECT status FROM s.t $$", "ok");
    [Fact]
    public void fna0054() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_bool(x integer) RETURNS boolean LANGUAGE sql AS $$ SELECT x > 0 $$", "ok");
    [Fact]
    public void fna0055() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_numeric(x numeric) RETURNS numeric LANGUAGE sql IMMUTABLE AS $$ SELECT x * 2 $$", "ok");
    [Fact]
    public void fna0056() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_text(t text) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT upper(t) $$", "ok");
    [Fact]
    public void fna0057() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_jsonb(j jsonb) RETURNS jsonb LANGUAGE sql AS $$ SELECT j $$", "ok");
    [Fact]
    public void fna0058() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_ts() RETURNS timestamptz LANGUAGE sql STABLE AS $$ SELECT now() $$", "ok");
    [Fact]
    public void fna0059() => CorpusAssert.Parses(@"CREATE FUNCTION s.returns_bigint(x bigint) RETURNS bigint LANGUAGE sql IMMUTABLE AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0060() => CorpusAssert.Parses(@"CREATE FUNCTION s.out_named(IN a integer, OUT result integer) LANGUAGE sql AS $$ SELECT a * 2 $$", "ok");
    [Fact]
    public void fna0061() => CorpusAssert.Parses(@"CREATE FUNCTION s.multi_out(OUT x integer, OUT y text) LANGUAGE sql AS $$ SELECT 1, 'hello' $$", "ok");
    [Fact]
    public void fna0062() => CorpusAssert.Parses(@"CREATE FUNCTION s.inout_named(INOUT val integer) LANGUAGE sql AS $$ SELECT val + 10 $$", "ok");
    [Fact]
    public void fna0063() => CorpusAssert.Parses(@"CREATE FUNCTION s.in_default_null(x integer, y integer DEFAULT NULL) RETURNS integer LANGUAGE sql AS $$ SELECT COALESCE(y, x) $$", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0064() => CorpusAssert.Parses(@"CREATE FUNCTION s.in_default_expr(x integer, y integer DEFAULT x * 2) RETURNS integer LANGUAGE sql AS $$ SELECT y $$", "error");
    [Fact]
    public void fna0065() => CorpusAssert.Parses(@"CREATE FUNCTION s.schema_qual_lang(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0066() => CorpusAssert.Parses(@"CREATE FUNCTION s.quoted_lang(x integer) RETURNS integer LANGUAGE 'sql' AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0067() => CorpusAssert.Parses(@"CREATE FUNCTION s.leakproof_fn(x integer) RETURNS integer LANGUAGE sql IMMUTABLE LEAKPROOF AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0068() => CorpusAssert.Parses(@"CREATE FUNCTION s.not_leakproof(x integer) RETURNS integer LANGUAGE sql IMMUTABLE NOT LEAKPROOF AS $$ SELECT x $$", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0069() => CorpusAssert.Parses(@"CREATE FUNCTION s.cost_zero(x integer) RETURNS integer LANGUAGE sql COST 0 AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0070() => CorpusAssert.Parses(@"CREATE FUNCTION s.rows_on_scalar(x integer) RETURNS integer LANGUAGE sql ROWS 100 AS $$ SELECT x $$", "error");
    [Fact]
    public void fna0071() => CorpusAssert.Parses(@"CREATE FUNCTION (x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0072() => CorpusAssert.Parses(@"CREATE FUNCTION s.no_lang(x integer) RETURNS integer LANGUAGE sql", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0073() => CorpusAssert.Parses(@"CREATE FUNCTION s.bad_volatile(x integer) RETURNS integer LANGUAGE sql IMMUTABLE VOLATILE AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0074() => CorpusAssert.Parses(@"CREATE FUNCTION s.bad_strict(x integer) RETURNS integer LANGUAGE sql STRICT CALLED ON NULL INPUT AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0075() => CorpusAssert.Parses(@"CREATE FUNCTION s.bad_security(x integer) RETURNS integer LANGUAGE sql SECURITY DEFINER SECURITY INVOKER AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0076() => CorpusAssert.Parses(@"CREATE FUNCTION s.bad_parallel(x integer) RETURNS integer LANGUAGE sql PARALLEL SAFE PARALLEL UNSAFE AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0077() => CorpusAssert.Parses(@"CREATE FUNCTION s.bad_mode(INOUT VARIADIC x integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT x[1] $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0078() => CorpusAssert.Parses(@"CREATE FUNCTION s.bad_returns_table_out(OUT x integer) RETURNS TABLE(a int) LANGUAGE sql AS $$ SELECT 1, 1 $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0079() => CorpusAssert.Parses(@"CREATE FUNCTION s.bad_default_order(x integer DEFAULT 0, y integer) RETURNS integer LANGUAGE sql AS $$ SELECT x + y $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0080() => CorpusAssert.Parses(@"CREATE FUNCTION s.bad_parallel_val(x integer) RETURNS integer LANGUAGE sql PARALLEL MAYBE AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0081() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_variadic_not_array(VARIADIC x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0082() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_extra_comma(x integer,) RETURNS integer LANGUAGE sql AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0083() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_cost_str(x integer) RETURNS integer LANGUAGE sql COST 'a lot' AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0084() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_rows_negative(x integer) RETURNS SETOF integer LANGUAGE sql ROWS -1 AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0085() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_duplicate() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$; CREATE FUNCTION s.fn_duplicate() RETURNS integer LANGUAGE sql AS $$ SELECT 2 $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0086() => CorpusAssert.Parses(@"CREATE OR REPLACE FUNCTION s.f(x integer) RETURNS text LANGUAGE sql AS $$ SELECT x::text $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0087() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_rettype(x integer) RETURNS nonexistent_type_xyz LANGUAGE sql AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0088() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_lang(x integer) RETURNS integer LANGUAGE nonexistent_lang_xyz AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0089() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_argtype(x nonexistent_xyz) RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$", "error");
    [Fact]
    public void fna0090() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_rows(n integer) RETURNS SETOF integer LANGUAGE sql ROWS 200 AS $$ SELECT generate_series(1, n) $$", "ok");
    [Fact]
    public void fna0091() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_table_rows() RETURNS TABLE(x int) LANGUAGE sql ROWS 50 AS $$ SELECT 1 $$", "ok");
    [Fact]
    public void fna0092() => CorpusAssert.Parses(@"CREATE FUNCTION s.plpgsql_sec(p text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = s AS $$ BEGIN RETURN p IS NOT NULL; END $$", "ok");
    [Fact]
    public void fna0093() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_void2() RETURNS void LANGUAGE plpgsql AS $$ BEGIN PERFORM s.f(1); END $$", "ok");
    [Fact]
    public void fna0094() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_out_inout(IN a integer, OUT b integer, INOUT c integer) LANGUAGE sql AS $$ SELECT a + c, c + 1 $$", "ok");
    [Fact]
    public void fna0095() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_variadic_out(VARIADIC nums integer[], OUT total integer) LANGUAGE sql AS $$ SELECT sum(n) FROM unnest(nums) n $$", "ok");
    [Fact]
    public void fna0096() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_no_args() RETURNS integer LANGUAGE sql AS $$ SELECT 99 $$", "ok");
    [Fact]
    public void fna0097() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_text_default(t text DEFAULT 'hello') RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT t $$", "ok");
    [Fact]
    public void fna0098() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bool_default(b boolean DEFAULT true) RETURNS boolean LANGUAGE sql IMMUTABLE AS $$ SELECT b $$", "ok");
    [Fact]
    public void fna0099() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_numeric_default(n numeric DEFAULT 3.14) RETURNS numeric LANGUAGE sql IMMUTABLE AS $$ SELECT n $$", "ok");
    [Fact]
    public void fna0100() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_array_param(arr integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT arr[1] $$", "ok");
    [Fact]
    public void fna0101() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_jsonb_param(j jsonb, k text) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT j ->> k $$", "ok");
    [Fact]
    public void fna0102() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_ts_param(ts timestamptz) RETURNS date LANGUAGE sql IMMUTABLE AS $$ SELECT ts::date $$", "ok");
    [Fact]
    public void fna0103() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_overload_text(x text) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0104() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_set_multi_val(x integer) RETURNS integer LANGUAGE sql SET search_path TO s, public AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0105() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_cost_rows(x integer) RETURNS SETOF integer LANGUAGE sql COST 10 ROWS 1000 AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0106() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_immutable_leakproof(x integer) RETURNS integer LANGUAGE sql IMMUTABLE LEAKPROOF STRICT AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0107() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_lang_plpgsql_strict(x integer) RETURNS integer LANGUAGE plpgsql STRICT AS $$ BEGIN RETURN x; END $$", "ok");
    [Fact]
    public void fna0108() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_stable(x integer) RETURNS integer LANGUAGE plpgsql STABLE AS $$ BEGIN RETURN x; END $$", "ok");
    [Fact]
    public void fna0109() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_immutable(x integer) RETURNS integer LANGUAGE plpgsql IMMUTABLE AS $$ BEGIN RETURN x * 2; END $$", "ok");
    [Fact]
    public void fna0110() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_tbl_wide() RETURNS TABLE(a int, b text, c boolean, d numeric) LANGUAGE sql AS $$ SELECT 1, 'x', true, 1.0 $$", "ok");
    [Fact]
    public void fna0111() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_begin_atomic_void() RETURNS void LANGUAGE sql BEGIN ATOMIC INSERT INTO s.t(name) VALUES('x'); END", "ok");
    [Fact]
    public void fna0112() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_upper_keywords(X INTEGER) RETURNS INTEGER LANGUAGE SQL IMMUTABLE AS $$ SELECT X $$", "ok");
    [Fact]
    public void fna0113() => CorpusAssert.Parses(@"CREATE FUNCTION ""s"".""fn_quoted_name""(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0114() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_out_with_explicit_returns(OUT result integer) RETURNS integer LANGUAGE sql AS $$ SELECT 42 $$", "ok");
    [Fact]
    public void fna0115() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_variadic_last(a integer, b text, VARIADIC rest text[]) RETURNS text LANGUAGE sql AS $$ SELECT b || rest[1] $$", "ok");
    [Fact]
    public void fna0116() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_default_call(x integer, y integer DEFAULT 5) RETURNS integer LANGUAGE sql AS $$ SELECT x + y $$", "ok");
    [Fact]
    public void fna0117() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_parallel(x integer) RETURNS integer LANGUAGE plpgsql PARALLEL RESTRICTED AS $$ BEGIN RETURN x; END $$", "ok");
    [Fact]
    public void fna0118() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_dollar_nested() RETURNS text LANGUAGE plpgsql AS $outer$ BEGIN RETURN $inner$hello$inner$; END $outer$", "ok");
    [Fact]
    public void fna0119() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_search_path_empty(x integer) RETURNS integer LANGUAGE sql SET search_path = '' AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0120() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_with_comment(x integer) RETURNS integer LANGUAGE sql -- inline comment
AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0121() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_body_refs_fixture(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT s.f(x) $$", "ok");
    [Fact]
    public void fna0122() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_body_refs_table() RETURNS bigint LANGUAGE sql STABLE AS $$ SELECT count(*) FROM s.t $$", "ok");
    [Fact]
    public void fna0123() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_body_refs_seq() RETURNS bigint LANGUAGE sql AS $$ SELECT nextval('s.seq') $$", "ok");
    [Fact]
    public void fna0124() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_body_refs_view() RETURNS bigint LANGUAGE sql STABLE AS $$ SELECT count(*) FROM s.v $$", "ok");
    [Fact]
    public void fna0125() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_create_and_use() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$; SELECT s.fn_create_and_use()", "ok");
    [Fact]
    public void fna0126() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_two_creates_a(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$; CREATE FUNCTION s.fn_two_creates_b(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x * 2 $$", "ok");
    [Fact]
    public void fna0127() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_replace_then_call() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$; CREATE OR REPLACE FUNCTION s.fn_replace_then_call() RETURNS integer LANGUAGE sql AS $$ SELECT 2 $$; SELECT s.fn_replace_then_call()", "ok");
    [Fact]
    public void fna0128() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_cost2(x integer) RETURNS integer LANGUAGE plpgsql COST 200 AS $$ BEGIN RETURN x; END $$", "ok");
    [Fact]
    public void fna0129() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_security_invoker_default(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0130() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_exception(x integer) RETURNS integer LANGUAGE plpgsql AS $$ BEGIN RETURN x; EXCEPTION WHEN division_by_zero THEN RETURN -1; END $$", "ok");
    [Fact]
    public void fna0131() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_if(x integer) RETURNS integer LANGUAGE plpgsql AS $$ BEGIN IF x > 0 THEN RETURN 1; ELSE RETURN -1; END IF; END $$", "ok");
    [Fact]
    public void fna0132() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_loop(n integer) RETURNS integer LANGUAGE plpgsql AS $fn$ DECLARE i integer := 0; tot integer := 0; BEGIN FOR i IN 1..n LOOP tot := tot + i; END LOOP; RETURN tot; END $fn$", "ok");
    [Fact]
    public void fna0133() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_plpgsql() RETURNS SETOF s.t LANGUAGE plpgsql STABLE AS $fn$ BEGIN RETURN QUERY SELECT * FROM s.t; END $fn$", "ok");
    [Fact]
    public void fna0134() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_table_plpgsql(lim int) RETURNS TABLE(id bigint, nm text) LANGUAGE plpgsql STABLE AS $fn$ BEGIN RETURN QUERY SELECT t.id, t.name FROM s.t LIMIT lim; END $fn$", "ok");
    [Fact]
    public void fna0135() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_out_plpgsql(IN x integer, OUT result integer) LANGUAGE plpgsql AS $fn$ BEGIN result := x * 3; END $fn$", "ok");
    [Fact]
    public void fna0136() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_inout_plpgsql(INOUT v integer) LANGUAGE plpgsql AS $fn$ BEGIN v := v + 100; END $fn$", "ok");
    [Fact]
    public void fna0137() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_using_g() RETURNS integer LANGUAGE sql AS $fn$ SELECT s.g(10, 20) $fn$", "ok");
    [Fact]
    public void fna0138() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_using_g_default() RETURNS integer LANGUAGE sql AS $$ SELECT s.g(10) $$", "ok");
    [Fact]
    public void fna0139() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_setof_record() RETURNS SETOF record LANGUAGE sql AS $$ SELECT 1 AS a, 'x' AS b $$", "ok");
    [Fact]
    public void fna0140() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_variadic_text(VARIADIC words text[]) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT array_to_string(words, ' ') $$", "ok");
    [Fact]
    public void fna0141() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_window_sql() RETURNS integer LANGUAGE sql WINDOW AS $$ SELECT 1 $$", "ok");
    [Fact]
    public void fna0142() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_raise(x integer) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RAISE NOTICE 'val=%', x; END $$", "ok");
    [Fact]
    public void fna0143() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_interval(d integer) RETURNS interval LANGUAGE sql IMMUTABLE AS $$ SELECT (d || ' days')::interval $$", "ok");
    [Fact]
    public void fna0144() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_bytea(b bytea) RETURNS bytea LANGUAGE sql IMMUTABLE AS $$ SELECT b $$", "ok");
    [Fact]
    public void fna0145() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_uuid() RETURNS uuid LANGUAGE sql AS $$ SELECT gen_random_uuid() $$", "ok");
    [Fact]
    public void fna0146() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_set_timezone(x integer) RETURNS integer LANGUAGE sql SET TimeZone = 'UTC' AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0147() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_begin_atomic_imm() RETURNS integer LANGUAGE sql IMMUTABLE BEGIN ATOMIC RETURN 42; END", "ok");
    [Fact]
    public void fna0148() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_begin_atomic_strict() RETURNS integer LANGUAGE sql STRICT BEGIN ATOMIC RETURN 1; END", "ok");
    [Fact]
    public void fna0149() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_no_schema(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0150() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_multiline_body(x integer) RETURNS integer LANGUAGE sql AS $body$
SELECT
  x * 2
$body$", "ok");
    [Fact]
    public void fna0151() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_multi_out(OUT a integer, OUT b text, OUT c boolean) LANGUAGE plpgsql AS $$ BEGIN a := 1; b := 'hi'; c := true; END $$", "ok");
    [Fact]
    public void fna0152() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_window(x integer) RETURNS integer LANGUAGE plpgsql WINDOW AS $$ BEGIN RETURN x; END $$", "ok");
    [Fact]
    public void fna0153() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_cost_rows(n integer) RETURNS SETOF integer LANGUAGE plpgsql COST 50 ROWS 100 AS $fn$ BEGIN RETURN QUERY SELECT generate_series(1, n); END $fn$", "ok");
    [Fact]
    public void fna0154() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_addr() RETURNS SETOF s.addr LANGUAGE sql AS $$ SELECT home FROM s.t WHERE home IS NOT NULL $$", "ok");
    [Fact]
    public void fna0155() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_option_order1(x integer) RETURNS integer LANGUAGE sql COST 10 IMMUTABLE STRICT PARALLEL SAFE SECURITY DEFINER AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0156() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_option_order2(x integer) RETURNS integer AS $$ SELECT x $$ LANGUAGE sql IMMUTABLE", "ok");
    [Fact]
    public void fna0157() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_option_order3(x integer) RETURNS integer IMMUTABLE LANGUAGE sql AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0158() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_perform2() RETURNS void LANGUAGE plpgsql AS $$ BEGIN PERFORM s.f(42); END $$", "ok");
    [Fact]
    public void fna0159() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_enum_param(m s.mood) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT m::text $$", "ok");
    [Fact]
    public void fna0160() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_composite_param(a s.addr) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT (a).city $$", "ok");
    [Fact]
    public void fna0161() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_domain_param(x s.pos_int) RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT x $$", "ok");
    [Fact]
    public void fna0162() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_named_notation(a integer, b integer DEFAULT 0) RETURNS integer LANGUAGE sql AS $$ SELECT a + b $$; SELECT s.fn_named_notation(a => 5, b => 3)", "ok");
    [Fact]
    public void fna0163() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_named_notation2(a integer, b integer DEFAULT 0) RETURNS integer LANGUAGE sql AS $$ SELECT a + b $$; SELECT s.fn_named_notation2(b := 3, a := 5)", "ok");
    [Fact]
    public void fna0164() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_perform3() RETURNS void LANGUAGE plpgsql AS $fn$ BEGIN PERFORM s.f(42); END $fn$", "ok");
    [Fact]
    public void fna0165() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_begin_atomic_setof() RETURNS SETOF integer LANGUAGE sql BEGIN ATOMIC SELECT 1; SELECT 2; END", "ok");
    [Fact]
    public void fna0166() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_internal_valid() RETURNS integer LANGUAGE internal AS 'int4pl'", "ok");
    [Fact]
    public void fna0167() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_plpgsql2() RETURNS SETOF integer LANGUAGE plpgsql AS $fn$ BEGIN RETURN QUERY SELECT generate_series(1, 5); END $fn$", "ok");
    [Fact]
    public void fna0168() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_inout_plpgsql2(INOUT val integer) LANGUAGE plpgsql AS $fn2$ BEGIN val := val + 100; END $fn2$", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0169() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_returns_no_keyword(x integer) integer LANGUAGE sql AS $$ SELECT x $$", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fna0170() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_missing_as_keyword(x integer) RETURNS integer LANGUAGE sql $$ SELECT x $$", "error");
    [Fact]
    public void fnb0001() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_basic(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x + 1 $$;", "ok");
    [Fact]
    public void fnb0002() => CorpusAssert.Parses(@"CREATE OR REPLACE FUNCTION s.fn_basic(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x + 1 $$;", "ok");
    [Fact]
    public void fnb0003() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_void() RETURNS void LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnb0004() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_record() RETURNS record LANGUAGE sql AS $$ SELECT 1, 'x' $$;", "ok");
    [Fact]
    public void fnb0005() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof(n integer) RETURNS SETOF integer LANGUAGE sql AS $$ SELECT generate_series(1, n) $$;", "ok");
    [Fact]
    public void fnb0006() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_t() RETURNS SETOF s.t LANGUAGE sql AS $$ SELECT * FROM s.t $$;", "ok");
    [Fact]
    public void fnb0007() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_table() RETURNS TABLE(a integer, b text) LANGUAGE sql AS $$ SELECT 1, 'x' $$;", "ok");
    [Fact]
    public void fnb0008() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_table2() RETURNS TABLE(id bigint, name text, val numeric) LANGUAGE sql AS $$ SELECT id, name, val FROM s.t $$;", "ok");
    [Fact]
    public void fnb0009() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_in_arg(IN x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0010() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_out_arg(OUT result integer) RETURNS integer LANGUAGE sql AS $$ SELECT 42 $$;", "ok");
    [Fact]
    public void fnb0011() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_out_only(OUT result integer) LANGUAGE sql AS $$ SELECT 42 $$;", "ok");
    [Fact]
    public void fnb0012() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_inout(INOUT x integer) LANGUAGE sql AS $$ SELECT x + 1 $$;", "ok");
    [Fact]
    public void fnb0013() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_variadic(VARIADIC arr integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT arr[1] $$;", "ok");
    [Fact]
    public void fnb0014() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_variadic_named(VARIADIC nums integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT array_length(nums, 1) $$;", "ok");
    [Fact]
    public void fnb0015() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_mixed_modes(IN a integer, OUT b integer, INOUT c integer) LANGUAGE sql AS $$ SELECT a, c $$;", "ok");
    [Fact]
    public void fnb0016() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_default_eq(x integer = 5) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0017() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_default_kw(x integer DEFAULT 5) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0018() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_multi_default(a integer DEFAULT 1, b integer DEFAULT 2) RETURNS integer LANGUAGE sql AS $$ SELECT a + b $$;", "ok");
    [Fact]
    public void fnb0019() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_named_args(IN p_id bigint, IN p_name text DEFAULT NULL) RETURNS text LANGUAGE sql AS $$ SELECT p_name $$;", "ok");
    [Fact]
    public void fnb0020() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_immutable(x integer) RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT x * 2 $$;", "ok");
    [Fact]
    public void fnb0021() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_stable(x integer) RETURNS integer LANGUAGE sql STABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0022() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_volatile(x integer) RETURNS integer LANGUAGE sql VOLATILE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0023() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_leakproof(x integer) RETURNS integer LANGUAGE sql IMMUTABLE LEAKPROOF AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0024() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_not_leakproof(x integer) RETURNS integer LANGUAGE sql IMMUTABLE NOT LEAKPROOF AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0025() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_strict(x integer) RETURNS integer LANGUAGE sql STRICT AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0026() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_null(x integer) RETURNS integer LANGUAGE sql RETURNS NULL ON NULL INPUT AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0027() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_called_null(x integer) RETURNS integer LANGUAGE sql CALLED ON NULL INPUT AS $$ SELECT COALESCE(x, 0) $$;", "ok");
    [Fact]
    public void fnb0028() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_security_definer(x integer) RETURNS integer LANGUAGE sql SECURITY DEFINER AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0029() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_security_invoker(x integer) RETURNS integer LANGUAGE sql SECURITY INVOKER AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0030() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_ext_sec_def(x integer) RETURNS integer LANGUAGE sql EXTERNAL SECURITY DEFINER AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0031() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_ext_sec_inv(x integer) RETURNS integer LANGUAGE sql EXTERNAL SECURITY INVOKER AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0032() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_parallel_safe(x integer) RETURNS integer LANGUAGE sql PARALLEL SAFE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0033() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_parallel_restricted(x integer) RETURNS integer LANGUAGE sql PARALLEL RESTRICTED AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0034() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_parallel_unsafe(x integer) RETURNS integer LANGUAGE sql PARALLEL UNSAFE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0035() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_cost(x integer) RETURNS integer LANGUAGE sql COST 100 AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0036() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_cost_real(x integer) RETURNS integer LANGUAGE sql COST 10.5 AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0037() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_rows(n integer) RETURNS SETOF integer LANGUAGE sql ROWS 100 AS $$ SELECT generate_series(1, n) $$;", "ok");
    [Fact]
    public void fnb0038() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_set_config() RETURNS integer LANGUAGE sql SET search_path TO s AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnb0039() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_set_from_current() RETURNS integer LANGUAGE sql SET search_path FROM CURRENT AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnb0040() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_set_eq() RETURNS integer LANGUAGE sql SET work_mem = '4MB' AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnb0041() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql(x integer) RETURNS integer LANGUAGE plpgsql AS $$ BEGIN RETURN x + 1; END $$;", "ok");
    [Fact]
    public void fnb0042() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_decl(x integer) RETURNS integer LANGUAGE plpgsql AS $$ DECLARE v integer; BEGIN v := x + 1; RETURN v; END $$;", "ok");
    [Fact]
    public void fnb0043() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_dollar_tag(x integer) RETURNS integer LANGUAGE sql AS $body$ SELECT x + 1 $body$;", "ok");
    [Fact]
    public void fnb0044() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_dollar_nested(x integer) RETURNS text LANGUAGE plpgsql AS $outer$ BEGIN RETURN $inner$ hello $inner$; END $outer$;", "ok");
    [Fact]
    public void fnb0045() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_no_args() RETURNS integer LANGUAGE sql AS $$ SELECT 42 $$;", "ok");
    [Fact]
    public void fnb0046() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_text() RETURNS text LANGUAGE sql AS $$ SELECT 'hello' $$;", "ok");
    [Fact]
    public void fnb0047() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bool() RETURNS boolean LANGUAGE sql IMMUTABLE AS $$ SELECT true $$;", "ok");
    [Fact]
    public void fnb0048() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_numeric() RETURNS numeric LANGUAGE sql IMMUTABLE AS $$ SELECT 3.14 $$;", "ok");
    [Fact]
    public void fnb0049() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_timestamptz() RETURNS timestamptz LANGUAGE sql STABLE AS $$ SELECT now() $$;", "ok");
    [Fact]
    public void fnb0050() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_array() RETURNS integer[] LANGUAGE sql IMMUTABLE AS $$ SELECT ARRAY[1,2,3] $$;", "ok");
    [Fact]
    public void fnb0051() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_jsonb() RETURNS jsonb LANGUAGE sql IMMUTABLE AS $$ SELECT '{""a"":1}'::jsonb $$;", "ok");
    [Fact]
    public void fnb0052() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_enum_ret() RETURNS s.mood LANGUAGE sql IMMUTABLE AS $$ SELECT 'ok'::s.mood $$;", "ok");
    [Fact]
    public void fnb0053() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_composite_ret() RETURNS s.addr LANGUAGE sql IMMUTABLE AS $$ SELECT ROW('1 Main', 'Springfield', '12345')::s.addr $$;", "ok");
    [Fact]
    public void fnb0054() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_domain_ret() RETURNS s.pos_int LANGUAGE sql IMMUTABLE AS $$ SELECT 5::s.pos_int $$;", "ok");
    [Fact]
    public void fnb0055() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_all_options(x integer) RETURNS integer LANGUAGE sql IMMUTABLE STRICT SECURITY DEFINER PARALLEL SAFE COST 1 SET search_path TO s AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0056() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_options_order2(x integer) RETURNS integer LANGUAGE sql COST 1 PARALLEL SAFE IMMUTABLE STRICT AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0057() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_options_order3(x integer) RETURNS integer LANGUAGE sql SECURITY INVOKER VOLATILE PARALLEL UNSAFE CALLED ON NULL INPUT AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0058() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_window(x integer) RETURNS integer LANGUAGE sql WINDOW AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0059() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_variadic_text(VARIADIC words text[]) RETURNS text LANGUAGE sql AS $$ SELECT array_to_string(words, ' ') $$;", "ok");
    [Fact]
    public void fnb0060() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_in_variadic(a integer, VARIADIC rest integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT a + COALESCE(rest[1], 0) $$;", "ok");
    [Fact]
    public void fnb0061() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_multi_out(OUT a integer, OUT b text) LANGUAGE sql AS $$ SELECT 1, 'hello' $$;", "ok");
    [Fact]
    public void fnb0062() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_in_out_combo(IN x integer, OUT y integer, OUT z text) LANGUAGE sql AS $$ SELECT x * 2, x::text $$;", "ok");
    [Fact]
    public void fnb0063() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_inout_multi(INOUT a integer, INOUT b integer) LANGUAGE sql AS $$ SELECT a + 1, b + 1 $$;", "ok");
    [Fact]
    public void fnb0064() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_default_expr(x integer DEFAULT s.f(1)) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0065() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_default_arith(x integer DEFAULT 2 + 3) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0066() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_sql_body_atomic(x integer) RETURNS integer LANGUAGE sql BEGIN ATOMIC RETURN x + 1; END;", "ok");
    [Fact]
    public void fnb0067() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_sql_body_multi(x integer) RETURNS integer LANGUAGE sql BEGIN ATOMIC SELECT x; RETURN x + 1; END;", "ok");
    [Fact]
    public void fnb0068() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_sql_begin_immutable(x integer) RETURNS integer LANGUAGE sql IMMUTABLE BEGIN ATOMIC RETURN x * 2; END;", "ok");
    [Fact]
    public void fnb0069() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_rows_real(n integer) RETURNS SETOF integer LANGUAGE sql ROWS 1000.0 AS $$ SELECT generate_series(1, n) $$;", "ok");
    [Fact]
    public void fnb0070() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_set_multi() RETURNS integer LANGUAGE sql SET search_path TO s, public SET work_mem = '8MB' AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnb0071() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_called_first(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$ CALLED ON NULL INPUT;", "ok");
    [Fact]
    public void fnb0072() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_uppercase_lang(x integer) RETURNS integer LANGUAGE SQL AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0073() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_upper_keywords(X INTEGER) RETURNS INTEGER LANGUAGE SQL IMMUTABLE AS $$ SELECT X $$;", "ok");
    [Fact]
    public void fnb0074() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_qualified_type(x pg_catalog.int4) RETURNS pg_catalog.int4 LANGUAGE sql IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0075() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_table_many_cols() RETURNS TABLE(id bigint, name text, val numeric, qty integer, flag boolean) LANGUAGE sql AS $$ SELECT id, name, val, qty, flag FROM s.t $$;", "ok");
    [Fact]
    public void fnb0076() => CorpusAssert.Parses(@"CREATE FUNCTION fn_unqualified(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0077() => CorpusAssert.Parses(@"CREATE FUNCTION s.""fn-hyphen""(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0078() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_comment_in_body(x integer) RETURNS integer LANGUAGE sql AS $$ -- add one
SELECT x + 1 $$;", "ok");
    [Fact]
    public void fnb0079() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_record() RETURNS SETOF record LANGUAGE sql AS $$ SELECT 1, 'x' $$;", "ok");
    [Fact]
    public void fnb0080() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_out(OUT result text) LANGUAGE plpgsql AS $$ BEGIN result := 'hello'; END $$;", "ok");
    [Fact]
    public void fnb0081() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_strict(x integer) RETURNS integer LANGUAGE plpgsql STRICT AS $$ BEGIN RETURN x + 1; END $$;", "ok");
    [Fact]
    public void fnb0082() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_sec_def(x integer) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN RETURN x; END $$;", "ok");
    [Fact]
    public void fnb0083() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_stable(x integer) RETURNS integer LANGUAGE plpgsql STABLE AS $$ BEGIN RETURN x; END $$;", "ok");
    [Fact]
    public void fnb0084() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_cost(x integer) RETURNS integer LANGUAGE plpgsql COST 200 AS $$ BEGIN RETURN x; END $$;", "ok");
    [Fact]
    public void fnb0085() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_in_named(IN p_x integer) RETURNS integer LANGUAGE sql AS $$ SELECT p_x $$;", "ok");
    [Fact]
    public void fnb0086() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_three_args(a integer, b text, c boolean DEFAULT false) RETURNS text LANGUAGE sql AS $$ SELECT b $$;", "ok");
    [Fact]
    public void fnb0087() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_or_replace_noop(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$; CREATE OR REPLACE FUNCTION s.fn_or_replace_noop(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x + 0 $$;", "ok");
    [Fact]
    public void fnb0088() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_rows_setof_table() RETURNS SETOF s.t LANGUAGE sql ROWS 50 AS $$ SELECT * FROM s.t $$;", "ok");
    [Fact]
    public void fnb0089() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_enum() RETURNS SETOF s.mood LANGUAGE sql AS $$ SELECT unnest(ARRAY['sad','ok','happy']::s.mood[]) $$;", "ok");
    [Fact]
    public void fnb0090() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_domain() RETURNS SETOF s.pos_int LANGUAGE sql AS $$ SELECT generate_series(1,3)::s.pos_int $$;", "ok");
    [Fact]
    public void fnb0091() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_empty_parens() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnb0092() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_cost_rows_combo(n integer) RETURNS SETOF integer LANGUAGE sql COST 50 ROWS 200 AS $$ SELECT generate_series(1,n) $$;", "ok");
    [Fact]
    public void fnb0093() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_security_parallel(x integer) RETURNS integer LANGUAGE sql SECURITY DEFINER PARALLEL SAFE IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0094() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_leakproof_strict(x integer) RETURNS integer LANGUAGE sql IMMUTABLE LEAKPROOF STRICT AS $$ SELECT x $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0095() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_set_local_off() RETURNS integer LANGUAGE sql SET LOCAL AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0096() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_no_returns() LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0097() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_parallel(x integer) RETURNS integer LANGUAGE sql PARALLEL SUPERFAST AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0098() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_volatility(x integer) RETURNS integer LANGUAGE sql MUTABLE AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0099() => CorpusAssert.Parses(@"CREATE (x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "error");
    [Fact]
    public void fnb0100() => CorpusAssert.Parses(@"CREATE FUNCTION (x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0101() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_arg_type(x NOSUCHTYPE) RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0102() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_missing_as(x integer) RETURNS integer LANGUAGE sql $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0103() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_missing_language(x integer) RETURNS integer AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0104() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_cost(x integer) RETURNS integer LANGUAGE sql COST 'expensive' AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0105() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_rows(n integer) RETURNS SETOF integer LANGUAGE sql ROWS 'many' AS $$ SELECT generate_series(1,n) $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0106() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_variadic_not_last(VARIADIC arr integer[], x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0107() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_default_then_nodefault(x integer DEFAULT 1, y integer) RETURNS integer LANGUAGE sql AS $$ SELECT x + y $$;", "error");
    [Fact]
    public void fnb0108() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_dup_mode(IN OUT x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0109() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_after_out(OUT x integer) RETURNS void LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0110() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_lang(x integer) RETURNS integer LANGUAGE nonexistent_lang AS $$ SELECT x $$;", "error");
    [Fact]
    public void fnb0111() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_leakproof_volatile(x integer) RETURNS integer LANGUAGE sql VOLATILE LEAKPROOF AS $$ SELECT x $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0112() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_missing_body(x integer) RETURNS integer LANGUAGE sql;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0113() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_comma_extra(x integer,) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0114() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_missing_type(x integer) RETURNS LANGUAGE sql AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0115() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_table_no_cols() RETURNS TABLE() LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0116() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_table_invalid() RETURNS SETOF TABLE(a int) LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0117() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_parallel_none(x integer) RETURNS integer LANGUAGE sql PARALLEL NONE AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0118() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_duplicate_immutable(x integer) RETURNS integer LANGUAGE sql IMMUTABLE IMMUTABLE AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0119() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_stable_immutable(x integer) RETURNS integer LANGUAGE sql STABLE IMMUTABLE AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0120() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_sec_def_invoker(x integer) RETURNS integer LANGUAGE sql SECURITY DEFINER SECURITY INVOKER AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0121() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_strict_called(x integer) RETURNS integer LANGUAGE sql STRICT CALLED ON NULL INPUT AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0122() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_begin_atomic(x integer) RETURNS integer LANGUAGE plpgsql BEGIN ATOMIC RETURN x + 1; END;", "error");
    [Fact]
    public void fnb0123() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_integer_type(x int) RETURNS int LANGUAGE sql IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0124() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bigint_type(x bigint) RETURNS bigint LANGUAGE sql IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0125() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_float8(x float8) RETURNS float8 LANGUAGE sql IMMUTABLE AS $$ SELECT x * 2.0 $$;", "ok");
    [Fact]
    public void fnb0126() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_varchar(x varchar(100)) RETURNS varchar LANGUAGE sql IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0127() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_char_n(x char(10)) RETURNS char LANGUAGE sql IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0128() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_decimal_type(x decimal(10,2)) RETURNS decimal LANGUAGE sql IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0129() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_setof_void() RETURNS SETOF void LANGUAGE sql AS $$ SELECT $$;", "ok");
    [Fact]
    public void fnb0130() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_any_type(x anyelement) RETURNS anyelement LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0131() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_anyarray(x anyarray) RETURNS anyarray LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0132() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_anynonarray(x anynonarray) RETURNS anynonarray LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0133() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_anycompatible(x anycompatible) RETURNS anycompatible LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0134() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_anyrange(x anyrange) RETURNS anyrange LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0135() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_sql_body_return_text() RETURNS text LANGUAGE sql BEGIN ATOMIC RETURN 'hello'; END;", "ok");
    [Fact]
    public void fnb0136() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_sql_body_strict(x integer) RETURNS integer LANGUAGE sql STRICT BEGIN ATOMIC RETURN x; END;", "ok");
    [Fact]
    public void fnb0137() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_sql_body_security(x integer) RETURNS integer LANGUAGE sql SECURITY DEFINER BEGIN ATOMIC RETURN x; END;", "ok");
    [Fact]
    public void fnb0138() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_exception(x integer) RETURNS integer LANGUAGE plpgsql AS $$ BEGIN RETURN x; EXCEPTION WHEN division_by_zero THEN RETURN 0; END $$;", "ok");
    [Fact]
    public void fnb0139() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_if(x integer) RETURNS text LANGUAGE plpgsql AS $$ BEGIN IF x > 0 THEN RETURN 'positive'; ELSE RETURN 'non-positive'; END IF; END $$;", "ok");
    [Fact]
    public void fnb0140() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_loop(n integer) RETURNS integer LANGUAGE plpgsql AS $$ DECLARE i integer := 0; BEGIN FOR i IN 1..n LOOP NULL; END LOOP; RETURN i; END $$;", "ok");
    [Fact]
    public void fnb0141() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_create_then_call(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT s.f(x) $$;", "ok");
    [Fact]
    public void fnb0142() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_returns_existing_func_type(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT s.g(x, 0) $$;", "ok");
    [Fact]
    public void fnb0143() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_table_out_pk() RETURNS TABLE(id bigint, label text) LANGUAGE sql AS $$ SELECT id, label FROM s.t2 $$;", "ok");
    [Fact]
    public void fnb0144() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_window_immutable(x integer) RETURNS integer LANGUAGE sql WINDOW IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0145() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_set_reset() RETURNS integer LANGUAGE sql SET work_mem TO DEFAULT AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnb0146() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_raise(x integer) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF x < 0 THEN RAISE EXCEPTION 'negative: %', x; END IF; END $$;", "ok");
    [Fact]
    public void fnb0147() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_return_query() RETURNS SETOF s.t LANGUAGE plpgsql AS $$ BEGIN RETURN QUERY SELECT * FROM s.t; END $$;", "ok");
    [Fact]
    public void fnb0148() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_cursor() RETURNS void LANGUAGE plpgsql AS $$ DECLARE c refcursor; BEGIN OPEN c FOR SELECT * FROM s.t; CLOSE c; END $$;", "ok");
    [Fact]
    public void fnb0149() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_search_path_multi_set() RETURNS integer LANGUAGE sql SET search_path TO s, public, pg_catalog AS $$ SELECT 1 $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0150() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_cost_zero(x integer) RETURNS integer LANGUAGE sql COST 0 AS $$ SELECT x $$;", "error");
    [Fact]
    public void fnb0151() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_rows_one(n integer) RETURNS SETOF integer LANGUAGE sql ROWS 1 AS $$ SELECT generate_series(1,n) $$;", "ok");
    [Fact]
    public void fnb0152() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_schema_qualified_arg(x s.pos_int) RETURNS s.pos_int LANGUAGE sql IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0153() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_addr_arg(a s.addr) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT (a).city $$;", "ok");
    [Fact]
    public void fnb0154() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_mood_arg(m s.mood) RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT m::text $$;", "ok");
    [Fact]
    public void fnb0155() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_out_named_only(OUT x integer, OUT y text) LANGUAGE sql AS $$ SELECT 42, 'hi' $$;", "ok");
    [Fact]
    public void fnb0156() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_parallel_cost_rows(n integer) RETURNS SETOF integer LANGUAGE sql PARALLEL SAFE COST 10 ROWS 500 AS $$ SELECT generate_series(1,n) $$;", "ok");
    [Fact]
    public void fnb0157() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_perform(x integer) RETURNS void LANGUAGE plpgsql AS $$ BEGIN PERFORM s.f(x); END $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0158() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_language_before_returns(x integer) LANGUAGE sql RETURNS integer AS $$ SELECT x $$;", "error");
    [Fact]
    public void fnb0159() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_as_before_language(x integer) RETURNS integer AS $$ SELECT x $$ LANGUAGE sql;", "ok");
    [Fact]
    public void fnb0160() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_trailing_immutable(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$ IMMUTABLE;", "ok");
    [Fact]
    public void fnb0161() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_trailing_strict(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$ STRICT;", "ok");
    [Fact]
    public void fnb0162() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_trailing_cost(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$ COST 50;", "ok");
    [Fact]
    public void fnb0163() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_trailing_parallel(x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$ PARALLEL SAFE;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0164() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_no_parens RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0165() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_bad_returns_setof() RETURNS SETOF LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact]
    public void fnb0166() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_anyelement_anyarray(x anyelement) RETURNS anyarray LANGUAGE sql AS $$ SELECT ARRAY[x] $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnb0167() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_variadic_anyelement(VARIADIC args anyelement[]) RETURNS anyelement LANGUAGE sql AS $$ SELECT args[1] $$;", "error");
    [Fact]
    public void fnb0168() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_setof_anyelement(x anyelement) RETURNS SETOF anyelement LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnb0169() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_plpgsql_inout(INOUT x integer) LANGUAGE plpgsql AS $$ BEGIN x := x * 2; END $$;", "ok");
    [Fact]
    public void fnb0170() => CorpusAssert.Parses(@"CREATE FUNCTION s.fn_all_combo(a integer, b text, VARIADIC c integer[]) RETURNS text LANGUAGE sql AS $$ SELECT b || array_length(c,1)::text $$;", "ok");
    [Fact]
    public void fnc0001() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_simple() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0002() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_add(a integer, b integer) RETURNS integer LANGUAGE sql AS $$ SELECT a + b $$;", "ok");
    [Fact]
    public void fnc0003() => CorpusAssert.Parses(@"CREATE OR REPLACE FUNCTION fnc_orr() RETURNS void LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0004() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_void() RETURNS void LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0005() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_setof() RETURNS SETOF integer LANGUAGE sql AS $$ SELECT 1 UNION ALL SELECT 2 $$;", "ok");
    [Fact]
    public void fnc0006() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_setof_t() RETURNS SETOF s.t LANGUAGE sql AS $$ SELECT * FROM s.t $$;", "ok");
    [Fact]
    public void fnc0007() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_table_cols() RETURNS TABLE(id bigint, nm text) LANGUAGE sql AS $$ SELECT 1::bigint, 'a' $$;", "ok");
    [Fact]
    public void fnc0008() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_record() RETURNS record LANGUAGE sql AS $$ SELECT 1, 'a' $$;", "ok");
    [Fact]
    public void fnc0009() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_immutable(x integer) RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0010() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_stable(x integer) RETURNS integer LANGUAGE sql STABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0011() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_volatile(x integer) RETURNS integer LANGUAGE sql VOLATILE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0012() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_strict(x integer) RETURNS integer LANGUAGE sql STRICT AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0013() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_rnn(x integer) RETURNS integer LANGUAGE sql RETURNS NULL ON NULL INPUT AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0014() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_called(x integer) RETURNS integer LANGUAGE sql CALLED ON NULL INPUT AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0015() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_leakproof(x integer) RETURNS integer LANGUAGE sql IMMUTABLE LEAKPROOF AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0016() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_not_leakproof(x integer) RETURNS integer LANGUAGE sql NOT LEAKPROOF AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0017() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_secdef() RETURNS integer LANGUAGE sql SECURITY DEFINER AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0018() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_secinv() RETURNS integer LANGUAGE sql SECURITY INVOKER AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0019() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_ext_secdef() RETURNS integer LANGUAGE sql EXTERNAL SECURITY DEFINER AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0020() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_ext_secinv() RETURNS integer LANGUAGE sql EXTERNAL SECURITY INVOKER AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0021() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_par_safe() RETURNS integer LANGUAGE sql PARALLEL SAFE AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0022() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_par_restricted() RETURNS integer LANGUAGE sql PARALLEL RESTRICTED AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0023() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_par_unsafe() RETURNS integer LANGUAGE sql PARALLEL UNSAFE AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0024() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_cost() RETURNS integer LANGUAGE sql COST 100 AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0025() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_cost_float() RETURNS integer LANGUAGE sql COST 1.5 AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0026() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_rows() RETURNS SETOF integer LANGUAGE sql ROWS 1000 AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0027() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_set_param() RETURNS integer LANGUAGE sql SET search_path = s AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0028() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_set_from_current() RETURNS integer LANGUAGE sql SET search_path FROM CURRENT AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0029() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_multi_set() RETURNS integer LANGUAGE sql SET search_path = public SET work_mem = '4MB' AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0030() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_in_arg(IN x integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0031() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_out_arg(OUT result integer) RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0032() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_inout_arg(INOUT x integer) LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0033() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_variadic(VARIADIC arr integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT arr[1] $$;", "ok");
    [Fact]
    public void fnc0034() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_in_out_mixed(IN a integer, OUT b integer) LANGUAGE sql AS $$ SELECT a $$;", "ok");
    [Fact]
    public void fnc0035() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_named_default(x integer DEFAULT 5) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0036() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_eq_default(x integer = 5) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0037() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_multi_default(a integer DEFAULT 1, b integer DEFAULT 2) RETURNS integer LANGUAGE sql AS $$ SELECT a + b $$;", "ok");
    [Fact]
    public void fnc0038() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_mixed_default(a integer, b integer DEFAULT 0) RETURNS integer LANGUAGE sql AS $$ SELECT a + b $$;", "ok");
    [Fact]
    public void fnc0039() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_variadic_after(a integer, VARIADIC b integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT a + b[1] $$;", "ok");
    [Fact]
    public void fnc0040() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql() RETURNS integer LANGUAGE plpgsql AS $$ BEGIN RETURN 42; END $$;", "ok");
    [Fact]
    public void fnc0041() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql_strict(x integer) RETURNS integer LANGUAGE plpgsql STRICT AS $$ BEGIN RETURN x * 2; END $$;", "ok");
    [Fact]
    public void fnc0042() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_dollar_tag() RETURNS text LANGUAGE sql AS $myTag$ SELECT 'hello' $myTag$;", "ok");
    [Fact]
    public void fnc0043() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_dollar_empty() RETURNS text LANGUAGE sql AS $$ SELECT 'world' $$;", "ok");
    [Fact]
    public void fnc0044() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_schema_qualified() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0045() => CorpusAssert.Parses(@"CREATE FUNCTION s.fnc_sq() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0046() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_text() RETURNS text LANGUAGE sql AS $$ SELECT 'hello'::text $$;", "ok");
    [Fact]
    public void fnc0047() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_bool() RETURNS boolean LANGUAGE sql AS $$ SELECT true $$;", "ok");
    [Fact]
    public void fnc0048() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_numeric() RETURNS numeric LANGUAGE sql AS $$ SELECT 3.14 $$;", "ok");
    [Fact]
    public void fnc0049() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_json() RETURNS json LANGUAGE sql AS $$ SELECT '{}'::json $$;", "ok");
    [Fact]
    public void fnc0050() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_jsonb() RETURNS jsonb LANGUAGE sql AS $$ SELECT '{}'::jsonb $$;", "ok");
    [Fact]
    public void fnc0051() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_timestamp() RETURNS timestamptz LANGUAGE sql AS $$ SELECT now() $$;", "ok");
    [Fact]
    public void fnc0052() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_enum() RETURNS s.mood LANGUAGE sql AS $$ SELECT 'ok'::s.mood $$;", "ok");
    [Fact]
    public void fnc0053() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_composite() RETURNS s.addr LANGUAGE sql AS $$ SELECT ROW('Main St','Springfield','12345')::s.addr $$;", "ok");
    [Fact]
    public void fnc0054() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_domain() RETURNS s.pos_int LANGUAGE sql AS $$ SELECT 1::s.pos_int $$;", "ok");
    [Fact]
    public void fnc0055() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_arr() RETURNS integer[] LANGUAGE sql AS $$ SELECT ARRAY[1,2,3] $$;", "ok");
    [Fact]
    public void fnc0056() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_table_multi() RETURNS TABLE(a integer, b text, c boolean) LANGUAGE sql AS $$ SELECT 1, 'x', true $$;", "ok");
    [Fact]
    public void fnc0057() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_table_setof() RETURNS TABLE(id bigint, name text) LANGUAGE sql AS $$ SELECT id, name FROM s.t $$;", "ok");
    [Fact]
    public void fnc0058() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_window() RETURNS integer LANGUAGE sql WINDOW AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0059() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_all_opts(x integer DEFAULT 0) RETURNS integer LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE COST 10 SECURITY INVOKER AS $$ SELECT x $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0060() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_opts_order2(x integer) RETURNS integer LANGUAGE sql COST 50 ROWS 0 VOLATILE CALLED ON NULL INPUT PARALLEL UNSAFE SECURITY DEFINER AS $$ SELECT x $$;", "error");
    [Fact]
    public void fnc0061() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_begin_atomic() RETURNS integer LANGUAGE sql BEGIN ATOMIC SELECT 1; END;", "ok");
    [Fact]
    public void fnc0062() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_atomic_expr(a integer, b integer) RETURNS integer LANGUAGE sql BEGIN ATOMIC SELECT a + b; END;", "ok");
    [Fact]
    public void fnc0063() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_atomic_immutable() RETURNS integer LANGUAGE sql IMMUTABLE BEGIN ATOMIC SELECT 42; END;", "ok");
    [Fact]
    public void fnc0064() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_atomic_strict(x integer) RETURNS integer LANGUAGE sql STRICT BEGIN ATOMIC SELECT x * 2; END;", "ok");
    [Fact]
    public void fnc0065() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_atomic_multi() RETURNS void LANGUAGE sql BEGIN ATOMIC INSERT INTO s.t(name) VALUES ('x'); END;", "ok");
    [Fact]
    public void fnc0066() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_out_only(OUT x integer, OUT y integer) LANGUAGE sql AS $$ SELECT 1, 2 $$;", "ok");
    [Fact]
    public void fnc0067() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_inout_rw(INOUT x integer) LANGUAGE plpgsql AS $$ BEGIN x := x * 2; END $$;", "ok");
    [Fact]
    public void fnc0068() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_variadic_text(VARIADIC args text[]) RETURNS text LANGUAGE sql AS $$ SELECT array_to_string(args, ',') $$;", "ok");
    [Fact]
    public void fnc0069() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_default_null(x integer DEFAULT NULL) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0070() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_default_expr(x integer DEFAULT s.f(1)) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0071() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_default_text(s text DEFAULT 'hello') RETURNS text LANGUAGE sql AS $$ SELECT s $$;", "ok");
    [Fact]
    public void fnc0072() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_no_args() RETURNS integer LANGUAGE sql AS $$ SELECT 42 $$;", "ok");
    [Fact]
    public void fnc0073() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_named_in(IN p_val integer) RETURNS integer LANGUAGE sql AS $$ SELECT p_val $$;", "ok");
    [Fact]
    public void fnc0074() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_named_out(OUT p_result text) LANGUAGE sql AS $$ SELECT 'done' $$;", "ok");
    [Fact]
    public void fnc0075() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_named_inout(INOUT p_counter integer) LANGUAGE plpgsql AS $$ BEGIN p_counter := p_counter + 1; END $$;", "ok");
    [Fact]
    public void fnc0076() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_multi_out(OUT a integer, OUT b integer) LANGUAGE sql AS $$ SELECT 1, 2 $$;", "ok");
    [Fact]
    public void fnc0077() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_set_to(x integer) RETURNS integer LANGUAGE sql SET search_path TO public, s AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0078() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_cost_rows_srf() RETURNS SETOF integer LANGUAGE sql COST 20 ROWS 500 AS $$ SELECT generate_series(1,10) $$;", "ok");
    [Fact]
    public void fnc0079() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql_declare() RETURNS integer LANGUAGE plpgsql AS $$ DECLARE v integer := 0; BEGIN v := 10; RETURN v; END $$;", "ok");
    [Fact]
    public void fnc0080() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql_exception() RETURNS integer LANGUAGE plpgsql AS $$ BEGIN RETURN 1; EXCEPTION WHEN others THEN RETURN -1; END $$;", "ok");
    [Fact]
    public void fnc0081() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_or_replace_opts(x integer) RETURNS integer LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$ SELECT x $$ ; CREATE OR REPLACE FUNCTION fnc_or_replace_opts(x integer) RETURNS integer LANGUAGE sql STABLE AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0082() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_case_kw() RETURNS INTEGER LANGUAGE SQL AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0083() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_comment_inline(x integer /* the param */) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0084() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_search_path_empty() RETURNS integer LANGUAGE sql SET search_path = '' AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0085() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_body_string() RETURNS integer LANGUAGE sql AS 'SELECT 1';", "ok");
    [Fact]
    public void fnc0086() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_body_string_escape() RETURNS text LANGUAGE sql AS 'SELECT ''hello''';", "ok");
    [Fact]
    public void fnc0087() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_setof_text() RETURNS SETOF text LANGUAGE sql AS $$ SELECT unnest(ARRAY['a','b','c']) $$;", "ok");
    [Fact]
    public void fnc0088() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_table_one_col() RETURNS TABLE(val integer) LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0089() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql_secdef() RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = s AS $$ BEGIN RETURN 1; END $$;", "ok");
    [Fact]
    public void fnc0090() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_parallel_rows(n integer DEFAULT 100) RETURNS SETOF integer LANGUAGE sql PARALLEL SAFE ROWS 50 AS $$ SELECT generate_series(1,n) $$;", "ok");
    [Fact]
    public void fnc0091() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_transform() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0092() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_in_default_expr(x integer DEFAULT (1 + 2)) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0093() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_type_modifier(x varchar(100)) RETURNS varchar(100) LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0094() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_arr_text() RETURNS text[] LANGUAGE sql AS $$ SELECT ARRAY['a','b'] $$;", "ok");
    [Fact]
    public void fnc0095() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_arr_2d() RETURNS integer[][] LANGUAGE sql AS $$ SELECT ARRAY[[1,2],[3,4]] $$;", "ok");
    [Fact]
    public void fnc0096() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_large_body() RETURNS integer LANGUAGE plpgsql AS $body$ DECLARE i integer; result integer := 0; BEGIN FOR i IN 1..10 LOOP result := result + i; END LOOP; RETURN result; END $body$;", "ok");
    [Fact]
    public void fnc0097() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_table_complex() RETURNS TABLE(id bigint, nm text, val numeric) LANGUAGE sql AS $$ SELECT t.id, t.name, t.val FROM s.t t LIMIT 1 $$;", "ok");
    [Fact]
    public void fnc0098() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql_out(IN x integer, OUT doubled integer, OUT tripled integer) LANGUAGE plpgsql AS $$ BEGIN doubled := x * 2; tripled := x * 3; END $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0099() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_cost_zero() RETURNS integer LANGUAGE sql COST 0 AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0100() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_rows_nonsrf() RETURNS integer LANGUAGE sql ROWS 100 AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0101() => CorpusAssert.Parses(@"CREATE FUNCTION RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0102() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_no_lang() RETURNS integer AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0103() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_no_returns(x integer) LANGUAGE sql AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0104() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_bad_lang() RETURNS integer LANGUAGE nonexistentlang AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0105() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_bad_volatility(x integer) RETURNS integer LANGUAGE sql TEMPORARY AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0106() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_bad_parallel(x integer) RETURNS integer LANGUAGE sql PARALLEL MAYBE AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0107() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_bad_returns_setof() RETURNS SET OF integer LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0108() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_bad_cost_str() RETURNS integer LANGUAGE sql COST 'many' AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0109() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_duplicate_opt() RETURNS integer LANGUAGE sql IMMUTABLE VOLATILE AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0110() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_dup_strict() RETURNS integer LANGUAGE sql STRICT CALLED ON NULL INPUT AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0111() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_variadic_not_last(VARIADIC a integer[], b integer) RETURNS integer LANGUAGE sql AS $$ SELECT b $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0112() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_default_before_required(a integer DEFAULT 1, b integer) RETURNS integer LANGUAGE sql AS $$ SELECT a + b $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0113() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_table_no_cols() RETURNS TABLE() LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0114() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_bad_as() RETURNS integer LANGUAGE sql;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0115() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_double_as() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$ AS $$ SELECT 2 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0116() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_dup_parallel() RETURNS integer LANGUAGE sql PARALLEL SAFE PARALLEL UNSAFE AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0117() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_rows_neg() RETURNS SETOF integer LANGUAGE sql ROWS -1 AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0118() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_cost_neg() RETURNS integer LANGUAGE sql COST -5 AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0119() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_missing_paren2(x integer RETURNS integer) LANGUAGE sql AS $$ SELECT x $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0120() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_bad_returns() RETURNS LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0121() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_setof_table_cols() RETURNS SETOF TABLE(x integer) LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact]
    public void fnc0122() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_window_strict() RETURNS integer LANGUAGE sql WINDOW STRICT AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0123() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_window_immutable() RETURNS integer LANGUAGE sql WINDOW IMMUTABLE AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0124() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_set_equals(x integer) RETURNS integer LANGUAGE sql SET enable_seqscan = off AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0125() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_set_to_val(x integer) RETURNS integer LANGUAGE sql SET work_mem TO '8MB' AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0126() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_atomic_table() RETURNS TABLE(n integer) LANGUAGE sql BEGIN ATOMIC SELECT generate_series(1,5); END;", "ok");
    [Fact]
    public void fnc0127() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_atomic_strict2(x integer) RETURNS integer LANGUAGE sql STRICT BEGIN ATOMIC RETURN x + 1; END;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0128() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_dup_secdef() RETURNS integer LANGUAGE sql SECURITY DEFINER SECURITY INVOKER AS $$ SELECT 1 $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0129() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_both_body_styles() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$ BEGIN ATOMIC SELECT 2; END;", "error");
    [Fact]
    public void fnc0130() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_trigger() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;", "ok");
    [Fact]
    public void fnc0131() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_event_trigger() RETURNS event_trigger LANGUAGE plpgsql AS $$ BEGIN END $$;", "ok");
    [Fact]
    public void fnc0132() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_out_returns_explicit(OUT x integer) RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0133() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_out_returns_wrong(OUT x integer) RETURNS text LANGUAGE sql AS $$ SELECT 'a' $$;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0134() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_two_variadic(VARIADIC a integer[], VARIADIC b text[]) RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact]
    public void fnc0135() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_in_after_out(OUT a integer, IN b integer) RETURNS integer LANGUAGE sql AS $$ SELECT b $$;", "ok");
    [Fact]
    public void fnc0136() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_parallel_leakproof() RETURNS integer LANGUAGE sql IMMUTABLE LEAKPROOF PARALLEL SAFE AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0137() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_setof_record() RETURNS SETOF record LANGUAGE sql AS $$ SELECT 1, 'a' $$;", "ok");
    [Fact]
    public void fnc0138() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql_search_path() RETURNS integer LANGUAGE plpgsql SET search_path = s, public AS $$ BEGIN RETURN (SELECT count(*)::integer FROM t); END $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0139() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_no_arg_list RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$;", "error");
    [Fact]
    public void fnc0140() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_void_plpgsql() RETURNS void LANGUAGE plpgsql AS $$ BEGIN PERFORM 1; END $$;", "ok");
    [Fact]
    public void fnc0141() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_all_modes(IN a integer, OUT b integer, INOUT c integer, VARIADIC d integer[]) LANGUAGE plpgsql AS $$ BEGIN b := a; c := c + 1; END $$;", "ok");
    [Fact]
    public void fnc0142() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_default_cast(x integer DEFAULT '5'::integer) RETURNS integer LANGUAGE sql AS $$ SELECT x $$;", "ok");
    [Fact]
    public void fnc0143() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_cost_integer() RETURNS integer LANGUAGE sql COST 1000 AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0144() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql_secdef_path(x integer) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$ BEGIN RETURN x; END $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0145() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_sql_stable_imm() RETURNS integer LANGUAGE sql STABLE IMMUTABLE AS $$ SELECT 1 $$;", "error");
    [Fact]
    public void fnc0146() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_setof_mood() RETURNS SETOF s.mood LANGUAGE sql AS $$ SELECT status FROM s.t $$;", "ok");
    [Fact]
    public void fnc0147() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_setof_addr() RETURNS SETOF s.addr LANGUAGE sql AS $$ SELECT home FROM s.t $$;", "ok");
    [Fact]
    public void fnc0148() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_table_with_domain() RETURNS TABLE(x s.pos_int) LANGUAGE sql AS $$ SELECT 1::s.pos_int $$;", "ok");
    [Fact]
    public void fnc0149() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql_parallel_safe() RETURNS integer LANGUAGE plpgsql PARALLEL SAFE AS $$ BEGIN RETURN 1; END $$;", "ok");
    [Fact]
    public void fnc0150() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_sql_body_multi_stmt() RETURNS void LANGUAGE sql BEGIN ATOMIC INSERT INTO s.t(name) VALUES ('a'); INSERT INTO s.t(name) VALUES ('b'); END;", "ok");
    [Fact]
    public void fnc0151() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_named_variadic(VARIADIC vals integer[]) RETURNS integer LANGUAGE sql AS $$ SELECT vals[1] $$;", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0152() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_void_no_body() RETURNS void LANGUAGE sql;", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void fnc0153() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_bad_default_pos(a integer DEFAULT 1, b integer, c integer DEFAULT 3) RETURNS integer LANGUAGE sql AS $$ SELECT a + b + c $$;", "error");
    [Fact]
    public void fnc0154() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_setof_void() RETURNS SETOF void LANGUAGE sql AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0155() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_plpgsql_window() RETURNS integer LANGUAGE plpgsql WINDOW AS $$ BEGIN RETURN 1; END $$;", "ok");
    [Fact]
    public void fnc0156() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_or_replace_schema() RETURNS integer LANGUAGE sql AS $$ SELECT 1 $$; CREATE OR REPLACE FUNCTION fnc_or_replace_schema() RETURNS integer LANGUAGE sql AS $$ SELECT 2 $$;", "ok");
    [Fact]
    public void fnc0157() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_set_three() RETURNS integer LANGUAGE sql SET search_path = s SET work_mem = '4MB' SET enable_hashjoin = on AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0158() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_parallel_leakproof_definer() RETURNS integer LANGUAGE sql IMMUTABLE NOT LEAKPROOF PARALLEL SAFE SECURITY DEFINER AS $$ SELECT 1 $$;", "ok");
    [Fact]
    public void fnc0159() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_unnamed_out(integer, OUT integer) LANGUAGE sql AS $$ SELECT $1 $$;", "ok");
    [Fact]
    public void fnc0160() => CorpusAssert.Parses(@"CREATE FUNCTION fnc_returns_setof_enum_table() RETURNS TABLE(m s.mood, cnt bigint) LANGUAGE sql AS $$ SELECT status, count(*) FROM s.t GROUP BY status $$;", "ok");
}
