// <auto-generated> Generated from tests/corpus/*.jsonl by CorpusTestGenerator. Do not edit by hand. </auto-generated>
using Xunit;

namespace PgProj.Core.Tests.Corpus;

public class Corpus_Xml
{
    [Fact]
    public void xmla0001() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo)", "ok");
    [Fact]
    public void xmla0002() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, 'bar')", "ok");
    [Fact]
    public void xmla0003() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, 42)", "ok");
    [Fact]
    public void xmla0004() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlelement(NAME bar, 'baz'))", "ok");
    [Fact]
    public void xmla0005() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes('v' AS a))", "ok");
    [Fact]
    public void xmla0006() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes(1 AS n, 'x' AS val))", "ok");
    [Fact]
    public void xmla0007() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes('a' AS x, 'b' AS y), 'content')", "ok");
    [Fact]
    public void xmla0008() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes(name AS n), name) FROM s.t LIMIT 1", "ok");
    [Fact]
    public void xmla0009() => CorpusAssert.Parses(@"SELECT xmlelement(NAME row, xmlattributes(id AS id, name AS nm), val) FROM s.t LIMIT 1", "ok");
    [Fact]
    public void xmla0010() => CorpusAssert.Parses(@"SELECT xmlelement(NAME ""my-element"", 'hi')", "ok");
    [Fact]
    public void xmla0011() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, NULL::text)", "ok");
    [Fact]
    public void xmla0012() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes(NULL AS a))", "ok");
    [Fact]
    public void xmla0013() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, 'a', 'b', 'c')", "ok");
    [Fact]
    public void xmla0014() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, 1.5::numeric)", "ok");
    [Fact]
    public void xmla0015() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, true::boolean)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0016() => CorpusAssert.Parses(@"SELECT xmlelement('foo')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0017() => CorpusAssert.Parses(@"SELECT xmlelement(NAME)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0018() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes('constant'))", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0019() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes())", "error");
    [Fact]
    public void xmla0020() => CorpusAssert.Parses(@"SELECT xmlforest('hello' AS greeting)", "ok");
    [Fact]
    public void xmla0021() => CorpusAssert.Parses(@"SELECT xmlforest(1 AS a, 2 AS b, 3 AS c)", "ok");
    [Fact]
    public void xmla0022() => CorpusAssert.Parses(@"SELECT xmlforest(name, val, qty) FROM s.t LIMIT 1", "ok");
    [Fact]
    public void xmla0023() => CorpusAssert.Parses(@"SELECT xmlforest(name AS nm, val AS value) FROM s.t LIMIT 1", "ok");
    [Fact]
    public void xmla0024() => CorpusAssert.Parses(@"SELECT xmlforest(NULL::text AS missing)", "ok");
    [Fact]
    public void xmla0025() => CorpusAssert.Parses(@"SELECT xmlforest(id AS id, name AS name, created_at AS ts) FROM s.t LIMIT 1", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0026() => CorpusAssert.Parses(@"SELECT xmlforest()", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0027() => CorpusAssert.Parses(@"SELECT xmlforest('hi')", "error");
    [Fact]
    public void xmla0028() => CorpusAssert.Parses(@"SELECT xmlconcat(xmlelement(NAME a, 'x'), xmlelement(NAME b, 'y'))", "ok");
    [Fact]
    public void xmla0029() => CorpusAssert.Parses(@"SELECT xmlconcat(xmlelement(NAME a), xmlelement(NAME b), xmlelement(NAME c))", "ok");
    [Fact]
    public void xmla0030() => CorpusAssert.Parses(@"SELECT xmlconcat(NULL::xml, xmlelement(NAME a))", "ok");
    [Fact]
    public void xmla0031() => CorpusAssert.Parses(@"SELECT xmlconcat(NULL::xml, NULL::xml)", "ok");
    [Fact]
    public void xmla0032() => CorpusAssert.Parses(@"SELECT xmlconcat(xmlelement(NAME x, 1), xmlelement(NAME y, 2))", "ok");
    [Fact]
    public void xmla0033() => CorpusAssert.Parses(@"SELECT xmlconcat(xmlelement(NAME p, 'a'), xmlelement(NAME p, 'b'))", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0034() => CorpusAssert.Parses(@"SELECT xmlconcat()", "error");
    [Fact]
    public void xmla0035() => CorpusAssert.Parses(@"SELECT xmlpi(NAME foo)", "ok");
    [Fact]
    public void xmla0036() => CorpusAssert.Parses(@"SELECT xmlpi(NAME foo, 'bar=1')", "ok");
    [Fact]
    public void xmla0037() => CorpusAssert.Parses(@"SELECT xmlpi(NAME php, 'echo 1;')", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0038() => CorpusAssert.Parses(@"SELECT xmlpi(NAME xml, 'version=""1.0""')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0039() => CorpusAssert.Parses(@"SELECT xmlpi(NAME foo, 'contains ?> inside')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0040() => CorpusAssert.Parses(@"SELECT xmlpi('foo')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0041() => CorpusAssert.Parses(@"SELECT xmlpi(NAME)", "error");
    [Fact]
    public void xmla0042() => CorpusAssert.Parses(@"SELECT xmlcomment('hello world')", "ok");
    [Fact]
    public void xmla0043() => CorpusAssert.Parses(@"SELECT xmlcomment('no dashes here')", "ok");
    [Fact]
    public void xmla0044() => CorpusAssert.Parses(@"SELECT xmlcomment('')", "ok");
    [Fact]
    public void xmla0045() => CorpusAssert.Parses(@"SELECT xmlcomment(NULL)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0046() => CorpusAssert.Parses(@"SELECT xmlcomment('has -- double dash')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0047() => CorpusAssert.Parses(@"SELECT xmlcomment('ends with dash-')", "error");
    [Fact]
    public void xmla0048() => CorpusAssert.Parses(@"SELECT xmlroot(xmlelement(NAME doc, 'hi'), VERSION '1.0')", "ok");
    [Fact]
    public void xmla0049() => CorpusAssert.Parses(@"SELECT xmlroot(xmlelement(NAME doc, 'x'), VERSION '1.0', STANDALONE YES)", "ok");
    [Fact]
    public void xmla0050() => CorpusAssert.Parses(@"SELECT xmlroot(xmlelement(NAME doc, 'x'), VERSION '1.0', STANDALONE NO)", "ok");
    [Fact]
    public void xmla0051() => CorpusAssert.Parses(@"SELECT xmlroot(xmlelement(NAME doc, 'x'), VERSION '1.0', STANDALONE NO VALUE)", "ok");
    [Fact]
    public void xmla0052() => CorpusAssert.Parses(@"SELECT xmlroot(xmlelement(NAME doc), VERSION NO VALUE)", "ok");
    [Fact]
    public void xmla0053() => CorpusAssert.Parses(@"SELECT xmlroot(xmlelement(NAME doc), VERSION NO VALUE, STANDALONE YES)", "ok");
    [Fact]
    public void xmla0054() => CorpusAssert.Parses(@"SELECT xmlroot(xmlelement(NAME doc), VERSION NO VALUE, STANDALONE NO)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0055() => CorpusAssert.Parses(@"SELECT xmlroot(xmlelement(NAME doc))", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0056() => CorpusAssert.Parses(@"SELECT xmlroot('bad')", "error");
    [Fact]
    public void xmla0057() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT '<foo>bar</foo>')", "ok");
    [Fact]
    public void xmla0058() => CorpusAssert.Parses(@"SELECT xmlparse(CONTENT '<a>1</a><b>2</b>')", "ok");
    [Fact]
    public void xmla0059() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT '<?xml version=""1.0""?><root/>')", "ok");
    [Fact]
    public void xmla0060() => CorpusAssert.Parses(@"SELECT xmlparse(CONTENT 'hello &amp; world')", "ok");
    [Fact]
    public void xmla0061() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT '<root><child/></root>')", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0062() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT '<unclosed>')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0063() => CorpusAssert.Parses(@"SELECT xmlparse(CONTENT '<a>1</a><b>2</b')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0064() => CorpusAssert.Parses(@"SELECT xmlparse('<root/>')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0065() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT)", "error");
    [Fact]
    public void xmla0066() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT NULL)", "ok");
    [Fact]
    public void xmla0067() => CorpusAssert.Parses(@"SELECT xmlserialize(DOCUMENT xmlparse(DOCUMENT '<root/>') AS text)", "ok");
    [Fact]
    public void xmla0068() => CorpusAssert.Parses(@"SELECT xmlserialize(CONTENT xmlparse(CONTENT '<a/><b/>') AS text)", "ok");
    [Fact]
    public void xmla0069() => CorpusAssert.Parses(@"SELECT xmlserialize(DOCUMENT xmlparse(DOCUMENT '<root/>') AS varchar(100))", "ok");
    [Fact]
    public void xmla0070() => CorpusAssert.Parses(@"SELECT xmlserialize(CONTENT xmlelement(NAME x, 1) AS character varying)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0071() => CorpusAssert.Parses(@"SELECT xmlserialize(DOCUMENT xmlelement(NAME root) AS xml)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0072() => CorpusAssert.Parses(@"SELECT xmlserialize(xmlelement(NAME root) AS text)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0073() => CorpusAssert.Parses(@"SELECT xmlserialize(DOCUMENT xmlparse(DOCUMENT '<r/>') AS clob)", "error");
    [Fact]
    public void xmla0074() => CorpusAssert.Parses(@"SELECT xpath('/root/child', xmlparse(DOCUMENT '<root><child>val</child></root>'))", "ok");
    [Fact]
    public void xmla0075() => CorpusAssert.Parses(@"SELECT xpath('/root/@attr', xmlparse(DOCUMENT '<root attr=""v""/>'))", "ok");
    [Fact]
    public void xmla0076() => CorpusAssert.Parses(@"SELECT xpath('//item', xmlparse(DOCUMENT '<list><item>a</item><item>b</item></list>'))", "ok");
    [Fact]
    public void xmla0077() => CorpusAssert.Parses(@"SELECT xpath('/root/child/text()', xmlparse(DOCUMENT '<root><child>val</child></root>'))", "ok");
    [Fact]
    public void xmla0078() => CorpusAssert.Parses(@"SELECT xpath('count(//item)', xmlparse(DOCUMENT '<list><item/><item/></list>'))", "ok");
    [Fact]
    public void xmla0079() => CorpusAssert.Parses(@"SELECT xpath('/root', xmlparse(DOCUMENT '<root/>'), ARRAY[ARRAY['ns','http://example.com']])", "ok");
    [Fact]
    public void xmla0080() => CorpusAssert.Parses(@"SELECT xpath('//ns:el', xmlparse(DOCUMENT '<root xmlns:ns=""http://x.com""><ns:el/></root>'), ARRAY[ARRAY['ns','http://x.com']])", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0081() => CorpusAssert.Parses(@"SELECT xpath('/root', 'not xml')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0082() => CorpusAssert.Parses(@"SELECT xpath('/root', xmlparse(DOCUMENT '<root/>'), ARRAY['ns','http://x.com'])", "error");
    [Fact]
    public void xmla0083() => CorpusAssert.Parses(@"SELECT xpath_exists('/root', xmlparse(DOCUMENT '<root/>'))", "ok");
    [Fact]
    public void xmla0084() => CorpusAssert.Parses(@"SELECT xpath_exists('/missing', xmlparse(DOCUMENT '<root/>'))", "ok");
    [Fact]
    public void xmla0085() => CorpusAssert.Parses(@"SELECT xpath_exists('//item', xmlparse(DOCUMENT '<list><item/></list>'))", "ok");
    [Fact]
    public void xmla0086() => CorpusAssert.Parses(@"SELECT xpath_exists('/root', xmlparse(DOCUMENT '<root/>'), ARRAY[ARRAY['ns','http://example.com']])", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0087() => CorpusAssert.Parses(@"SELECT xpath_exists('/r', 'bad xml')", "error");
    [Fact]
    public void xmla0088() => CorpusAssert.Parses(@"SELECT xmlelement(NAME doc, 'hi') IS DOCUMENT", "ok");
    [Fact]
    public void xmla0089() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT '<root/>') IS DOCUMENT", "ok");
    [Fact]
    public void xmla0090() => CorpusAssert.Parses(@"SELECT xmlparse(CONTENT '<a/><b/>') IS DOCUMENT", "ok");
    [Fact]
    public void xmla0091() => CorpusAssert.Parses(@"SELECT NULL::xml IS DOCUMENT", "ok");
    [Fact]
    public void xmla0092() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT '<root/>') IS NOT DOCUMENT", "ok");
    [Fact]
    public void xmla0093() => CorpusAssert.Parses(@"SELECT xmlparse(CONTENT '<a/><b/>') IS NOT DOCUMENT", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0094() => CorpusAssert.Parses(@"SELECT 42 IS DOCUMENT", "error");
    [Fact]
    public void xmla0095() => CorpusAssert.Parses(@"SELECT table_to_xml('s.t'::regclass, false, false, '')", "ok");
    [Fact]
    public void xmla0096() => CorpusAssert.Parses(@"SELECT table_to_xml('s.t'::regclass, true, false, '')", "ok");
    [Fact]
    public void xmla0097() => CorpusAssert.Parses(@"SELECT table_to_xml('s.t'::regclass, false, true, '')", "ok");
    [Fact]
    public void xmla0098() => CorpusAssert.Parses(@"SELECT table_to_xml('s.t'::regclass, true, true, 'http://example.com')", "ok");
    [Fact]
    public void xmla0099() => CorpusAssert.Parses(@"SELECT table_to_xml('s.t2'::regclass, false, false, '')", "ok");
    [Fact]
    public void xmla0100() => CorpusAssert.Parses(@"SELECT table_to_xmlschema('s.t'::regclass, false, false, '')", "ok");
    [Fact]
    public void xmla0101() => CorpusAssert.Parses(@"SELECT table_to_xml_and_xmlschema('s.t'::regclass, false, false, '')", "ok");
    [Fact]
    public void xmla0102() => CorpusAssert.Parses(@"SELECT query_to_xml('SELECT id, name FROM s.t', false, false, '')", "ok");
    [Fact]
    public void xmla0103() => CorpusAssert.Parses(@"SELECT query_to_xml('SELECT id, name FROM s.t', true, true, 'http://ns.example.com')", "ok");
    [Fact]
    public void xmla0104() => CorpusAssert.Parses(@"SELECT schema_to_xml('s', false, false, '')", "ok");
    [Fact]
    public void xmla0105() => CorpusAssert.Parses(@"SELECT schema_to_xmlschema('s', false, false, '')", "ok");
    [Fact]
    public void xmla0106() => CorpusAssert.Parses(@"SELECT xmlagg(xmlelement(NAME item, name)) FROM s.t", "ok");
    [Fact]
    public void xmla0107() => CorpusAssert.Parses(@"SELECT xmlagg(xmlelement(NAME row, id)) FROM s.t", "ok");
    [Fact]
    public void xmla0108() => CorpusAssert.Parses(@"SELECT xmlagg(xmlelement(NAME item, name) ORDER BY name) FROM s.t", "ok");
    [Fact]
    public void xmla0109() => CorpusAssert.Parses(@"SELECT xmlagg(xmlelement(NAME item, name) ORDER BY name DESC) FROM s.t", "ok");
    [Fact]
    public void xmla0110() => CorpusAssert.Parses(@"SELECT xmlagg(xmlelement(NAME r, id, name) ORDER BY id ASC) FROM s.t", "ok");
    [Fact]
    public void xmla0111() => CorpusAssert.Parses(@"SELECT xmlagg(xmlelement(NAME r, name) ORDER BY id, name) FROM s.t", "ok");
    [Fact]
    public void xmla0112() => CorpusAssert.Parses(@"SELECT xmlagg(xmlelement(NAME item, name)) FILTER (WHERE val > 0) FROM s.t", "ok");
    [Fact]
    public void xmla0113() => CorpusAssert.Parses(@"SELECT xmlelement(NAME root, xmlagg(xmlelement(NAME r, name))) FROM s.t", "ok");
    [Fact]
    public void xmla0114() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row><a>1</a></row><row><a>2</a></row></rows>') COLUMNS a text PATH 'a')", "ok");
    [Fact]
    public void xmla0115() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/root/item' PASSING xmlparse(DOCUMENT '<root><item><id>1</id><val>x</val></item></root>') COLUMNS id int PATH 'id', val text PATH 'val')", "ok");
    [Fact]
    public void xmla0116() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row><n>1</n></row></rows>') COLUMNS rn FOR ORDINALITY, n int PATH 'n')", "ok");
    [Fact]
    public void xmla0117() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row/></rows>') COLUMNS x text PATH 'x' DEFAULT 'missing')", "ok");
    [Fact]
    public void xmla0118() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row><a>1</a></row></rows>') COLUMNS a text NOT NULL PATH 'a')", "ok");
    [Fact]
    public void xmla0119() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row><a>1</a></row></rows>') COLUMNS a text PATH 'a' NOT NULL)", "ok");
    [Fact]
    public void xmla0120() => CorpusAssert.Parses(@"SELECT * FROM xmltable('//item' PASSING xmlparse(DOCUMENT '<root><item>a</item><item>b</item></root>') COLUMNS val text PATH '.')", "ok");
    [Fact]
    public void xmla0121() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/r/row' PASSING xmlparse(DOCUMENT '<r><row><x>1</x><y>2</y></row></r>') COLUMNS x numeric PATH 'x', y numeric PATH 'y')", "ok");
    [Fact]
    public void xmla0122() => CorpusAssert.Parses(@"SELECT * FROM xmltable(XMLNAMESPACES('http://example.com' AS ns), '/ns:root/ns:row' PASSING xmlparse(DOCUMENT '<root xmlns=""http://example.com""><row><v>1</v></row></root>') COLUMNS v text PATH 'v')", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0123() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row/></rows>') COLUMNS a text PATH 'a' NOT NULL)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0124() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row><n>1</n></row></rows>') COLUMNS rn FOR ORDINALITY, rn2 FOR ORDINALITY, n int PATH 'n')", "error");
    [Fact]
    public void xmla0125() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING '<rows><row/></rows>' COLUMNS a text)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0126() => CorpusAssert.Parses(@"SELECT * FROM xmltable(PASSING xmlparse(DOCUMENT '<rows><row/></rows>') COLUMNS a text)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0127() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/row' PASSING xmlparse(DOCUMENT '<rows><row/></rows>') COLUMNS)", "error");
    [Fact]
    public void xmla0128() => CorpusAssert.Parses(@"SELECT XMLEXISTS('/root' PASSING BY VALUE xmlparse(DOCUMENT '<root/>'))", "ok");
    [Fact]
    public void xmla0129() => CorpusAssert.Parses(@"SELECT XMLEXISTS('/root' PASSING BY REF xmlparse(DOCUMENT '<root/>'))", "ok");
    [Fact]
    public void xmla0130() => CorpusAssert.Parses(@"SELECT XMLEXISTS('/root' PASSING xmlparse(DOCUMENT '<root/>'))", "ok");
    [Fact]
    public void xmla0131() => CorpusAssert.Parses(@"SELECT XMLEXISTS('//missing' PASSING xmlparse(DOCUMENT '<root/>'))", "ok");
    [Fact]
    public void xmla0132() => CorpusAssert.Parses(@"SELECT XMLEXISTS('//item' PASSING xmlparse(DOCUMENT '<list><item/><item/></list>'))", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0133() => CorpusAssert.Parses(@"SELECT XMLEXISTS('/r' PASSING 'bad xml')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0134() => CorpusAssert.Parses(@"SELECT XMLEXISTS('/r' xmlparse(DOCUMENT '<r/>'))", "error");
    [Fact]
    public void xmla0135() => CorpusAssert.Parses(@"SELECT xml_is_well_formed('<root/>')", "ok");
    [Fact]
    public void xmla0136() => CorpusAssert.Parses(@"SELECT xml_is_well_formed('<unclosed>')", "ok");
    [Fact]
    public void xmla0137() => CorpusAssert.Parses(@"SELECT xml_is_well_formed_document('<root/>')", "ok");
    [Fact]
    public void xmla0138() => CorpusAssert.Parses(@"SELECT xml_is_well_formed_document('<a/><b/>')", "ok");
    [Fact]
    public void xmla0139() => CorpusAssert.Parses(@"SELECT xml_is_well_formed_content('<a/><b/>')", "ok");
    [Fact]
    public void xmla0140() => CorpusAssert.Parses(@"SELECT xml_is_well_formed_content('<bad')", "ok");
    [Fact]
    public void xmla0141() => CorpusAssert.Parses(@"SELECT xml_is_well_formed(NULL)", "ok");
    [Fact]
    public void xmla0142() => CorpusAssert.Parses(@"SELECT xmltext('hello & world')", "ok");
    [Fact]
    public void xmla0143() => CorpusAssert.Parses(@"SELECT xmltext('<b>bold</b>')", "ok");
    [Fact]
    public void xmla0144() => CorpusAssert.Parses(@"SELECT xmltext('')", "ok");
    [Fact]
    public void xmla0145() => CorpusAssert.Parses(@"SELECT xmltext(NULL)", "ok");
    [Fact]
    public void xmla0146() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes(id AS id), xmlforest(name AS n, val AS v)) FROM s.t LIMIT 1", "ok");
    [Fact]
    public void xmla0147() => CorpusAssert.Parses(@"SELECT xmlconcat(xmlforest(1 AS a), xmlforest(2 AS b))", "ok");
    [Fact]
    public void xmla0148() => CorpusAssert.Parses(@"SELECT xmlelement(NAME root, xmlcomment('comment'), xmlelement(NAME child, 'text'))", "ok");
    [Fact]
    public void xmla0149() => CorpusAssert.Parses(@"SELECT xmlelement(NAME root, xmlpi(NAME target, 'data'), xmlelement(NAME body, 'x'))", "ok");
    [Fact]
    public void xmla0150() => CorpusAssert.Parses(@"SELECT xmlroot(xmlparse(DOCUMENT '<?xml version=""1.0""?><root/>'), VERSION '1.1', STANDALONE YES)", "ok");
    [Fact]
    public void xmla0151() => CorpusAssert.Parses(@"SELECT xmlserialize(DOCUMENT xmlroot(xmlelement(NAME root), VERSION '1.0') AS text)", "ok");
    [Fact]
    public void xmla0152() => CorpusAssert.Parses(@"SELECT (xpath('/root/child/text()', xmlparse(DOCUMENT '<root><child>hello</child></root>')))[1]", "ok");
    [Fact]
    public void xmla0153() => CorpusAssert.Parses(@"SELECT array_length(xpath('//item', xmlparse(DOCUMENT '<list><item/><item/><item/></list>')), 1)", "ok");
    [Fact]
    public void xmla0154() => CorpusAssert.Parses(@"SELECT xmlelement(NAME r, id, name, val) FROM s.t ORDER BY id LIMIT 3", "ok");
    [Fact]
    public void xmla0155() => CorpusAssert.Parses(@"SELECT xmlelement(NAME root, (SELECT xmlagg(xmlelement(NAME item, name)) FROM s.t))", "ok");
    [Fact]
    public void xmla0156() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row><a>1</a></row><row><a>2</a></row><row><a>3</a></row></rows>') COLUMNS rn FOR ORDINALITY, a int PATH 'a') WHERE a > 1", "ok");
    [Fact]
    public void xmla0157() => CorpusAssert.Parses(@"SELECT x.rn, x.a FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row><a>10</a></row></rows>') COLUMNS rn FOR ORDINALITY, a int PATH 'a') AS x", "ok");
    [Fact]
    public void xmla0158() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT '<r xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xsi:nil=""true""/>') IS DOCUMENT", "ok");
    [Fact]
    public void xmla0159() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes('v1' AS a1, 'v2' AS a2, 'v3' AS a3), xmlelement(NAME bar, xmlattributes('x' AS bx), 'inner'))", "ok");
    [Fact]
    public void xmla0160() => CorpusAssert.Parses(@"SELECT xmlagg(xmlelement(NAME r, id)) OVER () FROM s.t LIMIT 1", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmla0161() => CorpusAssert.Parses(@"SELECT xmlelement(NAME root, VARIADIC ARRAY['a','b','c'])", "error");
    [Fact]
    public void xmla0162() => CorpusAssert.Parses(@"SELECT xmlparse(DOCUMENT '<root>' || '</root>')", "ok");
    [Fact]
    public void xmla0163() => CorpusAssert.Parses(@"SELECT xmlserialize(CONTENT xmlconcat(xmlelement(NAME a), xmlelement(NAME b)) AS text)", "ok");
    [Fact]
    public void xmla0164() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes(CURRENT_DATE AS today))", "ok");
    [Fact]
    public void xmla0165() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes(42::text AS n))", "ok");
    [Fact]
    public void xmla0166() => CorpusAssert.Parses(@"SELECT xmlelement(NAME foo, xmlattributes(s.f(1) AS result))", "ok");
    [Fact]
    public void xmla0167() => CorpusAssert.Parses(@"SELECT xpath('/root', xmlparse(DOCUMENT '<root/>'), ARRAY[ARRAY['a','http://a.com'],ARRAY['b','http://b.com']])", "ok");
    [Fact]
    public void xmla0168() => CorpusAssert.Parses(@"SELECT * FROM xmltable('/rows/row' PASSING xmlparse(DOCUMENT '<rows><row><v>hello</v></row></rows>') COLUMNS v text PATH 'v', vx xml PATH 'v')", "ok");
    [Fact]
    public void xmla0169() => CorpusAssert.Parses(@"SELECT xmlelement(NAME root, xmlforest(name AS n, val AS v), xmlcomment('end')) FROM s.t LIMIT 1", "ok");
    [Fact]
    public void xmla0170() => CorpusAssert.Parses(@"SELECT xmlserialize(DOCUMENT xmlparse(DOCUMENT '<root><child>text &amp; more</child></root>') AS text)", "ok");
    [Fact]
    public void xmlb0001() => CorpusAssert.Parses(@"SELECT xmlelement(name foo)", "ok");
    [Fact]
    public void xmlb0002() => CorpusAssert.Parses(@"SELECT xmlelement(name foo, 'hello')", "ok");
    [Fact]
    public void xmlb0003() => CorpusAssert.Parses(@"SELECT xmlelement(name foo, xmlattributes('bar' AS baz))", "ok");
    [Fact]
    public void xmlb0004() => CorpusAssert.Parses(@"SELECT xmlelement(name foo, xmlattributes('x' AS a, 42 AS b), 'content')", "ok");
    [Fact]
    public void xmlb0005() => CorpusAssert.Parses(@"SELECT xmlelement(name outer, xmlelement(name inner, 'nested'))", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0006() => CorpusAssert.Parses(@"SELECT xmlelement('foo')", "error");
    [Fact]
    public void xmlb0007() => CorpusAssert.Parses(@"SELECT xmlforest('abc' AS foo, 123 AS bar)", "ok");
    [Fact]
    public void xmlb0008() => CorpusAssert.Parses(@"SELECT xmlforest(1 AS a)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0009() => CorpusAssert.Parses(@"SELECT xmlforest('x')", "error");
    [Fact]
    public void xmlb0010() => CorpusAssert.Parses(@"SELECT xmlconcat(xmlelement(name a), xmlelement(name b))", "ok");
    [Fact]
    public void xmlb0011() => CorpusAssert.Parses(@"SELECT xmlconcat(xmlelement(name x), NULL)", "ok");
    [Fact]
    public void xmlb0012() => CorpusAssert.Parses(@"SELECT xmlpi(name php, 'echo ""hello"";')", "ok");
    [Fact]
    public void xmlb0013() => CorpusAssert.Parses(@"SELECT xmlpi(name target)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0014() => CorpusAssert.Parses(@"SELECT xmlpi('target')", "error");
    [Fact]
    public void xmlb0015() => CorpusAssert.Parses(@"SELECT xmlcomment('this is a comment')", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0016() => CorpusAssert.Parses(@"SELECT xmlcomment('bad--comment')", "error");
    [Fact]
    public void xmlb0017() => CorpusAssert.Parses(@"SELECT xmlroot(xmlparse(document '<?xml version=""1.0""?><root/>'), version '1.0', standalone yes)", "ok");
    [Fact]
    public void xmlb0018() => CorpusAssert.Parses(@"SELECT xmlroot(xmlparse(document '<?xml version=""1.0""?><root/>'), version no value, standalone no)", "ok");
    [Fact]
    public void xmlb0019() => CorpusAssert.Parses(@"SELECT xmlroot(xmlparse(document '<?xml version=""1.0""?><root/>'), version '1.1')", "ok");
    [Fact]
    public void xmlb0020() => CorpusAssert.Parses(@"SELECT xmlparse(document '<?xml version=""1.0""?><root><child>text</child></root>')", "ok");
    [Fact]
    public void xmlb0021() => CorpusAssert.Parses(@"SELECT xmlparse(content '<a>one</a><b>two</b>')", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0022() => CorpusAssert.Parses(@"SELECT xmlparse(fragment '<a/>')", "error");
    [Fact]
    public void xmlb0023() => CorpusAssert.Parses(@"SELECT xmlserialize(document xmlparse(document '<?xml version=""1.0""?><root/>') AS text)", "ok");
    [Fact]
    public void xmlb0024() => CorpusAssert.Parses(@"SELECT xmlserialize(content xmlelement(name foo, 'bar') AS varchar)", "ok");
    [Fact]
    public void xmlb0025() => CorpusAssert.Parses(@"SELECT xpath('/root/child/text()', xmlparse(document '<?xml version=""1.0""?><root><child>hello</child></root>'))", "ok");
    [Fact]
    public void xmlb0026() => CorpusAssert.Parses(@"SELECT xpath('/a/text()', xmlparse(content '<a>val</a>'), ARRAY[ARRAY['ns','http://example.com']])", "ok");
    [Fact]
    public void xmlb0027() => CorpusAssert.Parses(@"SELECT xpath_exists('/root', xmlparse(content '<root/>'))", "ok");
    [Fact]
    public void xmlb0028() => CorpusAssert.Parses(@"SELECT xpath_exists('/ns:a', xmlparse(content '<ns:a xmlns:ns=""http://x.com""/>'), ARRAY[ARRAY['ns','http://x.com']])", "ok");
    [Fact]
    public void xmlb0029() => CorpusAssert.Parses(@"SELECT xmlparse(document '<?xml version=""1.0""?><root/>') IS DOCUMENT", "ok");
    [Fact]
    public void xmlb0030() => CorpusAssert.Parses(@"SELECT xmlparse(content '<a/><b/>') IS DOCUMENT", "ok");
    [Fact]
    public void xmlb0031() => CorpusAssert.Parses(@"SELECT xmlparse(content '<a/><b/>') IS NOT DOCUMENT", "ok");
    [Fact]
    public void xmlb0032() => CorpusAssert.Parses(@"SELECT xmlexists('//child' PASSING BY VALUE xmlparse(document '<?xml version=""1.0""?><root><child>x</child></root>'))", "ok");
    [Fact]
    public void xmlb0033() => CorpusAssert.Parses(@"SELECT xmlexists('//missing' PASSING xmlparse(content '<root/>'))", "ok");
    [Fact]
    public void xmlb0034() => CorpusAssert.Parses(@"SELECT * FROM XMLTABLE('/root/row' PASSING xmlparse(document '<?xml version=""1.0""?><root><row><id>1</id><val>a</val></row></root>') COLUMNS id int PATH 'id', val text PATH 'val')", "ok");
    [Fact]
    public void xmlb0035() => CorpusAssert.Parses(@"SELECT * FROM XMLTABLE('/rows/row' PASSING xmlparse(document '<?xml version=""1.0""?><rows><row><n>1</n></row></rows>') COLUMNS ord FOR ORDINALITY, n int PATH 'n')", "ok");
    [Fact]
    public void xmlb0036() => CorpusAssert.Parses(@"SELECT * FROM XMLTABLE('/r/item' PASSING xmlparse(document '<?xml version=""1.0""?><r><item/></r>') COLUMNS val text PATH 'missing' DEFAULT 'none')", "ok");
    [Fact]
    public void xmlb0037() => CorpusAssert.Parses(@"SELECT * FROM XMLTABLE(XMLNAMESPACES('http://example.com' AS ns), '/ns:root/ns:item' PASSING xmlparse(document '<?xml version=""1.0""?><root xmlns=""http://example.com""><item>x</item></root>') COLUMNS v text PATH 'text()')", "ok");
    [Fact]
    public void xmlb0038() => CorpusAssert.Parses(@"SELECT table_to_xml('s.t'::regclass, false, false, '')", "ok");
    [Fact]
    public void xmlb0039() => CorpusAssert.Parses(@"SELECT table_to_xml('s.t'::regclass, true, true, 'http://example.com')", "ok");
    [Fact]
    public void xmlb0040() => CorpusAssert.Parses(@"SELECT query_to_xml('SELECT id, name FROM s.t LIMIT 0', false, false, '')", "ok");
    [Fact]
    public void xmlb0041() => CorpusAssert.Parses(@"CREATE TABLE xmlb_agg_test (x xml);
INSERT INTO xmlb_agg_test VALUES (xmlelement(name a)), (xmlelement(name b));
SELECT xmlagg(x) FROM xmlb_agg_test", "ok");
    [Fact]
    public void xmlb0042() => CorpusAssert.Parses(@"CREATE TABLE xmlb_agg_ord (x xml, y int);
INSERT INTO xmlb_agg_ord VALUES (xmlelement(name a), 2), (xmlelement(name b), 1);
SELECT xmlagg(x ORDER BY y) FROM xmlb_agg_ord", "ok");
    [Fact]
    public void xmlb0043() => CorpusAssert.Parses(@"SELECT xml_is_well_formed('<abc/>')", "ok");
    [Fact]
    public void xmlb0044() => CorpusAssert.Parses(@"SELECT xml_is_well_formed('not xml <<')", "ok");
    [Fact]
    public void xmlb0045() => CorpusAssert.Parses(@"SELECT xml_is_well_formed_document('<?xml version=""1.0""?><root/>')", "ok");
    [Fact]
    public void xmlb0046() => CorpusAssert.Parses(@"SELECT xml_is_well_formed_content('<a/><b/>')", "ok");
    [Fact]
    public void xmlb0047() => CorpusAssert.Parses(@"SELECT xmlelement(name foo, xmlattributes(1 AS n, true AS flag), xmlforest('x' AS child))", "ok");
    [Fact]
    public void xmlb0048() => CorpusAssert.Parses(@"SELECT xmlroot(xmlparse(document '<?xml version=""1.0""?><r/>'), version '1.0', standalone no value)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0049() => CorpusAssert.Parses(@"SELECT xmlelement(name foo, xmlattributes())", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0050() => CorpusAssert.Parses(@"SELECT xmlroot(xmlelement(name r), standalone yes)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0051() => CorpusAssert.Parses(@"SELECT xmlserialize(xmlelement(name x) AS text)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0052() => CorpusAssert.Parses(@"SELECT xmlparse(document '<not-closed>')", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0053() => CorpusAssert.Parses(@"SELECT * FROM XMLTABLE('/r' PASSING xmlparse(content '<r/>'))", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0054() => CorpusAssert.Parses(@"SELECT xmlpi(name xml)", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0055() => CorpusAssert.Parses(@"SELECT xmlforest()", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0056() => CorpusAssert.Parses(@"SELECT xmlconcat()", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void xmlb0057() => CorpusAssert.Parses(@"SELECT xmlexists('/root' PASSING BY COPY xmlparse(content '<root/>'))", "error");
}
