// <auto-generated> Generated from tests/corpus/*.jsonl by CorpusTestGenerator. Do not edit by hand. </auto-generated>
using Xunit;

namespace PgProj.Core.Tests.Corpus;

public class Corpus_JsonJsonb
{
    [Fact]
    public void jsn0001() => CorpusAssert.Parses(@"SELECT data -> 'key' FROM s.t", "ok");
    [Fact]
    public void jsn0002() => CorpusAssert.Parses(@"SELECT data ->> 'key' FROM s.t", "ok");
    [Fact]
    public void jsn0003() => CorpusAssert.Parses(@"SELECT data -> 0 FROM s.t", "ok");
    [Fact]
    public void jsn0004() => CorpusAssert.Parses(@"SELECT data ->> 0 FROM s.t", "ok");
    [Fact]
    public void jsn0005() => CorpusAssert.Parses(@"SELECT data #> '{a,b}' FROM s.t", "ok");
    [Fact]
    public void jsn0006() => CorpusAssert.Parses(@"SELECT data #>> '{a,b}' FROM s.t", "ok");
    [Fact]
    public void jsn0007() => CorpusAssert.Parses(@"SELECT data @> '{""x"":1}'::jsonb FROM s.t", "ok");
    [Fact]
    public void jsn0008() => CorpusAssert.Parses(@"SELECT data <@ '{""x"":1}'::jsonb FROM s.t", "ok");
    [Fact]
    public void jsn0009() => CorpusAssert.Parses(@"SELECT data ? 'key' FROM s.t", "ok");
    [Fact]
    public void jsn0010() => CorpusAssert.Parses(@"SELECT data ?| ARRAY['a','b'] FROM s.t", "ok");
    [Fact]
    public void jsn0011() => CorpusAssert.Parses(@"SELECT data ?& ARRAY['a','b'] FROM s.t", "ok");
    [Fact]
    public void jsn0012() => CorpusAssert.Parses(@"SELECT data || '{""y"":2}'::jsonb FROM s.t", "ok");
    [Fact]
    public void jsn0013() => CorpusAssert.Parses(@"SELECT data #- '{a,b}' FROM s.t", "ok");
    [Fact]
    public void jsn0014() => CorpusAssert.Parses(@"SELECT data @? '$.key' FROM s.t", "ok");
    [Fact]
    public void jsn0015() => CorpusAssert.Parses(@"SELECT data @@ '$.val > 0' FROM s.t", "ok");
    [Fact]
    public void jsn0016() => CorpusAssert.Parses(@"SELECT jsonb_path_query(data, '$.key') FROM s.t", "ok");
    [Fact]
    public void jsn0017() => CorpusAssert.Parses(@"SELECT jsonb_path_query(data, '$.items[*]') FROM s.t", "ok");
    [Fact]
    public void jsn0018() => CorpusAssert.Parses(@"SELECT jsonb_path_query_first(data, '$.key') FROM s.t", "ok");
    [Fact]
    public void jsn0019() => CorpusAssert.Parses(@"SELECT jsonb_path_exists(data, '$.key') FROM s.t", "ok");
    [Fact]
    public void jsn0020() => CorpusAssert.Parses(@"SELECT jsonb_path_match(data, '$.val > 0') FROM s.t", "ok");
    [Fact]
    public void jsn0021() => CorpusAssert.Parses(@"SELECT json_build_object('a', 1, 'b', 'hello') FROM s.t", "ok");
    [Fact]
    public void jsn0022() => CorpusAssert.Parses(@"SELECT jsonb_build_array(1, 'two', true, NULL) FROM s.t", "ok");
    [Fact]
    public void jsn0023() => CorpusAssert.Parses(@"SELECT json_object(ARRAY['a','b'], ARRAY['1','2']) FROM s.t", "ok");
    [Fact]
    public void jsn0024() => CorpusAssert.Parses(@"SELECT to_jsonb(val) FROM s.t", "ok");
    [Fact]
    public void jsn0025() => CorpusAssert.Parses(@"SELECT to_jsonb(ROW(name, val)) FROM s.t", "ok");
    [Fact]
    public void jsn0026() => CorpusAssert.Parses(@"SELECT row_to_json(t) FROM s.t AS t", "ok");
    [Fact]
    public void jsn0027() => CorpusAssert.Parses(@"SELECT row_to_json(t, true) FROM s.t AS t", "ok");
    [Fact]
    public void jsn0028() => CorpusAssert.Parses(@"SELECT json_agg(name ORDER BY id) FROM s.t", "ok");
    [Fact]
    public void jsn0029() => CorpusAssert.Parses(@"SELECT jsonb_agg(data) FROM s.t", "ok");
    [Fact]
    public void jsn0030() => CorpusAssert.Parses(@"SELECT jsonb_object_agg(name, val) FROM s.t", "ok");
    [Fact]
    public void jsn0031() => CorpusAssert.Parses(@"SELECT json_object_agg(name, qty ORDER BY name) FROM s.t", "ok");
    [Fact]
    public void jsn0032() => CorpusAssert.Parses(@"SELECT data['key'] FROM s.t", "ok");
    [Fact]
    public void jsn0033() => CorpusAssert.Parses(@"SELECT data['a']['b'] FROM s.t", "ok");
    [Fact]
    public void jsn0034() => CorpusAssert.Parses(@"SELECT '{}' IS JSON FROM s.t", "ok");
    [Fact]
    public void jsn0035() => CorpusAssert.Parses(@"SELECT data IS NOT JSON FROM s.t", "ok");
    [Fact]
    public void jsn0036() => CorpusAssert.Parses(@"SELECT '{""a"":1}' IS JSON OBJECT FROM s.t", "ok");
    [Fact]
    public void jsn0037() => CorpusAssert.Parses(@"SELECT '[1,2]' IS JSON ARRAY FROM s.t", "ok");
    [Fact]
    public void jsn0038() => CorpusAssert.Parses(@"SELECT '1' IS JSON SCALAR FROM s.t", "ok");
    [Fact]
    public void jsn0039() => CorpusAssert.Parses(@"SELECT jt.* FROM s.t, JSON_TABLE(data, '$' COLUMNS (jval text PATH '$.key')) AS jt", "ok");
    [Fact]
    public void jsn0040() => CorpusAssert.Parses(@"SELECT data -> FROM s.t", "error");
    [Fact]
    public void jsn0041() => CorpusAssert.Parses(@"SELECT data @? FROM s.t", "error");
    [Fact]
    public void jsn0042() => CorpusAssert.Parses(@"SELECT data @@ FROM s.t", "error");
    [Fact]
    public void jsn0043() => CorpusAssert.Parses(@"SELECT jsonb_path_query(data '$.key') FROM s.t", "error");
    [Fact]
    public void jsn0044() => CorpusAssert.Parses(@"SELECT data @> FROM s.t", "error");
    [Fact]
    public void jsn0045() => CorpusAssert.Parses(@"SELECT data #- FROM s.t", "error");
    [Fact]
    public void jsn0046() => CorpusAssert.Parses(@"SELECT '{bad json' IS JSON FROM s.t", "ok");
    [Fact]
    public void jsn0047() => CorpusAssert.Parses(@"SELECT data #>> FROM s.t", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void jsn0048() => CorpusAssert.Parses(@"SELECT jsonb_path_query(data, '$[') FROM s.t", "error");
    [Fact]
    public void jsn0049() => CorpusAssert.Parses(@"SELECT data || FROM s.t", "error");
    [Fact]
    public void jsn0050() => CorpusAssert.Parses(@"SELECT jsonb_path_query(data, '$.a', vars := '{""x"":1}'::jsonb, silent := true) FROM s.t", "ok");
}
