// <auto-generated> Generated from tests/corpus/*.jsonl by CorpusTestGenerator. Do not edit by hand. </auto-generated>
using Xunit;

namespace PgProj.Core.Tests.Corpus;

public class Corpus_SetShowReset
{
    [Fact]
    public void ssra0001() => CorpusAssert.Parses(@"SET work_mem = '64MB'", "ok");
    [Fact]
    public void ssra0002() => CorpusAssert.Parses(@"SET work_mem TO '128MB'", "ok");
    [Fact]
    public void ssra0003() => CorpusAssert.Parses(@"SET SESSION work_mem = '64MB'", "ok");
    [Fact]
    public void ssra0004() => CorpusAssert.Parses(@"SET LOCAL work_mem = '64MB'", "ok");
    [Fact]
    public void ssra0005() => CorpusAssert.Parses(@"SET SESSION work_mem TO '64MB'", "ok");
    [Fact]
    public void ssra0006() => CorpusAssert.Parses(@"SET LOCAL work_mem TO '64MB'", "ok");
    [Fact]
    public void ssra0007() => CorpusAssert.Parses(@"SET work_mem TO DEFAULT", "ok");
    [Fact]
    public void ssra0008() => CorpusAssert.Parses(@"SET work_mem = DEFAULT", "ok");
    [Fact]
    public void ssra0009() => CorpusAssert.Parses(@"SET SESSION work_mem TO DEFAULT", "ok");
    [Fact]
    public void ssra0010() => CorpusAssert.Parses(@"SET LOCAL work_mem TO DEFAULT", "ok");
    [Fact]
    public void ssra0011() => CorpusAssert.Parses(@"RESET work_mem", "ok");
    [Fact]
    public void ssra0012() => CorpusAssert.Parses(@"RESET ALL", "ok");
    [Fact]
    public void ssra0013() => CorpusAssert.Parses(@"SHOW work_mem", "ok");
    [Fact]
    public void ssra0014() => CorpusAssert.Parses(@"SHOW ALL", "ok");
    [Fact]
    public void ssra0015() => CorpusAssert.Parses(@"SET TIME ZONE 'UTC'", "ok");
    [Fact]
    public void ssra0016() => CorpusAssert.Parses(@"SET TIME ZONE 'America/New_York'", "ok");
    [Fact]
    public void ssra0017() => CorpusAssert.Parses(@"SET TIME ZONE 'Europe/London'", "ok");
    [Fact]
    public void ssra0018() => CorpusAssert.Parses(@"SET TIME ZONE LOCAL", "ok");
    [Fact]
    public void ssra0019() => CorpusAssert.Parses(@"SET TIME ZONE DEFAULT", "ok");
    [Fact]
    public void ssra0020() => CorpusAssert.Parses(@"SET TIME ZONE -7", "ok");
    [Fact]
    public void ssra0021() => CorpusAssert.Parses(@"SET TIME ZONE 5.5", "ok");
    [Fact]
    public void ssra0022() => CorpusAssert.Parses(@"SET TIME ZONE INTERVAL '-08:00' HOUR TO MINUTE", "ok");
    [Fact]
    public void ssra0023() => CorpusAssert.Parses(@"SET TIME ZONE INTERVAL '+05:30'", "ok");
    [Fact]
    public void ssra0024() => CorpusAssert.Parses(@"SET SESSION TIME ZONE 'UTC'", "ok");
    [Fact]
    public void ssra0025() => CorpusAssert.Parses(@"SET LOCAL TIME ZONE 'UTC'", "ok");
    [Fact]
    public void ssra0026() => CorpusAssert.Parses(@"SHOW TIME ZONE", "ok");
    [Fact]
    public void ssra0027() => CorpusAssert.Parses(@"RESET timezone", "ok");
    [Fact]
    public void ssra0028() => CorpusAssert.Parses(@"SET search_path TO public", "ok");
    [Fact]
    public void ssra0029() => CorpusAssert.Parses(@"SET search_path TO s, public", "ok");
    [Fact]
    public void ssra0030() => CorpusAssert.Parses(@"SET search_path TO s, public, pg_catalog", "ok");
    [Fact]
    public void ssra0031() => CorpusAssert.Parses(@"SET search_path = s, public", "ok");
    [Fact]
    public void ssra0032() => CorpusAssert.Parses(@"SET search_path TO DEFAULT", "ok");
    [Fact]
    public void ssra0033() => CorpusAssert.Parses(@"SHOW search_path", "ok");
    [Fact]
    public void ssra0034() => CorpusAssert.Parses(@"RESET search_path", "ok");
    [Fact]
    public void ssra0035() => CorpusAssert.Parses(@"SET datestyle TO 'ISO, MDY'", "ok");
    [Fact]
    public void ssra0036() => CorpusAssert.Parses(@"SET datestyle TO 'ISO, DMY'", "ok");
    [Fact]
    public void ssra0037() => CorpusAssert.Parses(@"SET datestyle TO 'SQL, MDY'", "ok");
    [Fact]
    public void ssra0038() => CorpusAssert.Parses(@"SET datestyle TO postgres, dmy", "ok");
    [Fact]
    public void ssra0039() => CorpusAssert.Parses(@"SHOW datestyle", "ok");
    [Fact]
    public void ssra0040() => CorpusAssert.Parses(@"RESET datestyle", "ok");
    [Fact]
    public void ssra0041() => CorpusAssert.Parses(@"SET intervalstyle TO 'postgres'", "ok");
    [Fact]
    public void ssra0042() => CorpusAssert.Parses(@"SET intervalstyle TO 'sql_standard'", "ok");
    [Fact]
    public void ssra0043() => CorpusAssert.Parses(@"SET intervalstyle TO 'iso_8601'", "ok");
    [Fact]
    public void ssra0044() => CorpusAssert.Parses(@"SET intervalstyle TO 'postgres_verbose'", "ok");
    [Fact]
    public void ssra0045() => CorpusAssert.Parses(@"SHOW intervalstyle", "ok");
    [Fact]
    public void ssra0046() => CorpusAssert.Parses(@"RESET intervalstyle", "ok");
    [Fact]
    public void ssra0047() => CorpusAssert.Parses(@"SET client_encoding TO 'UTF8'", "ok");
    [Fact]
    public void ssra0048() => CorpusAssert.Parses(@"SET client_encoding = 'UTF8'", "ok");
    [Fact]
    public void ssra0049() => CorpusAssert.Parses(@"SET NAMES 'UTF8'", "ok");
    [Fact]
    public void ssra0050() => CorpusAssert.Parses(@"SHOW client_encoding", "ok");
    [Fact]
    public void ssra0051() => CorpusAssert.Parses(@"RESET client_encoding", "ok");
    [Fact]
    public void ssra0052() => CorpusAssert.Parses(@"SET SCHEMA 'public'", "ok");
    [Fact]
    public void ssra0053() => CorpusAssert.Parses(@"SET SCHEMA 's'", "ok");
    [Fact]
    public void ssra0054() => CorpusAssert.Parses(@"SET lock_timeout TO '5s'", "ok");
    [Fact]
    public void ssra0055() => CorpusAssert.Parses(@"SET lock_timeout = 5000", "ok");
    [Fact]
    public void ssra0056() => CorpusAssert.Parses(@"SET lock_timeout TO 0", "ok");
    [Fact]
    public void ssra0057() => CorpusAssert.Parses(@"SET statement_timeout TO '30s'", "ok");
    [Fact]
    public void ssra0058() => CorpusAssert.Parses(@"SET statement_timeout = 0", "ok");
    [Fact]
    public void ssra0059() => CorpusAssert.Parses(@"SET enable_seqscan TO on", "ok");
    [Fact]
    public void ssra0060() => CorpusAssert.Parses(@"SET enable_seqscan TO off", "ok");
    [Fact]
    public void ssra0061() => CorpusAssert.Parses(@"SET enable_seqscan TO true", "ok");
    [Fact]
    public void ssra0062() => CorpusAssert.Parses(@"SET enable_seqscan TO false", "ok");
    [Fact]
    public void ssra0063() => CorpusAssert.Parses(@"SET enable_seqscan TO 'on'", "ok");
    [Fact]
    public void ssra0064() => CorpusAssert.Parses(@"SET enable_seqscan TO 'off'", "ok");
    [Fact]
    public void ssra0065() => CorpusAssert.Parses(@"SET enable_seqscan = on", "ok");
    [Fact]
    public void ssra0066() => CorpusAssert.Parses(@"SHOW enable_seqscan", "ok");
    [Fact]
    public void ssra0067() => CorpusAssert.Parses(@"RESET enable_seqscan", "ok");
    [Fact]
    public void ssra0068() => CorpusAssert.Parses(@"SET geqo TO on", "ok");
    [Fact]
    public void ssra0069() => CorpusAssert.Parses(@"SET geqo_threshold TO 12", "ok");
    [Fact]
    public void ssra0070() => CorpusAssert.Parses(@"SHOW geqo", "ok");
    [Fact]
    public void ssra0071() => CorpusAssert.Parses(@"SET random_page_cost TO 1.1", "ok");
    [Fact]
    public void ssra0072() => CorpusAssert.Parses(@"SET cpu_tuple_cost TO 0.01", "ok");
    [Fact]
    public void ssra0073() => CorpusAssert.Parses(@"SET max_parallel_workers TO 4", "ok");
    [Fact]
    public void ssra0074() => CorpusAssert.Parses(@"SHOW max_parallel_workers", "ok");
    [Fact]
    public void ssra0075() => CorpusAssert.Parses(@"RESET random_page_cost", "ok");
    [Fact]
    public void ssra0076() => CorpusAssert.Parses(@"SET work_mem TO '256MB'; SHOW work_mem", "ok");
    [Fact]
    public void ssra0077() => CorpusAssert.Parses(@"SET work_mem TO '256MB'; RESET work_mem; SHOW work_mem", "ok");
    [Fact]
    public void ssra0078() => CorpusAssert.Parses(@"SET LOCAL enable_seqscan TO off; SET LOCAL enable_seqscan TO on", "ok");
    [Fact]
    public void ssra0079() => CorpusAssert.Parses(@"SET application_name TO 'myapp'", "ok");
    [Fact]
    public void ssra0080() => CorpusAssert.Parses(@"SET application_name = 'test app with spaces'", "ok");
    [Fact]
    public void ssra0081() => CorpusAssert.Parses(@"SHOW application_name", "ok");
    [Fact]
    public void ssra0082() => CorpusAssert.Parses(@"SET extra_float_digits TO 3", "ok");
    [Fact]
    public void ssra0083() => CorpusAssert.Parses(@"SET extra_float_digits TO -1", "ok");
    [Fact]
    public void ssra0084() => CorpusAssert.Parses(@"SHOW extra_float_digits", "ok");
    [Fact]
    public void ssra0085() => CorpusAssert.Parses(@"SET standard_conforming_strings TO on", "ok");
    [Fact]
    public void ssra0086() => CorpusAssert.Parses(@"SET standard_conforming_strings TO off", "ok");
    [Fact]
    public void ssra0087() => CorpusAssert.Parses(@"SHOW standard_conforming_strings", "ok");
    [Fact]
    public void ssra0088() => CorpusAssert.Parses(@"SET transaction_isolation TO 'read committed'", "ok");
    [Fact]
    public void ssra0089() => CorpusAssert.Parses(@"SET transaction_isolation TO 'repeatable read'", "ok");
    [Fact]
    public void ssra0090() => CorpusAssert.Parses(@"SET transaction_isolation TO 'serializable'", "ok");
    [Fact]
    public void ssra0091() => CorpusAssert.Parses(@"SET transaction_isolation TO 'read uncommitted'", "ok");
    [Fact]
    public void ssra0092() => CorpusAssert.Parses(@"SHOW transaction_isolation", "ok");
    [Fact]
    public void ssra0093() => CorpusAssert.Parses(@"SET transaction_read_only TO on", "ok");
    [Fact]
    public void ssra0094() => CorpusAssert.Parses(@"SET transaction_read_only TO off", "ok");
    [Fact]
    public void ssra0095() => CorpusAssert.Parses(@"SHOW transaction_read_only", "ok");
    [Fact]
    public void ssra0096() => CorpusAssert.Parses(@"SET join_collapse_limit TO 1", "ok");
    [Fact]
    public void ssra0097() => CorpusAssert.Parses(@"SET from_collapse_limit TO 8", "ok");
    [Fact]
    public void ssra0098() => CorpusAssert.Parses(@"SET default_transaction_isolation TO 'serializable'", "ok");
    [Fact]
    public void ssra0099() => CorpusAssert.Parses(@"SHOW default_transaction_isolation", "ok");
    [Fact]
    public void ssra0100() => CorpusAssert.Parses(@"SET xmlbinary TO 'base64'", "ok");
    [Fact]
    public void ssra0101() => CorpusAssert.Parses(@"SET xmlbinary TO 'hex'", "ok");
    [Fact]
    public void ssra0102() => CorpusAssert.Parses(@"SET xmloption TO 'document'", "ok");
    [Fact]
    public void ssra0103() => CorpusAssert.Parses(@"SET xmloption TO 'content'", "ok");
    [Fact]
    public void ssra0104() => CorpusAssert.Parses(@"SET lc_messages TO 'C'", "ok");
    [Fact]
    public void ssra0105() => CorpusAssert.Parses(@"SHOW lc_messages", "ok");
    [Fact]
    public void ssra0106() => CorpusAssert.Parses(@"SET lc_monetary TO 'C'", "ok");
    [Fact]
    public void ssra0107() => CorpusAssert.Parses(@"SET lc_numeric TO 'C'", "ok");
    [Fact]
    public void ssra0108() => CorpusAssert.Parses(@"SET lc_time TO 'C'", "ok");
    [Fact]
    public void ssra0109() => CorpusAssert.Parses(@"SHOW server_version", "ok");
    [Fact]
    public void ssra0110() => CorpusAssert.Parses(@"SHOW server_encoding", "ok");
    [Fact]
    public void ssra0111() => CorpusAssert.Parses(@"SHOW is_superuser", "ok");
    [Fact]
    public void ssra0112() => CorpusAssert.Parses(@"SHOW max_connections", "ok");
    [Fact]
    public void ssra0113() => CorpusAssert.Parses(@"SET SESSION AUTHORIZATION DEFAULT", "ok");
    [Fact]
    public void ssra0114() => CorpusAssert.Parses(@"SHOW session_authorization", "ok");
    [Fact]
    public void ssra0115() => CorpusAssert.Parses(@"SET ROLE NONE", "ok");
    [Fact]
    public void ssra0116() => CorpusAssert.Parses(@"SHOW role", "ok");
    [Fact]
    public void ssra0117() => CorpusAssert.Parses(@"SET check_function_bodies TO on", "ok");
    [Fact]
    public void ssra0118() => CorpusAssert.Parses(@"SET check_function_bodies TO off", "ok");
    [Fact]
    public void ssra0119() => CorpusAssert.Parses(@"SET log_min_duration_statement TO -1", "ok");
    [Fact]
    public void ssra0120() => CorpusAssert.Parses(@"SET log_min_duration_statement TO 0", "ok");
    [Fact]
    public void ssra0121() => CorpusAssert.Parses(@"SET log_min_duration_statement TO '1s'", "ok");
    [Fact]
    public void ssra0122() => CorpusAssert.Parses(@"SET seed TO 0.5", "ok");
    [Fact]
    public void ssra0123() => CorpusAssert.Parses(@"SET seed TO -0.5", "ok");
    [Fact]
    public void ssra0124() => CorpusAssert.Parses(@"SET seed TO 1.0", "ok");
    [Fact]
    public void ssra0125() => CorpusAssert.Parses(@"SET TIME ZONE 'PST8PDT'", "ok");
    [Fact]
    public void ssra0126() => CorpusAssert.Parses(@"SET TIME ZONE 0", "ok");
    [Fact]
    public void ssra0127() => CorpusAssert.Parses(@"SET TIME ZONE INTERVAL '1:00' HOUR TO MINUTE", "ok");
    [Fact]
    public void ssra0128() => CorpusAssert.Parses(@"SET SESSION TIME ZONE LOCAL", "ok");
    [Fact]
    public void ssra0129() => CorpusAssert.Parses(@"SET LOCAL TIME ZONE DEFAULT", "ok");
    [Fact]
    public void ssra0130() => CorpusAssert.Parses(@"set work_mem to '64MB'", "ok");
    [Fact]
    public void ssra0131() => CorpusAssert.Parses(@"Set Work_Mem To '64MB'", "ok");
    [Fact]
    public void ssra0132() => CorpusAssert.Parses(@"SHOW DateStyle", "ok");
    [Fact]
    public void ssra0133() => CorpusAssert.Parses(@"SET maintenance_work_mem TO '512MB'", "ok");
    [Fact]
    public void ssra0134() => CorpusAssert.Parses(@"SET maintenance_work_mem TO '1GB'", "ok");
    [Fact]
    public void ssra0135() => CorpusAssert.Parses(@"SHOW maintenance_work_mem", "ok");
    [Fact]
    public void ssra0136() => CorpusAssert.Parses(@"SET temp_buffers TO '32MB'", "ok");
    [Fact]
    public void ssra0137() => CorpusAssert.Parses(@"SET hash_mem_multiplier TO 1.0", "ok");
    [Fact]
    public void ssra0138() => CorpusAssert.Parses(@"SET effective_cache_size TO '4GB'", "ok");
    [Fact]
    public void ssra0139() => CorpusAssert.Parses(@"RESET ALL", "ok");
    [Fact]
    public void ssra0140() => CorpusAssert.Parses(@"SET search_path TO '""$user""', public", "ok");
    [Fact]
    public void ssra0141() => CorpusAssert.Parses(@"SET search_path TO s", "ok");
    [Fact]
    public void ssra0142() => CorpusAssert.Parses(@"SET search_path TO DEFAULT; SHOW search_path", "ok");
    [Fact]
    public void ssra0143() => CorpusAssert.Parses(@"SET row_security TO on", "ok");
    [Fact]
    public void ssra0144() => CorpusAssert.Parses(@"SET row_security TO off", "ok");
    [Fact]
    public void ssra0145() => CorpusAssert.Parses(@"SHOW row_security", "ok");
    [Fact]
    public void ssra0146() => CorpusAssert.Parses(@"SET enable_hashjoin TO off", "ok");
    [Fact]
    public void ssra0147() => CorpusAssert.Parses(@"SET enable_nestloop TO off", "ok");
    [Fact]
    public void ssra0148() => CorpusAssert.Parses(@"SET enable_mergejoin TO off", "ok");
    [Fact]
    public void ssra0149() => CorpusAssert.Parses(@"SHOW enable_hashjoin", "ok");
    [Fact]
    public void ssra0150() => CorpusAssert.Parses(@"SET enable_parallel_hash TO on", "ok");
    [Fact]
    public void ssra0151() => CorpusAssert.Parses(@"SET session work_mem = '64MB'", "ok");
    [Fact]
    public void ssra0152() => CorpusAssert.Parses(@"SET", "error");
    [Fact]
    public void ssra0153() => CorpusAssert.Parses(@"SET work_mem", "error");
    [Fact]
    public void ssra0154() => CorpusAssert.Parses(@"SET work_mem TO", "error");
    [Fact]
    public void ssra0155() => CorpusAssert.Parses(@"SET work_mem =", "error");
    [Fact]
    public void ssra0156() => CorpusAssert.Parses(@"SET LOCAL LOCAL work_mem TO '64MB'", "error");
    [Fact]
    public void ssra0157() => CorpusAssert.Parses(@"SET SESSION SESSION work_mem TO '64MB'", "error");
    [Fact]
    public void ssra0158() => CorpusAssert.Parses(@"SHOW", "error");
    [Fact]
    public void ssra0159() => CorpusAssert.Parses(@"SHOW work_mem = '64MB'", "error");
    [Fact]
    public void ssra0160() => CorpusAssert.Parses(@"SHOW work_mem TO '64MB'", "error");
    [Fact]
    public void ssra0161() => CorpusAssert.Parses(@"RESET", "error");
    [Fact]
    public void ssra0162() => CorpusAssert.Parses(@"RESET work_mem = DEFAULT", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0163() => CorpusAssert.Parses(@"SET TIME ZONE", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0164() => CorpusAssert.Parses(@"SET TIME ZONE TO 'UTC'", "error");
    [Fact]
    public void ssra0165() => CorpusAssert.Parses(@"SET TIMEZONE TO 'UTC'", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0166() => CorpusAssert.Parses(@"SET TIME TO '12:00'", "error");
    [Fact]
    public void ssra0167() => CorpusAssert.Parses(@"SET = '64MB'", "error");
    [Fact]
    public void ssra0168() => CorpusAssert.Parses(@"SET TO '64MB'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0169() => CorpusAssert.Parses(@"SET work_mem TO '64MB', '128MB'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0170() => CorpusAssert.Parses(@"SET server_version TO '18.0'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0171() => CorpusAssert.Parses(@"SET NAMES TO 'UTF8'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0172() => CorpusAssert.Parses(@"SET SCHEMA TO 'public'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0173() => CorpusAssert.Parses(@"SET search_path TO s public", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0174() => CorpusAssert.Parses(@"SET work_mem TO ON", "error");
    [Fact]
    public void ssra0175() => CorpusAssert.Parses(@"SET LOCAL SESSION work_mem TO '64MB'", "error");
    [Fact]
    public void ssra0176() => CorpusAssert.Parses(@"RESET TIME ZONE", "ok");
    [Fact]
    public void ssra0177() => CorpusAssert.Parses(@"SET work_mem DEFAULT", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0178() => CorpusAssert.Parses(@"SET datestyle TO 'INVALID_STYLE'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0179() => CorpusAssert.Parses(@"SET work_mem TO '64MB' '128MB'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0180() => CorpusAssert.Parses(@"SET nonexistent_guc_param TO 'value'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0181() => CorpusAssert.Parses(@"SET intervalstyle TO 'invalid_style'", "error");
    [Fact]
    public void ssra0182() => CorpusAssert.Parses(@"SHOW ALL ALL", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0183() => CorpusAssert.Parses(@"SET work_mem TO 'not_a_memory_size'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0184() => CorpusAssert.Parses(@"SET TIME ZONE INTERVAL", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0185() => CorpusAssert.Parses(@"SET TIME ZONE 'bad/timezone/name'", "error");
    [Fact]
    public void ssra0186() => CorpusAssert.Parses(@"RESET LOCAL work_mem", "error");
    [Fact]
    public void ssra0187() => CorpusAssert.Parses(@"RESET SESSION work_mem", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0188() => CorpusAssert.Parses(@"SET seed TO 2.0", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0189() => CorpusAssert.Parses(@"SET seed TO -2.0", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0190() => CorpusAssert.Parses(@"SET max_connections TO 200", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0191() => CorpusAssert.Parses(@"SET client_encoding TO 'NOSUCHENCODING'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0192() => CorpusAssert.Parses(@"SET transaction_isolation TO 'dirty read'", "error");
    [Fact]
    public void ssra0193() => CorpusAssert.Parses(@"SET enable_seqscan TO yes", "ok");
    [Fact]
    public void ssra0194() => CorpusAssert.Parses(@"SET enable_seqscan TO no", "ok");
    [Fact]
    public void ssra0195() => CorpusAssert.Parses(@"SET enable_seqscan TO 1", "ok");
    [Fact]
    public void ssra0196() => CorpusAssert.Parses(@"SET enable_seqscan TO 0", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0197() => CorpusAssert.Parses(@"SET xmlbinary TO 'invalid'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0198() => CorpusAssert.Parses(@"SET lc_messages TO 'not_a_real_locale'", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0199() => CorpusAssert.Parses(@"SET geqo_threshold TO -1", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0200() => CorpusAssert.Parses(@"SET SESSION AUTHORIZATION 'invalid_user_that_does_not_exist'", "error");
    [Fact]
    public void ssra0201() => CorpusAssert.Parses(@"SET ROLE 'invalid_role_xyz'", "error");
    [Fact]
    public void ssra0202() => CorpusAssert.Parses(@"SHOW ALL; SET work_mem TO '64MB'", "ok");
    [Fact]
    public void ssra0203() => CorpusAssert.Parses(@"SET transaction_deferrable TO on", "ok");
    [Fact]
    public void ssra0204() => CorpusAssert.Parses(@"SET LOCAL SESSION AUTHORIZATION DEFAULT", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssra0205() => CorpusAssert.Parses(@"SET xmloption TO 'invalid_xmloption'", "error");
    [Fact]
    public void ssrb0001() => CorpusAssert.Parses(@"SET work_mem = '4MB'", "ok");
    [Fact]
    public void ssrb0002() => CorpusAssert.Parses(@"SET work_mem TO '8MB'", "ok");
    [Fact]
    public void ssrb0003() => CorpusAssert.Parses(@"SET SESSION work_mem TO '16MB'", "ok");
    [Fact]
    public void ssrb0004() => CorpusAssert.Parses(@"SET LOCAL work_mem TO '32MB'", "ok");
    [Fact]
    public void ssrb0005() => CorpusAssert.Parses(@"SET work_mem TO DEFAULT", "ok");
    [Fact]
    public void ssrb0006() => CorpusAssert.Parses(@"SET SESSION work_mem TO DEFAULT", "ok");
    [Fact]
    public void ssrb0007() => CorpusAssert.Parses(@"SET LOCAL work_mem TO DEFAULT", "ok");
    [Fact]
    public void ssrb0008() => CorpusAssert.Parses(@"RESET work_mem", "ok");
    [Fact]
    public void ssrb0009() => CorpusAssert.Parses(@"RESET ALL", "ok");
    [Fact]
    public void ssrb0010() => CorpusAssert.Parses(@"SHOW work_mem", "ok");
    [Fact]
    public void ssrb0011() => CorpusAssert.Parses(@"SHOW ALL", "ok");
    [Fact]
    public void ssrb0012() => CorpusAssert.Parses(@"SET search_path TO s, public", "ok");
    [Fact]
    public void ssrb0013() => CorpusAssert.Parses(@"SET search_path TO 's', 'public'", "ok");
    [Fact]
    public void ssrb0014() => CorpusAssert.Parses(@"SET TIME ZONE 'America/New_York'", "ok");
    [Fact]
    public void ssrb0015() => CorpusAssert.Parses(@"SET TIME ZONE LOCAL", "ok");
    [Fact]
    public void ssrb0016() => CorpusAssert.Parses(@"SET TIME ZONE DEFAULT", "ok");
    [Fact]
    public void ssrb0017() => CorpusAssert.Parses(@"SET TIME ZONE 'UTC'", "ok");
    [Fact]
    public void ssrb0018() => CorpusAssert.Parses(@"SET TIME ZONE INTERVAL '+05:30' HOUR TO MINUTE", "ok");
    [Fact]
    public void ssrb0019() => CorpusAssert.Parses(@"SET datestyle TO 'ISO, MDY'", "ok");
    [Fact]
    public void ssrb0020() => CorpusAssert.Parses(@"SET intervalstyle TO 'sql_standard'", "ok");
    [Fact]
    public void ssrb0021() => CorpusAssert.Parses(@"SET client_encoding TO 'UTF8'", "ok");
    [Fact]
    public void ssrb0022() => CorpusAssert.Parses(@"SET enable_seqscan TO on", "ok");
    [Fact]
    public void ssrb0023() => CorpusAssert.Parses(@"SET enable_seqscan TO off", "ok");
    [Fact]
    public void ssrb0024() => CorpusAssert.Parses(@"SET enable_seqscan = true", "ok");
    [Fact]
    public void ssrb0025() => CorpusAssert.Parses(@"SET statement_timeout TO 5000", "ok");
    [Fact]
    public void ssrb0026() => CorpusAssert.Parses(@"SET standard_conforming_strings TO on; SHOW standard_conforming_strings", "ok");
    [Fact]
    public void ssrb0027() => CorpusAssert.Parses(@"SET SESSION AUTHORIZATION DEFAULT", "ok");
    [Fact]
    public void ssrb0028() => CorpusAssert.Parses(@"SET ROLE NONE", "ok");
    [Fact]
    public void ssrb0029() => CorpusAssert.Parses(@"SET", "error");
    [Fact]
    public void ssrb0030() => CorpusAssert.Parses(@"SHOW work_mem = '4MB'", "error");
    [Fact]
    public void ssrb0031() => CorpusAssert.Parses(@"SET work_mem TO", "error");
    [Fact]
    public void ssrb0032() => CorpusAssert.Parses(@"SET LOCAL LOCAL work_mem TO '4MB'", "error");
    [Fact]
    public void ssrb0033() => CorpusAssert.Parses(@"RESET", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssrb0034() => CorpusAssert.Parses(@"SET TIME ZONE", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void ssrb0035() => CorpusAssert.Parses(@"SET work_mem TO '4MB', '8MB'", "error");
}
