// <auto-generated> Generated from tests/corpus/*.jsonl by CorpusTestGenerator. Do not edit by hand. </auto-generated>
using Xunit;

namespace PgProj.Core.Tests.Corpus;

public class Corpus_Explain
{
    [Fact]
    public void expa0001() => CorpusAssert.Parses(@"EXPLAIN SELECT 1", "ok");
    [Fact]
    public void expa0002() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0003() => CorpusAssert.Parses(@"EXPLAIN ANALYZE SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0004() => CorpusAssert.Parses(@"EXPLAIN VERBOSE SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0005() => CorpusAssert.Parses(@"EXPLAIN ANALYZE VERBOSE SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0006() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0007() => CorpusAssert.Parses(@"EXPLAIN (VERBOSE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0008() => CorpusAssert.Parses(@"EXPLAIN (COSTS) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0009() => CorpusAssert.Parses(@"EXPLAIN (BUFFERS) SELECT * FROM s.t", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0010() => CorpusAssert.Parses(@"EXPLAIN (WAL) SELECT * FROM s.t", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0011() => CorpusAssert.Parses(@"EXPLAIN (TIMING) SELECT * FROM s.t", "error");
    [Fact]
    public void expa0012() => CorpusAssert.Parses(@"EXPLAIN (SUMMARY) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0013() => CorpusAssert.Parses(@"EXPLAIN (MEMORY) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0014() => CorpusAssert.Parses(@"EXPLAIN (SETTINGS) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0015() => CorpusAssert.Parses(@"EXPLAIN (FORMAT TEXT) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0016() => CorpusAssert.Parses(@"EXPLAIN (FORMAT XML) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0017() => CorpusAssert.Parses(@"EXPLAIN (FORMAT JSON) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0018() => CorpusAssert.Parses(@"EXPLAIN (FORMAT YAML) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0019() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE TRUE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0020() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE FALSE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0021() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE ON) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0022() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE OFF) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0023() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE 1) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0024() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE 0) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0025() => CorpusAssert.Parses(@"EXPLAIN (VERBOSE TRUE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0026() => CorpusAssert.Parses(@"EXPLAIN (VERBOSE FALSE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0027() => CorpusAssert.Parses(@"EXPLAIN (COSTS TRUE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0028() => CorpusAssert.Parses(@"EXPLAIN (COSTS FALSE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0029() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0030() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0031() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, WAL) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0032() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, TIMING) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0033() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, TIMING FALSE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0034() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, SUMMARY) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0035() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, SUMMARY FALSE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0036() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, BUFFERS) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0037() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, BUFFERS, FORMAT JSON) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0038() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, BUFFERS, FORMAT XML) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0039() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, BUFFERS, FORMAT YAML) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0040() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, BUFFERS, FORMAT TEXT) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0041() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, COSTS, SETTINGS, BUFFERS, WAL, TIMING, SUMMARY, MEMORY, FORMAT JSON) SELECT * FROM s.t", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0042() => CorpusAssert.Parses(@"EXPLAIN (GENERIC_PLAN) SELECT * FROM s.t WHERE id = $1", "ok");
    [Fact]
    public void expa0043() => CorpusAssert.Parses(@"EXPLAIN (GENERIC_PLAN) SELECT * FROM s.t", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0044() => CorpusAssert.Parses(@"EXPLAIN (GENERIC_PLAN, FORMAT JSON) SELECT * FROM s.t WHERE id = $1", "ok");
    [Fact]
    public void expa0045() => CorpusAssert.Parses(@"EXPLAIN INSERT INTO s.t (name, qty) VALUES ('x', 1)", "ok");
    [Fact]
    public void expa0046() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE) INSERT INTO s.t (name, qty) VALUES ('x', 1)", "ok");
    [Fact]
    public void expa0047() => CorpusAssert.Parses(@"EXPLAIN UPDATE s.t SET qty = qty + 1 WHERE id = 1", "ok");
    [Fact]
    public void expa0048() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE) UPDATE s.t SET qty = qty + 1 WHERE id = 1", "ok");
    [Fact]
    public void expa0049() => CorpusAssert.Parses(@"EXPLAIN DELETE FROM s.t WHERE id = 1", "ok");
    [Fact]
    public void expa0050() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE) DELETE FROM s.t WHERE id = 1", "ok");
    [Fact]
    public void expa0051() => CorpusAssert.Parses(@"EXPLAIN MERGE INTO s.t USING s.t2 ON s.t.id = s.t2.t_id WHEN MATCHED THEN UPDATE SET qty = s.t.qty + 1 WHEN NOT MATCHED THEN INSERT (name, qty) VALUES ('new', 0)", "ok");
    [Fact]
    public void expa0052() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE) MERGE INTO s.t USING s.t2 ON s.t.id = s.t2.t_id WHEN MATCHED THEN UPDATE SET qty = s.t.qty + 1 WHEN NOT MATCHED THEN INSERT (name, qty) VALUES ('new', 0)", "ok");
    [Fact]
    public void expa0053() => CorpusAssert.Parses(@"EXPLAIN CREATE TABLE expa_tmp AS SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0054() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE) CREATE TABLE expa_tmp2 AS SELECT * FROM s.t", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0055() => CorpusAssert.Parses(@"PREPARE expa_stmt AS SELECT * FROM s.t WHERE id = $1; EXPLAIN EXECUTE expa_stmt(1)", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0056() => CorpusAssert.Parses(@"PREPARE expa_stmt2 AS SELECT * FROM s.t WHERE id = $1; EXPLAIN (ANALYZE) EXECUTE expa_stmt2(1)", "ok");
    [Fact]
    public void expa0057() => CorpusAssert.Parses(@"EXPLAIN DECLARE cur CURSOR FOR SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0058() => CorpusAssert.Parses(@"EXPLAIN SELECT id, name FROM s.t WHERE qty > 0 ORDER BY name LIMIT 10", "ok");
    [Fact]
    public void expa0059() => CorpusAssert.Parses(@"EXPLAIN SELECT s.t.id, s.t2.label FROM s.t JOIN s.t2 ON s.t.id = s.t2.t_id", "ok");
    [Fact]
    public void expa0060() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t WHERE data @> '{""key"":""val""}'", "ok");
    [Fact]
    public void expa0061() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t WHERE tags @> ARRAY['x']", "ok");
    [Fact]
    public void expa0062() => CorpusAssert.Parses(@"EXPLAIN SELECT status, count(*) FROM s.t GROUP BY status HAVING count(*) > 0", "ok");
    [Fact]
    public void expa0063() => CorpusAssert.Parses(@"EXPLAIN WITH cte AS (SELECT id FROM s.t) SELECT * FROM cte", "ok");
    [Fact]
    public void expa0064() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t UNION SELECT * FROM s.t WHERE qty > 0", "ok");
    [Fact]
    public void expa0065() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t INTERSECT SELECT * FROM s.t WHERE qty > 0", "ok");
    [Fact]
    public void expa0066() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t EXCEPT SELECT * FROM s.t WHERE qty > 0", "ok");
    [Fact]
    public void expa0067() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.v", "ok");
    [Fact]
    public void expa0068() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.mv", "ok");
    [Fact]
    public void expa0069() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.rows_f()", "ok");
    [Fact]
    public void expa0070() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t LEFT JOIN s.t2 ON s.t.id = s.t2.t_id", "ok");
    [Fact]
    public void expa0071() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.parent UNION ALL SELECT id, kind FROM s.child", "ok");
    [Fact]
    public void expa0072() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.events WHERE occurred BETWEEN '2024-01-01' AND '2024-12-31'", "ok");
    [Fact]
    public void expa0073() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t WHERE name LIKE 'a%'", "ok");
    [Fact]
    public void expa0074() => CorpusAssert.Parses(@"EXPLAIN (VERBOSE) SELECT s.t.id, s.t.name FROM s.t", "ok");
    [Fact]
    public void expa0075() => CorpusAssert.Parses(@"EXPLAIN (VERBOSE, FORMAT JSON) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0076() => CorpusAssert.Parses(@"EXPLAIN (COSTS FALSE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0077() => CorpusAssert.Parses(@"EXPLAIN (COSTS OFF) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0078() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0079() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, BUFFERS, FORMAT XML) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0080() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, BUFFERS, FORMAT YAML) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0081() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, BUFFERS, SETTINGS, FORMAT JSON) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0082() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, MEMORY) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0083() => CorpusAssert.Parses(@"EXPLAIN (MEMORY, FORMAT JSON) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0084() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, WAL, BUFFERS) INSERT INTO s.t (name, qty) VALUES ('w', 1)", "ok");
    [Fact]
    public void expa0085() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, TIMING TRUE, SUMMARY TRUE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0086() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, TIMING OFF, SUMMARY OFF) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0087() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE TRUE, VERBOSE TRUE, COSTS TRUE, BUFFERS TRUE, FORMAT TEXT) SELECT 42", "ok");
    [Fact]
    public void expa0088() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE FALSE, VERBOSE FALSE, COSTS FALSE, SETTINGS FALSE) SELECT 42", "ok");
    [Fact]
    public void expa0089() => CorpusAssert.Parses(@"EXPLAIN (SETTINGS TRUE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0090() => CorpusAssert.Parses(@"EXPLAIN (SETTINGS FALSE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0091() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t WHERE id = ANY(ARRAY[1,2,3])", "ok");
    [Fact]
    public void expa0092() => CorpusAssert.Parses(@"EXPLAIN SELECT id, (SELECT count(*) FROM s.t2 WHERE t_id = s.t.id) AS cnt FROM s.t", "ok");
    [Fact]
    public void expa0093() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t WHERE EXISTS (SELECT 1 FROM s.t2 WHERE t_id = s.t.id)", "ok");
    [Fact]
    public void expa0094() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE) SELECT * FROM s.t ORDER BY name", "ok");
    [Fact]
    public void expa0095() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, FORMAT JSON) SELECT count(*) FROM s.t GROUP BY status", "ok");
    [Fact]
    public void expa0096() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t TABLESAMPLE BERNOULLI(50)", "ok");
    [Fact]
    public void expa0097() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t WHERE span @> 5", "ok");
    [Fact]
    public void expa0098() => CorpusAssert.Parses(@"EXPLAIN INSERT INTO s.t (name, qty) SELECT label, 1 FROM s.t2", "ok");
    [Fact]
    public void expa0099() => CorpusAssert.Parses(@"EXPLAIN UPDATE s.t SET val = subq.v FROM (SELECT t_id, sum(amount) AS v FROM s.t2 GROUP BY t_id) AS subq WHERE s.t.id = subq.t_id", "ok");
    [Fact]
    public void expa0100() => CorpusAssert.Parses(@"EXPLAIN DELETE FROM s.t WHERE id IN (SELECT t_id FROM s.t2)", "ok");
    [Fact]
    public void expa0101() => CorpusAssert.Parses(@"EXPLAIN VALUES (1, 'a'), (2, 'b')", "ok");
    [Fact]
    public void expa0102() => CorpusAssert.Parses(@"EXPLAIN (FORMAT JSON) VALUES (1, 'a')", "ok");
    [Fact]
    public void expa0103() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t WHERE home IS NOT NULL", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0104() => CorpusAssert.Parses(@"EXPLAIN SELECT (home).city FROM s.t WHERE home IS NOT NULL", "ok");
    [Fact]
    public void expa0105() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, BUFFERS, WAL, TIMING, SUMMARY, MEMORY, FORMAT JSON) UPDATE s.t SET qty = qty + 1 WHERE id < 0", "ok");
    [Fact]
    public void expa0106() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, BUFFERS, WAL, FORMAT YAML) DELETE FROM s.t WHERE id < 0", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0107() => CorpusAssert.Parses(@"EXPLAIN (GENERIC_PLAN, VERBOSE) SELECT * FROM s.t WHERE id = $1 AND name = $2", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0108() => CorpusAssert.Parses(@"EXPLAIN (GENERIC_PLAN, FORMAT JSON) SELECT * FROM s.t WHERE id = $1", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0109() => CorpusAssert.Parses(@"EXPLAIN (GENERIC_PLAN, COSTS FALSE) SELECT * FROM s.t WHERE id = $1", "ok");
    [Fact]
    public void expa0110() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, FORMAT XML) SELECT id, name FROM s.t WHERE qty > 0", "ok");
    [Fact]
    public void expa0111() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, FORMAT YAML) SELECT id, name FROM s.t WHERE qty > 0", "ok");
    [Fact]
    public void expa0112() => CorpusAssert.Parses(@"EXPLAIN SELECT s.f(qty) FROM s.t", "ok");
    [Fact]
    public void expa0113() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM s.t WHERE id IN (SELECT id FROM s.t WHERE qty > 0)", "ok");
    [Fact]
    public void expa0114() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t WHERE status = 'ok'::s.mood", "ok");
    [Fact]
    public void expa0115() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t LIMIT 10 OFFSET 5", "ok");
    [Fact]
    public void expa0116() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, BUFFERS, SETTINGS, MEMORY, FORMAT JSON) SELECT count(*), status FROM s.t GROUP BY status", "ok");
    [Fact]
    public void expa0117() => CorpusAssert.Parses(@"EXPLAIN WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM r WHERE n < 5) SELECT * FROM r", "ok");
    [Fact]
    public void expa0118() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE) WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM r WHERE n < 5) SELECT * FROM r", "ok");
    [Fact]
    public void expa0119() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t WHERE val BETWEEN 1.0 AND 100.0", "ok");
    [Fact]
    public void expa0120() => CorpusAssert.Parses(@"EXPLAIN SELECT row_number() OVER (PARTITION BY status ORDER BY id) AS rn, * FROM s.t", "ok");
    [Fact]
    public void expa0121() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE) SELECT row_number() OVER (PARTITION BY status ORDER BY id) AS rn, * FROM s.t", "ok");
    [Fact]
    public void expa0122() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t CROSS JOIN s.t2", "ok");
    [Fact]
    public void expa0123() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM s.t NATURAL JOIN s.t2", "ok");
    [Fact]
    public void expa0124() => CorpusAssert.Parses(@"EXPLAIN (SERIALIZE NONE) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0125() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, SERIALIZE TEXT) SELECT * FROM s.t", "ok");
    [Fact]
    public void expa0126() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, SERIALIZE BINARY) SELECT * FROM s.t", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0127() => CorpusAssert.Parses(@"EXPLAIN (SERIALIZE TEXT) SELECT * FROM s.t", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0128() => CorpusAssert.Parses(@"EXPLAIN (SERIALIZE BINARY) SELECT * FROM s.t", "error");
    [Fact]
    public void expa0129() => CorpusAssert.Parses(@"EXPLAIN", "error");
    [Fact]
    public void expa0130() => CorpusAssert.Parses(@"EXPLAIN ()", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0131() => CorpusAssert.Parses(@"EXPLAIN (FORMAT) SELECT 1", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0132() => CorpusAssert.Parses(@"EXPLAIN (FORMAT CSV) SELECT 1", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0133() => CorpusAssert.Parses(@"EXPLAIN (FORMAT HTML) SELECT 1", "error");
    [Fact]
    public void expa0134() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, GENERIC_PLAN) SELECT * FROM s.t WHERE id = $1", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0135() => CorpusAssert.Parses(@"EXPLAIN (BADOPTION) SELECT 1", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0136() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE MAYBE) SELECT 1", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0137() => CorpusAssert.Parses(@"EXPLAIN VERBOSE ANALYZE SELECT 1", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0138() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE FORMAT JSON) SELECT 1", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0139() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE,) SELECT 1", "error");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0140() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE VERBOSE) SELECT 1", "error");
    [Fact]
    public void expa0141() => CorpusAssert.Parses(@"EXPLAIN ANALYZE SELECT", "ok");
    [Fact(Skip = "pending: parser not yet complete")]
    public void expa0142() => CorpusAssert.Parses(@"EXPLAIN SELECT * FROM nonexistent_table_xyz", "error");
    [Fact]
    public void expa0143() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, FORMAT JSON) INSERT INTO s.t (name, qty) VALUES ('z', 99)", "ok");
    [Fact]
    public void expa0144() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, FORMAT YAML) DELETE FROM s.t WHERE id < 0", "ok");
    [Fact]
    public void expa0145() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, VERBOSE, FORMAT XML) UPDATE s.t SET qty = 0 WHERE id < 0", "ok");
    [Fact]
    public void expa0146() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, BUFFERS, WAL, TIMING, SUMMARY, MEMORY, FORMAT JSON) MERGE INTO s.t USING s.t2 ON s.t.id = s.t2.t_id WHEN MATCHED THEN UPDATE SET qty = 0", "ok");
    [Fact]
    public void expa0147() => CorpusAssert.Parses(@"EXPLAIN (VERBOSE ON) SELECT 1", "ok");
    [Fact]
    public void expa0148() => CorpusAssert.Parses(@"EXPLAIN (VERBOSE OFF) SELECT 1", "ok");
    [Fact]
    public void expa0149() => CorpusAssert.Parses(@"EXPLAIN (SUMMARY ON, FORMAT JSON) SELECT count(*) FROM s.t", "ok");
    [Fact]
    public void expa0150() => CorpusAssert.Parses(@"EXPLAIN (ANALYZE, SERIALIZE NONE, BUFFERS, FORMAT JSON) SELECT * FROM s.t", "ok");
}
