blank_issues_enabled: false
contact_links:
  - name: Licensing, modification & commercial inquiries
    url: https://code-cleaners.com/
    about: For permission to modify/redistribute, or for commercial use, contact CodeCleaners d.o.o.
