using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Npgsql;
using PgProj.Core.Model;
using PgProj.Core.Packaging;

namespace PgProj.Core.Data;

/// <summary>
/// Loads a package's embedded <c>data/</c> COPY section (#151) into a target database, after its schema has
/// been deployed. Streams each table's PostgreSQL text-format payload via <c>COPY … FROM STDIN</c> in the
/// package's FK-safe order, then advances identity/serial sequences past the loaded rows.
/// </summary>
/// <remarks>
/// COPY FROM has no <c>OVERRIDING SYSTEM VALUE</c>, so a <c>GENERATED ALWAYS AS IDENTITY</c> column would
/// reject the explicit ids in the dump. For such a table the loader temporarily relaxes the column to
/// <c>GENERATED BY DEFAULT</c> around the COPY and restores <c>ALWAYS</c> afterwards (in a finally), so the
/// final schema matches the project while the exact ids are preserved.
/// </remarks>
public static class CopyDataLoader
{
    /// <summary>Load every embedded data table into <paramref name="connectionString"/>; a no-op for a schema-only package.</summary>
    public static async Task LoadAsync(string connectionString, PgPkg pkg, CancellationToken ct = default)
    {
        if (!pkg.HasData) return;

        await using var conn = new NpgsqlConnection(connectionString);
        await conn.OpenAsync(ct);

        var seqFixups = new List<(string Schema, string Name, string Col)>();
        foreach (var d in pkg.Data)
        {
            var table = pkg.Model.Tables.FirstOrDefault(t =>
                DatabaseModel.NameEquals(t.Schema, d.Schema) && DatabaseModel.NameEquals(t.Name, d.Name));

            var alwaysCols = d.HasAlwaysIdentity && table is not null
                ? table.Columns.Where(c => c is { IsIdentity: true, IdentityKind: "ALWAYS" }).Select(c => c.Name).ToList()
                : new List<string>();

            foreach (var c in alwaysCols)
                await ExecAsync(conn, $"ALTER TABLE {Q(d.Schema)}.{Q(d.Name)} ALTER COLUMN {Q(c)} SET GENERATED BY DEFAULT", ct);
            try
            {
                var colList = string.Join(", ", d.Columns.Select(Q));
                using var writer = conn.BeginTextImport($"COPY {Q(d.Schema)}.{Q(d.Name)} ({colList}) FROM STDIN");
                writer.Write(d.CopyText);
                // Dispose (end of using) completes the COPY.
            }
            finally
            {
                foreach (var c in alwaysCols)
                    await ExecAsync(conn, $"ALTER TABLE {Q(d.Schema)}.{Q(d.Name)} ALTER COLUMN {Q(c)} SET GENERATED ALWAYS", ct);
            }

            if (table is not null)
                foreach (var c in table.Columns.Where(c => c.IsIdentity || c.IsSerial))
                    seqFixups.Add((d.Schema, d.Name, c.Name));
        }

        foreach (var (schema, name, col) in seqFixups)
            await ExecAsync(conn,
                $"SELECT setval(pg_get_serial_sequence('{schema}.{name}', '{col}'), " +
                $"GREATEST((SELECT COALESCE(MAX({Q(col)}), 1) FROM {Q(schema)}.{Q(name)}), 1))", ct);
    }

    private static async Task ExecAsync(NpgsqlConnection conn, string sql, CancellationToken ct)
    {
        await using var cmd = new NpgsqlCommand(sql, conn);
        await cmd.ExecuteNonQueryAsync(ct);
    }

    private static string Q(string ident) => "\"" + ident.Replace("\"", "\"\"") + "\"";
}
