-- ============================================================
-- PgProj deployment script
-- 69 change(s)
-- ============================================================

BEGIN;

-- Create extension btree_gist
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Create schema afd
CREATE SCHEMA IF NOT EXISTS "afd";

-- Create schema reporting
CREATE SCHEMA IF NOT EXISTS "reporting";

-- Create collation afd.case_insensitive
CREATE COLLATION afd.case_insensitive(PROVIDER=icu,LOCALE='und-u-ks-level2',DETERMINISTIC=false);

-- Create textsearchdictionary afd.english_dict
CREATE TEXT SEARCH DICTIONARY afd.english_dict(TEMPLATE=pg_catalog.simple,STOPWORDS=english);

-- Create textsearchconfiguration afd.english_cfg
CREATE TEXT SEARCH CONFIGURATION afd.english_cfg(COPY=pg_catalog.english);

-- Create type afd.address
CREATE TYPE afd.address AS(street text,city text,zip text);

-- Create type afd.float_range
CREATE TYPE afd.float_range AS RANGE(SUBTYPE=float8);

-- Create type afd.mood
CREATE TYPE afd.mood AS ENUM('sad','ok','happy');

-- Create type afd.shell_type
CREATE TYPE afd.shell_type;

-- Create domain afd.email
CREATE DOMAIN afd.email AS text DEFAULT 'unknown@example.com' CONSTRAINT email_format CHECK(VALUE~'^[^@]+@[^@]+\.[^@]+$');

-- Create domain afd.pos_int
CREATE DOMAIN afd.pos_int AS integer NOT NULL CHECK(VALUE>0);

-- Create conversion afd.latin1_to_utf8
CREATE CONVERSION afd.latin1_to_utf8 FOR 'LATIN1' TO 'UTF8' FROM iso8859_1_to_utf8;

-- Create sequence afd.order_no_seq
CREATE SEQUENCE IF NOT EXISTS "afd"."order_no_seq" AS bigint INCREMENT BY 10 MINVALUE 1000 MAXVALUE 9999999999 START WITH 1000 CACHE 5 CYCLE;

-- Create foreigndatawrapper dummy_fdw
CREATE FOREIGN DATA WRAPPER dummy_fdw NO HANDLER NO VALIDATOR OPTIONS(debug 'true');

-- Create server dummy_server
CREATE SERVER dummy_server FOREIGN DATA WRAPPER dummy_fdw OPTIONS(host 'localhost',dbname 'remote');

-- Create table afd.base_entity
CREATE TABLE "afd"."base_entity" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "kind" text NOT NULL,
    PRIMARY KEY ("id")
);

-- Create table afd.customers
CREATE TABLE "afd"."customers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id" integer NOT NULL DEFAULT 1,
    "email" afd.email NOT NULL,
    "full_name" text NOT NULL,
    "code" character(8),
    "short_name" character varying(50),
    "notes" text,
    "balance_cents" bigint NOT NULL DEFAULT 0,
    "score" numeric(10, 2) NOT NULL DEFAULT 0,
    "rating" real,
    "big_rating" double precision,
    "qty" afd.pos_int DEFAULT 1,
    "serial_no" serial,
    "big_serial_no" bigserial,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "born_on" date,
    "wake_time" time without time zone,
    "duration" interval,
    "ip_addr" inet,
    "mac" macaddr,
    "flags" bit(8),
    "varflags" bit varying(16),
    "ext_id" uuid DEFAULT gen_random_uuid(),
    "wallet" money,
    "tags" text[] NOT NULL DEFAULT '{}',
    "scores" integer[],
    "matrix" numeric(6, 2)[][],
    "profile" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "legacy_doc" json,
    "xml_doc" xml,
    "home" afd.address,
    "status" afd.mood NOT NULL DEFAULT 'ok',
    "valid_period" tstzrange,
    "temp_range" afd.float_range,
    "region" circle,
    "search" tsvector,
    "order_no" bigint NOT NULL DEFAULT nextval('afd.order_no_seq'),
    "name_upper" text GENERATED ALWAYS AS (upper(full_name)) STORED,
    "balance_dollars" numeric(20, 2) GENERATED ALWAYS AS (balance_cents/100.0) STORED,
    "discount" integer,
    "referral_email" afd.email,
    CONSTRAINT "customers_pk" PRIMARY KEY ("tenant_id", "id"),
    UNIQUE ("referral_email"),
    CONSTRAINT "customers_email_uq" UNIQUE ("tenant_id", "email"),
    CHECK (discount BETWEEN 0 AND 100),
    CONSTRAINT "customers_score_chk" CHECK (score>=0)
);

-- Create table afd.customers_archive
CREATE TABLE "afd"."customers_archive" (
    "archived_at" timestamp with time zone NOT NULL DEFAULT now()
);

-- Create table afd.document
CREATE TABLE "afd"."document" (
    "title" text NOT NULL,
    "body" text
) INHERITS(afd.base_entity);

-- Create table afd.events
CREATE TABLE "afd"."events" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "occurred" date NOT NULL,
    "kind" text NOT NULL,
    "payload" jsonb,
    PRIMARY KEY ("id", "occurred")
) PARTITION BY RANGE(occurred);

-- Create table afd.orders
CREATE TABLE "afd"."orders" (
    "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    "tenant_id" integer NOT NULL,
    "customer_id" bigint NOT NULL,
    "total_cents" integer NOT NULL DEFAULT 0,
    "placed_at" timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CHECK (total_cents>=0)
);

-- Create table afd.room_booking
CREATE TABLE "afd"."room_booking" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "room_id" integer NOT NULL,
    "during" tstzrange NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT room_no_overlap EXCLUDE USING gist(room_id WITH=,during WITH&&)
);

-- Create foreigntable afd.remote_customers
CREATE FOREIGN TABLE afd.remote_customers(id bigint NOT NULL,email text) SERVER dummy_server OPTIONS(schema_name 'public',table_name 'customers');

-- Create table afd.address_row
CREATE TABLE afd.address_row OF afd.address(PRIMARY KEY(zip));

-- Create table afd.events_2024
CREATE TABLE afd.events_2024 PARTITION OF afd.events FOR VALUES FROM('2024-01-01') TO('2025-01-01');

-- Create table afd.events_default
CREATE TABLE afd.events_default PARTITION OF afd.events DEFAULT;

-- Create index afd.customers_active_idx
CREATE INDEX "customers_active_idx" ON "afd"."customers" (full_name) WHERE is_active;

-- Create index afd.customers_email_idx
CREATE UNIQUE INDEX "customers_email_idx" ON "afd"."customers" (tenant_id, email);

-- Create index afd.customers_name_lower_idx
CREATE INDEX "customers_name_lower_idx" ON "afd"."customers" USING btree (lower(full_name) text_pattern_ops ASC NULLS LAST);

-- Create index afd.customers_profile_gin
CREATE INDEX "customers_profile_gin" ON "afd"."customers" USING gin (profile jsonb_path_ops);

-- Create index afd.customers_region_gist
CREATE INDEX "customers_region_gist" ON "afd"."customers" USING gist (region);

-- Create index afd.customers_tags_gin
CREATE INDEX "customers_tags_gin" ON "afd"."customers" USING gin (tags);

-- Create statistics afd.customers_stats
CREATE STATISTICS afd.customers_stats(ndistinct,dependencies,mcv) ON tenant_id,status,is_active FROM afd.customers;

-- Add foreign key on afd.orders -> afd.customers
ALTER TABLE "afd"."orders" ADD CONSTRAINT "orders_customer_fk" FOREIGN KEY ("tenant_id", "customer_id") REFERENCES "afd"."customers" ("tenant_id", "id") ON DELETE CASCADE ON UPDATE RESTRICT;

-- Create or replace view afd.active_customers_v
CREATE OR REPLACE VIEW "afd"."active_customers_v" AS SELECT tenant_id,id,email,full_name,is_active,status FROM afd.customers WHERE is_active;

-- Create or replace view afd.customer_orders
CREATE OR REPLACE VIEW "afd"."customer_orders" AS SELECT c.tenant_id,c.id AS customer_id,c.email,count(o.id) AS order_count,coalesce(sum(o.total_cents),0) AS total_cents FROM afd.customers c LEFT JOIN afd.orders o ON o.tenant_id=c.tenant_id AND o.customer_id=c.id GROUP BY c.tenant_id,c.id,c.email;

-- Create or replace view reporting.customer_mv
CREATE MATERIALIZED VIEW IF NOT EXISTS "reporting"."customer_mv" AS SELECT status,count(*) AS n,avg(score) AS avg_score FROM afd.customers GROUP BY status;

-- Create or replace function afd.accumulate(bigint, integer[])
CREATE FUNCTION afd.accumulate(INOUT running bigint,VARIADIC vals integer[]) LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
    v integer;
BEGIN
    FOREACH v IN ARRAY vals LOOP
        running := running + v;
    END LOOP;
END;
$$;

-- Create or replace function afd.active_customers()
CREATE FUNCTION afd.active_customers() RETURNS SETOF afd.customers LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT * FROM afd.customers WHERE is_active
$$;

-- Create or replace function afd.add(integer, integer)
CREATE FUNCTION afd.add(a integer,b integer DEFAULT 0) RETURNS integer LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE RETURN a+b;

-- Create or replace function afd.customer_stats(numeric)
CREATE FUNCTION afd.customer_stats(min_score numeric DEFAULT 0) RETURNS TABLE(status afd.mood,customer_count bigint,avg_score numeric) LANGUAGE plpgsql STABLE AS $$
BEGIN
    RETURN QUERY
        SELECT c.status, count(*), avg(c.score)
        FROM afd.customers c
        WHERE c.score >= min_score
        GROUP BY c.status;
END;
$$;

-- Create or replace function afd.log_ddl()
CREATE FUNCTION afd.log_ddl() RETURNS event_trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE NOTICE 'DDL command % executed', tg_tag;
END;
$$;

-- Create or replace function afd.mood_eq(afd.mood, afd.mood)
CREATE FUNCTION afd.mood_eq(a afd.mood,b afd.mood) RETURNS boolean LANGUAGE sql IMMUTABLE STRICT AS $$
    SELECT a = b
$$;

-- Create or replace function afd.mood_to_int(afd.mood)
CREATE FUNCTION afd.mood_to_int(m afd.mood) RETURNS integer LANGUAGE sql IMMUTABLE STRICT AS $$
    SELECT CASE m WHEN 'sad' THEN -1 WHEN 'ok' THEN 0 WHEN 'happy' THEN 1 END
$$;

-- Create or replace function afd.split_name(text, text, text)
CREATE FUNCTION afd.split_name(IN full_name text,OUT first_name text,OUT last_name text) LANGUAGE sql IMMUTABLE AS $$
    SELECT split_part(full_name, ' ', 1),
           split_part(full_name, ' ', 2)
$$;

-- Create or replace function afd.touch_updated_at()
CREATE FUNCTION afd.touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.created_at := now();
    RETURN NEW;
END;
$$;

-- Create or replace function afd.archive_customer(integer, bigint, boolean)
CREATE PROCEDURE afd.archive_customer(IN p_tenant integer,IN p_id bigint,INOUT moved boolean DEFAULT false) LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO afd.customers_archive
    SELECT now(), c.*
    FROM afd.customers c
    WHERE c.tenant_id = p_tenant AND c.id = p_id;

    DELETE FROM afd.customers c
    WHERE c.tenant_id = p_tenant AND c.id = p_id;

    moved := FOUND;
END;
$$;

-- Create aggregate afd.afd.sum_int(integer)
CREATE AGGREGATE afd.sum_int(integer)(SFUNC=int4pl,STYPE=integer,INITCOND='0');

-- Create cast (afd.mood AS integer)
CREATE CAST(afd.mood AS integer) WITH FUNCTION afd.mood_to_int(afd.mood) AS ASSIGNMENT;

-- Create operator afd.===(FUNCTION=afd.mood_eq,LEFTARG=afd.mood,RIGHTARG=afd.mood,COMMUTATOR=OPERATOR(afd.===),HASHES,MERGES)
CREATE OPERATOR afd.===(FUNCTION=afd.mood_eq,LEFTARG=afd.mood,RIGHTARG=afd.mood,COMMUTATOR=OPERATOR(afd.===),HASHES,MERGES);

-- Create operatorclass afd.afd.int_minmax_ops USING btree
CREATE OPERATOR CLASS afd.int_minmax_ops FOR TYPE integer USING btree AS OPERATOR 1<,OPERATOR 2<=,OPERATOR 3=,OPERATOR 4>=,OPERATOR 5>,FUNCTION 1 btint4cmp(integer,integer);

-- Create publication customer_pub
CREATE PUBLICATION customer_pub FOR TABLE afd.customers,afd.orders WITH(publish='insert, update');

-- Create trigger customers_touch on afd.customers
CREATE TRIGGER customers_touch BEFORE UPDATE ON afd.customers FOR EACH ROW WHEN(OLD.full_name IS DISTINCT FROM NEW.full_name) EXECUTE FUNCTION afd.touch_updated_at();

-- Create trigger orders_stmt_audit on afd.orders
CREATE TRIGGER orders_stmt_audit AFTER INSERT OR UPDATE OR DELETE ON afd.orders FOR EACH STATEMENT EXECUTE FUNCTION afd.touch_updated_at();

-- Create rule orders_no_delete on afd.orders
CREATE RULE orders_no_delete AS ON DELETE TO afd.orders DO INSTEAD NOTHING;

-- Create policy customers_tenant_isolation on afd.customers
CREATE POLICY customers_tenant_isolation ON afd.customers AS PERMISSIVE FOR ALL TO PUBLIC USING(tenant_id=current_setting('afd.tenant_id',true)::integer) WITH CHECK(tenant_id=current_setting('afd.tenant_id',true)::integer);

-- Create eventtrigger audit_ddl
CREATE EVENT TRIGGER audit_ddl ON ddl_command_end WHEN TAG IN('CREATE TABLE','ALTER TABLE','DROP TABLE') EXECUTE FUNCTION afd.log_ddl();

-- Create comment 
COMMENT ON SCHEMA afd IS 'All-features showcase schema';

-- Create comment 
COMMENT ON TABLE afd.customers IS 'Customer master records (flagship table)';

-- Create comment 
COMMENT ON COLUMN afd.customers.profile IS 'Arbitrary JSONB customer profile';

-- Create comment 
COMMENT ON VIEW afd.customer_orders IS 'Per-customer order rollup';

-- Create comment 
COMMENT ON MATERIALIZED VIEW reporting.customer_mv IS 'Cached customer counts by status';

-- Create comment 
COMMENT ON FUNCTION afd.add(integer,integer) IS 'Add two integers';

-- Create comment 
COMMENT ON TYPE afd.mood IS 'Three-valued mood enum';

-- Create comment 
COMMENT ON DOMAIN afd.email IS 'Validated email address';

-- Create comment 
COMMENT ON INDEX afd.customers_email_idx IS 'Unique email per tenant';

-- Create comment 
COMMENT ON SEQUENCE afd.order_no_seq IS 'Human-facing order numbers';

-- Create comment 
COMMENT ON TRIGGER customers_touch ON afd.customers IS 'Bumps created_at on rename';

COMMIT;
