-- ============================================================================
-- Corpus fixture schema  (loaded once into the postgres:18 ground-truth DB)
-- ----------------------------------------------------------------------------
-- The ground-truth oracle (tools/pg-oracle.ps1) executes every corpus case in a
-- rolled-back transaction against a database that already has THIS schema loaded.
-- That makes Postgres a *syntactic + semantic* check on self-contained statements:
-- an `expect:ok` case must run cleanly against these objects; an `expect:error`
-- case must be rejected by Postgres (ideally a real syntax error, SQLSTATE 42601).
--
-- CONTRACT: corpus authors may reference any object defined here by its exact
-- name. Anything else a case needs must be created inside the case itself (the
-- whole case runs in one rolled-back transaction, so CREATE ... then use it).
-- Do NOT rename or repurpose objects here without updating CORPUS.md and re-running
-- every category's cases through the oracle.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS s;

-- enum, composite, domain, range -------------------------------------------------
CREATE TYPE s.mood AS ENUM ('sad', 'ok', 'happy');
CREATE TYPE s.addr AS (street text, city text, zip text);
CREATE DOMAIN s.pos_int AS integer CHECK (VALUE > 0);

-- core tables --------------------------------------------------------------------
CREATE TABLE s.t (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text          NOT NULL,
    val        numeric(12,2),
    qty        integer       NOT NULL DEFAULT 0,
    flag       boolean       NOT NULL DEFAULT false,
    tags       text[],
    data       jsonb,
    home       s.addr,
    status     s.mood        NOT NULL DEFAULT 'ok',
    span       int4range,
    created_at timestamptz   NOT NULL DEFAULT now()
);

CREATE TABLE s.t2 (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    t_id  bigint REFERENCES s.t (id) ON DELETE CASCADE,
    label text,
    amount numeric(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE s.parent (id bigint PRIMARY KEY, kind text);
CREATE TABLE s.child  (extra text) INHERITS (s.parent);

-- a partitioned table (range) ----------------------------------------------------
CREATE TABLE s.events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred   date NOT NULL,
    payload    jsonb,
    PRIMARY KEY (id, occurred)
) PARTITION BY RANGE (occurred);
CREATE TABLE s.events_2024 PARTITION OF s.events
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

-- sequence, view, matview --------------------------------------------------------
CREATE SEQUENCE s.seq START 100 INCREMENT 2;
CREATE VIEW s.v AS SELECT id, name, val FROM s.t;
CREATE MATERIALIZED VIEW s.mv AS SELECT status, count(*) AS n FROM s.t GROUP BY status;

-- functions / procedure ----------------------------------------------------------
CREATE FUNCTION s.f(x integer) RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT x + 1 $$;
CREATE FUNCTION s.g(a integer, b integer DEFAULT 0) RETURNS integer LANGUAGE sql AS $$ SELECT a + b $$;
CREATE FUNCTION s.rows_f() RETURNS SETOF s.t LANGUAGE sql AS $$ SELECT * FROM s.t $$;
CREATE PROCEDURE s.p(IN n integer) LANGUAGE plpgsql AS $$ BEGIN PERFORM s.f(n); END $$;

-- a trigger function + trigger so trigger-DDL cases have a target -----------------
CREATE FUNCTION s.trg() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
CREATE TRIGGER t_touch BEFORE UPDATE ON s.t FOR EACH ROW EXECUTE FUNCTION s.trg();

-- an index so index-DDL / drop cases have a target -------------------------------
CREATE INDEX t_name_idx ON s.t (name);

-- a role-free comment anchor -----------------------------------------------------
COMMENT ON TABLE s.t IS 'corpus fixture primary table';
